### ISSUE TITLE
SOAPEngine missing Content-Length in the header of the HTTP response or its value is equal zero!

### ISSUE THREAD

**Issue by reshmyanup** [priore/SOAPEngine#102]
Hello,
I   want to call secured(https) svc service in ios with swift. I am getting the error as 
"SOAPEngine missing Content-Length in the header of the HTTP response or its value is equal zero!"

below is my code 

let SoapMessage:String = "<?xml version='1.0' encoding='utf-8'?><soap:Envelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/' xmlns='http://tempuri.org/'></soap:Body></soap:Envelope>"
        let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.version = VERSION_1_1
        soap.responseHeader = true 
       soap.envelope=SoapMessage
      
        soap.setValue("text/xml; charset=utf-8", forKey:"Content-Type")
        soap.setValue(String(SoapMessage.characters.count), forKey:"Content-Length")
       
        soap.requestURL("http://------.svc",
            soapAction: "http://tempuri.org/---------",
            
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                 print("Response: \(dict)")
                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)
        }

**Comment by priore** [comment]
please read issue #91
