### ISSUE TITLE
Data parsing With Soap Engine in Swift

### ISSUE THREAD

**Issue by ozcan-durak** [priore/SOAPEngine#106]
in swift 2.0 using **SOAP Engine** to parse data.

having a problem while taking data into an NSArray.

      soap.requestURL("URL",
            soapAction: "ActionURL",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                
                var result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
                
From ***NSLog*** the data which i receive is :

    {
        Results =     {
            Result =         (
                            {
                    ILCE = "ALA";
                    KOD = 21894;
                    MAHALLE = "ATATURK";
                    MAHALLEKOD = 57;
                    YOL = "ATATURK";
                },
                            {
                    ILCE = "DEN";
                    KOD = 21894;
                    MAHALLE = "KAZIM D\U0130R\U0130K";
                    MAHALLEKOD = 257;
                    YOL = "ATAT\U00dcRK";
                },
                            {
                    ILCE = "AL\U0130A\U011eA";
                    KOD = 21894;
                    MAHALLE = "K\U00dcLT\U00dcR";
                    MAHALLEKOD = 517;
                    YOL = "ATAT\U00dcRK";
                },

I only want to get the ***Result*** instead of ***Results*** into the NSArray. Here is what i do :

                    let sonuclar = result["Results"]
                    
              ->    let aramalar: NSArray = sonuclar as! NSArray
                    print(aramalar)
    
                    self.aramalar = aramalar
                    self.table.reloadData()
                    
                }) { (error : NSError!) -> Void in
                    
                    NSLog("%@", error)
            }

But at this point on "aramalar" i m reciving an error such 

> Could not cast value of type '__NSDictionaryM' (0x1038ced38) to 'NSArray' (0x1038ce900).

Thanks in advance !

**Comment by priore** [comment]
Hi,
"Results" is a dictionary with one key named "Result", this key named "Result" is a array of dictionary, use :
```swift
let sonuclar = result["Results"]["Result"]

```

**Comment by ozcan-durak** [comment]
Hi when trying this, I m getting an error:

> Value of optional type 'AnyObject?' not unwrapped; did you mean to use '!' or '?'

**Comment by priore** [comment]
sorry, this is basics for swift language, but we not experts on swift
```swift
let sonuclar = dict["Results"]!["Result"]
```

**Comment by ozcan-durak** [comment]
thank you so much that helped.
