### ISSUE TITLE
Sending custom soap request

### ISSUE THREAD

**Issue by ArunIOSM** [priore/SOAPEngine#109]
I'm trying to send a request to a webservice and retrieve the XML through the WSDL file.
The envelope I need to send looks like this:

```xml
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <List
            xmlns="attribute_url">
            <id
                xmlns:a="attribute_url"
                xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                <a:IPAddress i:nil="true"/>
                <a:PasswordHash>abc</a:PasswordHash>
                <a:UserName>abc@abc.co</a:UserName>
            </id>
            <type>74</type>
            <term i:nil="true"
                xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>
            </term>
            <filters i:nil="true"
                xmlns:a="attribute_url"
                xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            </filters>
            <page>1</page>
            <pageSize>20</pageSize>
            <sortBy>ID</sortBy>
            <sortDescending>false</sortDescending>
        </List>
    </s:Body>
</s:Envelope>
```

I am sending request like this:

```objective-c
[soap requestURL:@"wsdl_url" soapAction:@"SoapAction"];
```

But it is sending own Request format, 
Please help me with this.

**Comment by priore** [comment]
I do not recommend to use the wsdl, or method named requestWSDL, its a slows process, but you can use the requestURL, without wsdl, like below :

```objective-c
    NSMutableDictionary *ID = [NSMutableDictionary dictionary];
    [ID setValue:[NSNull null] forKey:@"a:IPAddress"];
    [ID setValue:@"abc" forKey:@"a:PasswordHash"];
    [ID setValue:@"abc@abc.co" forKey:@"a:UserName"];

    [soap setValue:ID forKey:@"id" attributes:@{@"xmlns:a": @"http://attribute_url"}];
    [soap setValue:@(74) forKey:@"type"];
    [soap setValue:nil forKey:@"filters"];
    [soap setValue:@(1) forKey:@"page"];
    [soap setValue:@(20) forKey:@"pageSize"];
    [soap setValue:@"ID" forKey:@"sortBy"];
    [soap setValue:@(NO) forKey:@"sortDescending"];

    soap.replaceNillable = YES; // important!
    [soap requestURL:@"http://attribute_url/service_name_without_wsdl"
          soapAction:@"http://attribute_url/List"];
```

it produces an xml like this :

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Header/>
	<soap:Body>
		<List xmlns="http://attribute_url/">
			<id xmlns:a="http://attribute_url">
				<a:UserName>abc@abc.co</a:UserName>
				<a:PasswordHash>abc</a:PasswordHash>
				<a:IPAddress xsi:nil="true"/>
			</id>
			<type>74</type>
			<filters xsi:nil="true"/>
			<page>1</page>
			<pageSize>20</pageSize>
			<sortBy>ID</sortBy>
			<sortDescending>0</sortDescending>
		</List>
	</soap:Body>
</soap:Envelope>
```

**Comment by ArunIOSM** [comment]
Thanks for replying,

It is helpful but how did I replace tags 
<soap:Envelope> with <s:Envelope>
<soap:Header/> with <s:Header/>
<soap:Body> with <s:Body>

and also remove the following attributes which are coming by default
```

<?xml version="1.0" encoding="utf-8"?>
`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" `
```

Thanks in advance.

**Comment by priore** [comment]
you can use the delegate named **didBeforeSendingURLRequest**, like below :

```objective-c

- (NSMutableURLRequest *)soapEngine:(SOAPEngine *)soapEngine didBeforeSendingURLRequest:(NSMutableURLRequest *)request
{
    NSString *xml = [[NSString alloc] initWithData:[request HTTPBody] encoding:NSUTF8StringEncoding];
    NSLog(@"%@", xml);
    
    //
    // TODO: modify xml here
    //
    
    request.HTTPBody = [xml dataUsingEncoding:NSUTF8StringEncoding];
    return request;
}
```

**Comment by ArunIOSM** [comment]
Thanks priore for helping, you saved my lot of time.

**Comment by ArunIOSM** [comment]
Hi

SoapEngine.framework is working fine on simulator but when i am trying to run on device or trying archive Project, it sends me this error,

_`ld: '/Users/*/Desktop/Desktop 2//*/SOAPEngine64.framework/SOAPEngine64(SOAPEngine64-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`_

Please help me with this. Thanks

**Comment by priore** [comment]
Hello,
what version you have? (you can find it in the .h)

**Comment by ArunIOSM** [comment]
I have version 1.26.3 of SoapEngine64.framework.

**Comment by priore** [comment]
it is a Xcode 7.3 bug when run it from the command line, to create the libraries, now release a new version of our framework that fix it.

**Comment by priore** [comment]
in this last version 1.27 you can change the namespace name of the Envelope tag using the properties named soapNamespace, eg:

```objective-c
soap.soapNamespace = @"s"; // <soap:Envelope become <s:Envelope
```

**Comment by ArunIOSM** [comment]
Is it only work in Xcode 7.3 ???

**Comment by priore** [comment]
absolutely no, but we use Xcode 7.3 to compile the library, unfortunately has this bug.

**Comment by ArunIOSM** [comment]
Xcode is throwing these two issues in Xcode version 7.2

`clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)`

I am not able to understand these errors.

**Comment by priore** [comment]
if you use the swift example, included in the zip of our library, you have the same problem?

**Comment by ArunIOSM** [comment]
I am working in objective C....

**Comment by priore** [comment]
uh sorry, but if you use the Objective-C sample you have same problem ?
