### ISSUE TITLE
send customer header

### ISSUE THREAD

**Issue by haiboss** [priore/SOAPEngine#110]
i using soapengine v 1.26.3.
Code Here:
```swift
func  CheckAunthen()-> String{
        let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.responseHeader = true
        //soap.authorizationMethod = SOAP_AUTH_CUSTOM;
        soap.licenseKey = "eJJDzkPK9Xx+p5cOH7w0Q+AvPdgK1fzWWuUpMaYCq3r1mwf36Ocw6dn0+CLjRaOiSjfXaFQBWMi+TxCpxVF/FA=="
        soap.header  ="<AuthHeader xmlns=\"http://xnetws.vnptphuyen.vn/\"><Username>Hainp.pyn</Username><Password>1</Password><ClientIP>1</ClientIP><AppID>1</AppID></AuthHeader>"
         var result:NSDictionary?
        do {
            result = try soap.syncRequestURL("http://xnetws.vnptphuyen.vn/alarm.asmx",soapAction: "http://xnetws.vnptphuyen.vn/CheckAuthen")
        }catch let error as NSError {
            NSLog("%@Error:",error.description )
            return error.description
        }        
        let jsonStr: String = result!.valueForKeyPath("Body.CheckAuthenResponse.CheckAuthenResult") as! String
        return jsonStr as String!
```

when i call CheckAunthen then allway return error at header . i tester webservice allway return  true  on winform,webform but when using soapengine then error at header.
webservice : http://xnetws.vnptphuyen.vn/alarm.asmx
action : http://xnetws.vnptphuyen.vn/CheckAuthen

pls help me fix responseheader. thx

**Comment by priore** [comment]
you need to set
```swift
soap.authorizationMethod = SOAP_AUTH_CUSTOM
```

**Comment by haiboss** [comment]
thx, priore. 
I set  soap.authorizationMethod = SOAP_AUTH_CUSTOM but error "use of unresolved identify SOAP_AUTH_CUSTOM"

**Comment by priore** [comment]
sorry, in swift should be like below:  
```swift
soap.authorizationMethod = SOAPAuthorization.SOAP_AUTH_CUSTOM
```

**Comment by priore** [comment]
maybe you not have the "Bridging Header" configured correctly ?

http://dr-palaniraja.blogspot.it/2015/02/swift-objective-c-interoperability.html

**Comment by haiboss** [comment]
.blogspot. i don't see it. in Alarm-Bridging-Header.h i import <SOAPEngine64/SOAPEngine.h>. i can send project for you. you can fix it for me. thx

**Comment by priore** [comment]
ok, we have received it, you need to declare the Import for SOAPEngine in your class

```swift
import SOAPEngine64 // <---- important!

public class Alarm {
// your code here
}
```

**Important note:** we recommend to use the latest version [v1.27](https://github.com/priore/SOAPEngine/releases/tag/v1.27) why the version [v1.26.3](https://github.com/priore/SOAPEngine/releases/tag/v1.26.3) that you are using has a bug for bitcode compilation, derived from a bug of Xcode 7.3.

thanks.

**Comment by haiboss** [comment]
thanks.
