### ISSUE TITLE
how to check exprie licenseKey

### ISSUE THREAD

**Issue by haiboss** [priore/SOAPEngine#113]
how to check licenseKey expire.

**Comment by priore** [comment]
the license key does not expire, for the single license is matched to the app bundle-id (eg. com.organization.appname), and for the enterprise license is matched to organization  bundle-id (eg. com.organization).

**Comment by haiboss** [comment]
i want license key using trial 30 day for all device. i test program befor i buy license key.u can send license key for me. i test it with 01 app bundle - id Alarm.vnpt.vn.thx

**Comment by priore** [comment]
Sorry,we not have a time license, but you can use the bundle-id and the license code included in the examples, that can not use in the store.
