### ISSUE TITLE
Code=-1005 "The network connection was lost."

### ISSUE THREAD

**Issue by tyagnesh** [priore/SOAPEngine#114]
`Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x7ffa5cbadea0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLStringKey=http://webservices.***.com/WebService.svc, NSErrorFailingURLKey=http://webservices.***.com/WebService.svc, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The network connection was lost.}}, NSErrorFailingURLStringKey=http://webservices.***.com/WebService.svc, NSErrorFailingURLKey=http://webservices.***.com/WebService.svc, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}`

Sometimes it works perfectly, while in sometimes getting this error. I also search if there is an error from my side but, There is working internet connection on my device. Still getting this error.

Here is my code for requesting.

```
        let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.version = .VERSION_WCF_1_1
        soap.licenseKey = SOAPENGINE_LICENCEKEY
        soap.responseHeader = true
        for var ii = 0; ii < paramsDict.count; ii++
    {
            soap.setValue(sortedValues.objectAtIndex(ii), forKey:sortedKeys11.objectAtIndex(ii).description as! String) 
        }
        soap.requestURL("http://webservices.***.com/WebService.svc",
            soapAction:NSString(format: "http://tempuri.org/IWebService/%@",methodName) as String  ,
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                let result:Dictionary = dict as Dictionary
             completion(returnDict: result)
            }) { (error : NSError!) -> Void in
                completion(returnDict: NSDictionary())
        }
```

**Comment by priore** [comment]
is a generic error returned by NSURLConnection, usually depends on the server, but you can try using the delegate **didBeforeSendingURLRequest** and set **[request AddValue:@"close" forHTTPHeaderField:@"Connection"];** or make the call from the main thread using GCD.

**Comment by tyagnesh** [comment]
Added delegate, but still same problme

**Comment by priore** [comment]
This is only solution [stackoverflow](http://stackoverflow.com/a/25996971/4069848), but if you send the complete code, with webservice link, on our support email we can test it for you.

**Comment by priore** [comment]
Hello @tyagnesh how you solved ?

**Comment by tyagnesh** [comment]
No its same, every time I’m getting this error

**Comment by priore** [comment]
we now have the same problem but only on a simulator with ios 8.x, instead for other versions of the device works fine, but this problem replicated for any library, even AFNetworking.

**Comment by priore** [comment]
Is very very strange, but after disable Avast antivirus from ours Mac, all calls to networking, from simulator with iOS 8.x, work fine.

**Comment by doncorsean** [comment]
Getting kCFStreamErrorCodeKey=32 as well. Is there a workaround?
