### ISSUE TITLE
licenseKey is not working anymore

### ISSUE THREAD

**Issue by tyagnesh** [priore/SOAPEngine#115]
Yesterday I upgraded SOAPEngine famework from 1.21.1 to 1.27 and my licenseKey is not working.
I'm sure I have not changed any code, just replace framework with new.
Still I checked via downgrading framework from 1.27 to 1.21.1 and licenseKey working like charm.

So I think I can not upgrade SOAPEngine framework with new one and must need to use old one.
Is it so???

**Comment by priore** [comment]
The license works with any version 1.x, if you can communicate to us the your order number, we can retrieve the bundle and license for try it.

**Comment by tyagnesh** [comment]
Hello Support,

 

Please have look the thread

 

Order number: 6CU9916804274551G 

 

Thanks and Regards

Yagnesh Tatmiya | yagnesh@eheuristic.com | www.eheuristic.com

**Comment by priore** [comment]
We tested it with your bundle (com.curranttheapp-identifier
.xxxxx, where xxxxx is a name of your app) and your enterprise license key, it is working perfectly, please check again you bundle and license, may recover them from the email sent after the license generation.
