### ISSUE TITLE
the first SOAPEngine request is really slow to start

### ISSUE THREAD

**Issue by primax79** [priore/SOAPEngine#116]
the first SOAPEngine request is really slow to start
it took seconds between the first SOAPEngine initialization and the starting of the request

i think it's checking the licenseKey, but it's really slow. The user cannot wait seconds for the library initialization

**Comment by priore** [comment]
the license is checked in a separate asynchronous background task, for not to slow down the requests, what version you have?

**Comment by priore** [comment]
Try to change the value for property named **actionNamespaceSlash**.
