### ISSUE TITLE
How to Send HTTP body through the SOAPEngine

### ISSUE THREAD

**Issue by himanshi-nyllabs** [priore/SOAPEngine#117]
Swift version:
soap.setValue("Genesis", forKey: "BookName")
        soap.setIntegerValue(1, forKey: "chapter")
        soap.requestURL("http://www.prioregroup.com/services/americanbible.asmx",

I have requestURL and a request HTTP body. How to send HTTP body through the SOAPEngine?

**Comment by priore** [comment]
I not understand, SOAPEngine supports only SOAP protocol data that requiring defined specifications, is not a client for generic requests.

**Comment by joyeshkakkar** [comment]
On the same question, we have a request URL, SOAP Action and also the request body where I set all the necessary security credentials and other related data. This is the request body which I get through wsdl.
Thanks

**Comment by priore** [comment]
you can use the delegate named didBeforeSendingURLRequest for to alter the request.
