### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by abhi2412shek** [priore/SOAPEngine#118]
I am trying to make a secure connection to the server through "https://", but the i get an error response as "SOAPEngine connection fail! - An SSL error has occurred and a secure connection to the server cannot be made.". i have enabled selfSigned to true.

is there any more changes i need to make.?

**Comment by priore** [comment]
Apple made a radical decision with Xcode 7 (and iOS9), disabling all unsecured HTTP traffic from iOS apps, as a part of [App Transport Security (ATS)](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/).

Please, read this [Security for Xcode 7.x](https://github.com/priore/SOAPEngine#security-for-xcode-7x)
