### ISSUE TITLE
Cannot get response from asmx webservice

### ISSUE THREAD

**Issue by mrpkarthik** [priore/SOAPEngine#121]
I have a web service(asmx) method that returns data in JSON Format..

SOAP Engine is not responding if web service has 300+ records to return...
each record has 4 elements.

for example )
  In my case 
    " GetVerses " method not returning any data if we have more than 300 records in server ...  

``` swift
 soap.setValue("Genesis", forKey: "BookName")
        soap.setIntegerValue(1, forKey: "chapter")
        soap.requestURL("http://www.prioregroup.com/services/americanbible.asmx",
            soapAction: "http://www.prioregroup.com/GetVerses",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                var book:Dictionary = dict as Dictionary
                let verses:NSArray = book["BibleBookChapterVerse"] as! NSArray
                self.verses = verses
                self.table.reloadData()
            }) { (error : NSError!) -> Void in      
                NSLog("%@", error)
        }
```

I am using licensed framework version.

Also SOAP Engine works if web service returns less than 100 records..

Xcode : 7.3 / Swift

Please help me to solve my Problem..

**Comment by priore** [comment]
Hi,
SOAPEngine processes SOAP messages, JSON messages are processed only if they are contained in a SOAP message. SOAPEngine has no limitations on the number of data, processes them recursively, and the JSON messages using the native iOS parser, perhaps triggered the timeout on the request, try to increase requestTimeout value to 60.

**Comment by mrpkarthik** [comment]
Thanks Priore team..
**requestTimeout** is solved my issue.. but it almost takes about 5 minutes to populate 1000 records on table view.. 

Any idea to increase data processing speed ?

Thanks team..

**Comment by priore** [comment]
If returns the JSON data can't do anything, in this case SOAPEngine uses NSJSONSerialization for the parser.

You can try to enable gzip compression on the server that returns data, and you can use the delegate named **didBeforeSendingURLRequest** to enable data gzip reception, like this :
```objective-c
 [urlReq setValue:@"gzip" forHTTPHeaderField:@"Accept-Encoding"]
```
or you can customize the parsing using the delegate named **didBeforeParsingResponseString**.

**Comment by mrpkarthik** [comment]
Hi Priore Team,

      I tried but no changes in speed. Its too slow for loading 300 records

**Comment by priore** [comment]
you can send, by email, the response XML ?
