### ISSUE TITLE
Very slow when a lot of data!

### ISSUE THREAD

**Issue by AljosaH** [priore/SOAPEngine#125]
Hi. I like SOAPEngine, it's easy to work with, so I purchased a licence when I started working on a iOS app for my client.
Everything worked nicely when data I received from server was small, but when I got more data, thing slowed down A LOT!
If I try to receive around 200KB of data, the SOAPEngine takes around 15 MINUTES to process it and respond with callback! Server itself responds in about 2 seconds (tested with PHP script) so this is not a server side problem.

This is how I configured soap:
```
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true   // (tried with false, but nothing changed)
        soap.version = SOAPVersion.VERSION_1_1
        soap.responseHeader = false

```
This is how I make soap call:
```
        soap.requestURL(Const.Url.SoapUrl,
            soapAction: "getCallList",
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                
                let result:Dictionary = dict as Dictionary
                // send notification
                let nc = NSNotificationCenter.defaultCenter()
                nc.postNotificationName(Notification.GetAccountInfoSucces, object: nil, userInfo: ["result" : result])
                
        }) { (error : NSError!) -> Void in           
            // send notification
            let nc = NSNotificationCenter.defaultCenter()
            nc.postNotificationName(Notification.GetAccountInfoError, object: nil)
        }

```
Is there something wrong with my setup? What can I do to speed up the processing?
Thanks for your help.

**Comment by AljosaH** [comment]
Just a note: I've tested in simulator and on a device, but the results are the same.

**Comment by priore** [comment]
You can try to enable gzip compression on the server that returns data, and you can use the delegate named _didBeforeSendingURLRequest_ to enable data gzip reception, like this :

` [urlReq setValue:@"gzip" forHTTPHeaderField:@"Accept-Encoding"]`

and you can customize the parsing using the delegate named _didBeforeParsingResponseString_, we recommend using TBXML being the fastest, will also use us in the next new version 2.0.

**Comment by AljosaH** [comment]
Thank you for prompt response.
Some new things I discovered and some points I haven't made before:
1. I have no control over server and data
2. I can request data as XML or as JSON
3. When I get XML data from server, your SOAP engine works very fast (data is received and processed in about 3-4 seconds)
4. BUT server returns damaged XML data which I can't use, so all I can work with is JSON format for data
5. When data comes in as JSON, your engine is REALLY slow

What do you recommend I do to speed up the precessing?
I've created the delegate _didBeforeParsingResponseString_. In this method I can intercept the response stringXML. Should I try to parse out the JSON and use some 3rd party library to process it? In that case, do you have any recommendations for fast library?
Thank you for your help.

**Comment by priore** [comment]
Hello,
The SOAPEngine can parse only XML SOAP response type, not able to parse JSON response, if you need parse JSON response you can use the AFNetworkig, or if your Service return Xml SOAP message, you can decrease time to parsing using the delegates and TBXML, can find this library in GitHub.

Thanks
Danilo Priore

Inviato da iPad

**Comment by AljosaH** [comment]
Thank you for clearing that up.
Funny thing is, JSON data DOES get parsed (after long time of processing) and the result is correctly formed dictionary.
I'll try working with delegates, thank you for your reply, it was very helpful.
