### ISSUE TITLE
Swift 3.0 issue

### ISSUE THREAD

**Issue by Pacaman13** [priore/SOAPEngine#126]
I've  just downloaded Xcode 8 and tried to convert my code in Swift 3.0 syntax... The method soap.requestURL(... does not work anymore. 

error: Cannot call value of non-function type 'URL!'

I think you have to update the pod to handle this new syntax, but I can be wrong

If you could help me...

Regards

**Comment by priore** [comment]
for Swift 3 we need to do an update, please give us few days

**Comment by priore** [comment]
please take the last commit 08e5e34c3e7735b3610d0572c16769d5df56be75

**Comment by Pacaman13** [comment]
Thank you very much 

Regards

Julien Lescoulié

**Comment by JoshHrach** [comment]
I'm running 1.29 and seeing this.

**Comment by priore** [comment]
please, you can include what you see ?

**Comment by JoshHrach** [comment]
Sure.

This is basically what I have:


```
// let MyService.URL: String
// let MyService.Action: String
let soapEngine = SoapEngine()
soapEngine.requestURL(MyService.URL, soapAction: MyService.Action, 
completeWithDictionary: { (statusCode: Int, dict: [AnyHashable: Any]!) -> Void in
// completion handler 
}) { (error: NSError!) -> Void in
// error handler
}
```

Error is like above: Cannot call value of non-function type 'URL!'

This worked before in Swift 2, and while dict is now [AnyHashable: Any] (probably because of the migrator), changing it back to [NSObject: AnyObject] like the Swift example in the ReadMe doesn't change anything.

**Comment by priore** [comment]
we have tried with the follow code and it work fine :

```swift
        soap.setValue("Genesis", forKey: "BookName")
        soap.setIntegerValue(1, forKey: "chapter")
        soap.requestURL("http://www.prioregroup.com/services/americanbible.asmx",
            soapAction: "http://www.prioregroup.com/GetVerses",
            completeWithDictionary: { (statusCode : Int, dict : [AnyHashable : Any]?) -> Void in
                
                var book:Dictionary = dict! as Dictionary
                let verses:NSArray = book["BibleBookChapterVerse"] as! NSArray
                self.verses = verses
                self.table.reloadData()
                
            }) { (error : Error?) -> Void in
                
                print(error);
        }
```

please verify the version of SOAPEngine framework, you can read from head of .h file.

**Comment by JoshHrach** [comment]
The version we're using, according to SOAPEngine.h, is 1.29. 

The issue appeared to be my use of a ! instead of a ? after the dict declaration. But the error didn't help me with that AT ALL. Thanks, Xcode...

It's building for me now. I had to change how I'm working with dict because of the new declaration, but I copied what you used in the above example and I don't have any big issues thus far.

Thanks for your help!

**Comment by PawelDecowski** [comment]
I’m getting the same error when trying to wrap `requestURL` in my own function:

```swift
private func makeRequest(endpoint: String, action: String, 
 complete:SOAPEngineCompleteBlockWithDictionary, fail: SOAPEngineFailBlock) {
    let soap = SOAPEngine()
        
    let url = baseUrl + "/" + endpoint + ".asmx"
        
    soap.requestURL(url, soapAction: action, completeWithDictionary: complete, failWithError: fail)
```

How can I pass the completion and fail handlers from my function to `requestURL`?

Thanks!

**Comment by PawelDecowski** [comment]
Figured it out.

The library is written in Objective-C but I’m using it in Swift, so I have to type the handlers as implicitly unwrapped optionals:

```swift
private func makeRequest(endpoint: String, action: String, 
 complete:SOAPEngineCompleteBlockWithDictionary!, fail: SOAPEngineFailBlock!) {
```

(Note the exclamation marks after handler types)

Why?

> because that's the closest Swift approximation of an object that's expected to be there but which can be nil

https://stackoverflow.com/questions/24223120/in-swift-what-does-the-symbol-mean-in-a-function-signature

**Comment by priore** [comment]
Hello,
for now try to use this:

```swift
    func myFunc(_ action: String!, complete: SOAPEngineCompleteBlockWithDictionary?, fail: SOAPEngineFailBlock?) {
        
        let soap = SOAPEngine()
        soap.requestURL("http://myurl...",
                        soapAction: action,
                        completeWithDictionary: { (statusCode: Int?, dict: [AnyHashable: Any]?) -> Void in
                            complete?(statusCode ?? 0, dict)
        }) { (error: Error?) -> Void in
            fail?(error)
        }
    }
```

please, next time open a new issue, so we can keep track of every single fix we have to do.
many thanks
