### ISSUE TITLE
What is the User Object "myObject"?

### ISSUE THREAD

**Issue by swl367** [priore/SOAPEngine#128]
In the samples, it looks like the value being passed "myObject" is some custom object. I looked at the sample xcode project and can't figure out how/why you're using it?

**Comment by priore** [comment]
It is a simple example of how you can also use a user object model (derived from NSObject or another user object) to pass parameters instead of a NSDictionary or NSArray, SOAPEngine retrieves values, and names of the properties of object for converting into XML SOAP message.
