### ISSUE TITLE
SOAP.requestURL not working properly in swift 3

### ISSUE THREAD

**Issue by talhaqamar** [priore/SOAPEngine#129]
Hi,
That's the sample code i am using but its not working properly 
![screen shot 2016-10-01 at 6 00 44 pm](https://cloud.githubusercontent.com/assets/2019864/19012728/0d08f89e-8801-11e6-9d4a-545d8d5baa80.png)

let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.version = SOAPVersion.VERSION_1_1
        soap.responseHeader = true // use only for non standard MS-SOAP service

        soap.setValue("param-value", forKey: "param-name")
        soap.requestURL("http://www.my-web.com/my-service.asmx",
            soapAction: "http://www.my-web.com/My-Method-name",
            completeWithDictionary: { (statusCode : Int, 
                                 dict : [NSObject : AnyObject]!) -> Void in

                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)

            }) { (error : NSError!) -> Void in

                NSLog("%@", error)
        }

I believe soap.requesturl parameters have changed in swift 3.It was working well in swift 2.Any help would be highly appreciated.Thanks

**Comment by priore** [comment]
duplicate #126
