### ISSUE TITLE
Not able to manage order.

### ISSUE THREAD

**Issue by anandmahajan** [priore/SOAPEngine#130]
Hi,
Not able to manage order.
```xml
<Room>
     <Adults>1</Adults>
     <Child Age="10" />
     <Child Age="10" />
     <Child Age="10" />
     <Child Age="1" />
     <Child Age="1" />
 </Room>
```

I want to put <Adults>1</Adults> as first element, but When I add `<Child>` tag...`<Adult>` tag position will changed

**Comment by priore** [comment]
please read #77

**Comment by anandmahajan** [comment]
@priore thanks..you can close ticket
