### ISSUE TITLE
requestURL function call gives "Cannot call value of non-function type 'URL!'" error.

### ISSUE THREAD

**Issue by szemih** [priore/SOAPEngine#131]
Hi,
I am new to GitHub. I hope it is the right place to ask a question. 
I am trying to make a SOAP request with Swift 3 using your swift example code. However, I could not manage to build it yet. Following code gives the build error which I have mentioned in the title. 
```swift
       soap.requestURL("http://www.prioregroup.com/services/americanbible.asmx",
                        soapAction: "http://www.prioregroup.com/GetVerses",
                        completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                            
                            var book:Dictionary = dict as Dictionary
                            let verses:NSArray = book["BibleBookChapterVerse"] as! NSArray
                            self.verses = verses
                            self.table.reloadData()
                            
        }) { (error : NSError!) -> Void in
            
            NSLog("%@", error)
        }
```
--------------------
Builed Error: `Cannot call value of non-function type 'URL!'`

**Comment by priore** [comment]
please read #126

**Comment by szemih** [comment]
Thank you for the quick response. It solves the issue. I am sorry. I should have checked first closed issues.
On the other hand, It is better to update the Swift example.
