### ISSUE TITLE
Is there a way to remove the SOAPAction from the http Headers?

### ISSUE THREAD

**Issue by jlubeck** [priore/SOAPEngine#133]
Hi, it looks like my server is not liking the SOAPAction in the http Headers. 
And I have no control over the server. If I duplicate the request on another app (POSTMAN), and I remove that single Header, it works fine. 
So, how can I remove it from there? I want to buy a license, but I can´t even make it work because of this issue...

Thanks!

**Comment by priore** [comment]
Hello,
first try to change the value of property named __actionQuotes__ to YES.
If in this first case it not works, you can use the delegate named __didBeforeSendingURLRequest__ to change the header of the request, and remove the SOAPAction key.

Bye.

**Comment by jlubeck** [comment]
actionQuotes to YES didn´t work either. 
I was able to get it working with the delegate.

Thanks!
