### ISSUE TITLE
How to setValue with GUID

### ISSUE THREAD

**Issue by AmeliaBoli** [priore/SOAPEngine#135]
I am attempting to make a request where a GUID is the only parameter. When I use `setValue` with the GUID as a string, the service takes a little over two minutes and then comes back with a status code of 200 and an empty dictionary. If I put single quotes or escaped quotes around the GUID within the string I quickly receive an error back from the server saying that it was expecting a GUID.

Can you please help me figure out how to configure the request?

Here is the request from SOAP UI:

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetThumbnailForImageId>
         <!--Optional:-->
         <tem:imageId>3556cbba-b0a9-4c27-a167-18dedbfbdc75</tem:imageId>
      </tem:GetThumbnailForImageId>
   </soapenv:Body>
</soapenv:Envelope>
```

Here is my `setValue`:

``` swift
soapEngine.setValue("3556cbba-b0a9-4c27-a167-18dedbfbdc75", forKey: "tem:imageId")
```

Here is the definition of the SoapEngine instance. Other standard pieces are defined elsewhere that are used throughout the app.

```swift
soapEngine.envelope = "xmlns:soapenv=http://schemas.xmlsoap.org/soap/envelope/ xmlns:tem=http://tempuri.org/"

soapEngine.clearValues()
soapEngine.defaultTagName = nil
soapEngine.actionNamespaceSlash = false

soapEngine.setValue("3556cbba-b0a9-4c27-a167-18dedbfbdc75", forKey: "tem:imageId")
```

And then I am using the asmxURL requestURL.

```swift
// webservice request with block and dictionary
    open func requestURL(_ asmxURL: Any!, soapAction: String!, completeWithDictionary complete: SOAPEngine64.SOAPEngineCompleteBlockWithDictionary!, failWithError fail: SOAPEngine64.SOAPEngineFailBlock!)
```

All help will be greatly appreciated. Thank you in advance.

**Comment by priore** [comment]
Hi Amelia,
try to set property named **responseHeader** to YES.

(note: the response time depended on the image size).

thanks

**Comment by AmeliaBoli** [comment]
Thank you Priore.

Setting responseHeader to YES solved the problem. Can you please explain why this worked?

(FYI actionNamespaceSlash did need to be set to true, but this alone did not resolve the issue.)

Thank you again for your time.

Amelia

**Comment by priore** [comment]
Many services that are not found on MS servers don't return SOAP messages with the structure provided by MS, the SOAPEngine for default retrieve only the data in the SOAP message body that have a standard MS structure, with responseHeader set to YES, SOAPEngine takes all the data starting from the SOAP header.

Thanks
