### ISSUE TITLE
Purchased version still showing trial error message on device

### ISSUE THREAD

**Issue by talhaqamar** [priore/SOAPEngine#136]
Hi, 
I have purchased the SOAP Engine for my ios app.
Its working fine but when deploying on phone it shows the trial version error even though its purchased version.

Can you tell me how to integrate the license key in the iphone app.Thanks

Regards,
Talha Qamar

![screen shot 2016-10-10 at 5 13 54 pm](https://cloud.githubusercontent.com/assets/2019864/19228054/f51b5d5e-8f0c-11e6-8255-f509e19d0597.png)

**Comment by priore** [comment]
please, read this #19

**Comment by talhaqamar** [comment]
how to add the license key into the project ?
Thanks

**Comment by priore** [comment]
you need to set the property named **licenseKey**

**Comment by talhaqamar** [comment]
It works :) Cheers

**Comment by talhaqamar** [comment]
can you show me how exactly to add it ?
![screen shot 2016-10-13 at 12 37 58 pm](https://cloud.githubusercontent.com/assets/2019864/19333490/ff055914-9141-11e6-93e9-0494e7414024.png)
