### ISSUE TITLE
OSX Enum Unresolved Swift 3

### ISSUE THREAD

**Issue by markmunoz** [priore/SOAPEngine#137]
I have created a new blank project added OSXFramework as well as the header search path and linker flag.  This is a pure Swift 3 project so I import SOAPEngineOSX and it builds fine.  I can add a SOAPEngine object just fine.  However when I go to use any of the enums defined in this framework such a VERSION_1_1 or any of the AUTH ones I get Unresolved identifier.  The funny thing is I right click on the enum and do Jump to Definition it takes me to the header file in the framework with the definition of that enum.  

I have tried adding a bridging header file similar to the swift example but that doesn't work either.  Any ideas?

**Comment by priore** [comment]
seems that Swift 3 rename the enum values (???)

```swift
soap.authorizationMethod = SOAPAuthorization.AUTH_BASICAUTH
```

**Comment by markmunoz** [comment]
Yeah that seems to work for me too, thanks for the help!
