### ISSUE TITLE
licenseKey doesn't work

### ISSUE THREAD

**Issue by Skelzor** [priore/SOAPEngine#138]
Hello,

I am not sure if the problem is on my side or a framework issue.

We bought a license key and I add it for both instances: the shared instance and any instance I made of the soap engine by myself, but the overlay doesn't go away.

We have a correct bundle identifier: de.organizationname.app-name (is a german app).

Does I not recognize a special way to add the license key? e.g. a special initializer?

Thank you very much!

**Comment by priore** [comment]
you can attach the initialization code that you use?

**Comment by Skelzor** [comment]
`		SOAPEngine.sharedInstance().licenseKey = "C8v2TeGd********0NS72Q=="
        let soap = SOAPEngine()
		soap.licenseKey = "C8v2TeGd********0NS72Q=="
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.version = .VERSION_1_1`

**Comment by priore** [comment]
first; if you create a instance of SOAPEngine and use it, you don't need set the licenseKey for sharedInstance.
second; please check your bundle and license key that you copied from email, maybe not is equal or an incorrect copy with invisible and invalid chars (cr or line feed), we have tested the your bundle and licenseKey and work correctly.

**Comment by Skelzor** [comment]
Thank you very much - I wrote a mail to your support, because we have a little problem getting the mail with the license key. Nice framework by the way - it safes me a lot of time!
