### ISSUE TITLE
Schedule connection on WIFI

### ISSUE THREAD

**Issue by AmeliaBoli** [priore/SOAPEngine#139]
Is there a way to create a `requestURL` that will only execute if the user is on WIFI? And if they are not, schedule it for later?

Thanks.

**Comment by priore** [comment]
try using [reachability](https://developer.apple.com/library/content/samplecode/Reachability/Introduction/Intro.html) or [AFNetworking](https://github.com/AFNetworking/AFNetworking#network-reachability-manager)
