### ISSUE TITLE
Escaped special characters in xml issue

### ISSUE THREAD

**Issue by mario-epsilon** [priore/SOAPEngine#140]
We are using version 1.21.1 (even though we tested with other versions with same outcome), our server dev verifies that they escape special characters properly, but when we receive the xml string in:

`- (NSString*)soapEngine:(SOAPEngine*)soapEngine didBeforeParsingResponseString:(NSString*)stringXML`

`stringXML` does not contain the escape characters, and this causes a "parser error : Opening and ending tag mismatch".  Example: We are getting `<parameter>` instead of `&lt;parameter&gt;`

**Comment by priore** [comment]
for XML standard the `<` and `>` characters are special characters, if a value of a key contains these characters must be returned by your server as Unicode characters (`\U+003C` and `\U+003E`) and not HTML (`&lt` or `&gt`) or char (`<>`), perhaps can also try to return to the values `&#60` and `&#62`.

**Comment by mario-epsilon** [comment]
Thank you for your reply. Our server is using .Net and supplying other clients other than our iOS app. Therefore, server is not willing to change their format of xml. Is there anything from iOS side that we can do to handle this?

**Comment by priore** [comment]
please, download the last version and use the delegate named didBeforeParsingResponseData instead of didBeforeParsingResponseString.

thanks for your patience.

**Comment by mario-epsilon** [comment]
Thank you, this solved the problem.
