### ISSUE TITLE
How can I get the values stored in the SOAPEngine? 

### ISSUE THREAD

**Issue by jlubeck** [priore/SOAPEngine#141]
I see there are setValue methods, and clearValues method, but I couldn't find any getValues methods. 

Thanks

**Comment by priore** [comment]
Hi,
when you receiving the response from the service, these are in a NSDictionary, you can use the valueForKey or valueForKeyPath of NSDictionary.

**Comment by jlubeck** [comment]
Right, but what if I don't get the response from the service? I'm creating logs for my app, and the place to put this log would be BEFORE calling the service, not after...
Thanks!

**Comment by priore** [comment]
you can use the delegate named `didBeforeSendingURLRequest` for retrieve the xml requests from `httpBody` property of `request` object.

**Comment by jlubeck** [comment]
That was it. Closing this. Thanks!
