### ISSUE TITLE
Set URL in first tag after Body

### ISSUE THREAD

**Issue by AmeliaBoli** [priore/SOAPEngine#143]
How do I set the url for the first tag after the Body in my request?

For example, right now I am setting soapAction to `http://tempuri.org/METHOD_NAME` in `requestURL`.

However, my request looks like this:

...`<soap:Body><METHOD_NAME xmlns="http:/">`...

Other requests that I make to other urls and soapActions have the url inserted. How can I make this happen here?

Thank you in advance.

**Comment by priore** [comment]
you do not need to set the namespace attribute for "METHOD_NAME" because this set automatically

**Comment by AmeliaBoli** [comment]
I am not setting the namespace. I am only setting the soapAction.

**Comment by priore** [comment]
Yes, when you passing the soapAction value (http://tempuri.com/METHOD_NAME) the name space (xmlns) be set automatically (for this case at http://tempuri.com). If you receive an error for this namespace, try to change the value for the property named actionNamespaceSlash.

**Comment by AmeliaBoli** [comment]
Maybe I didn't make my question clear. Here is the request printed before it is sent:

`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/"><soap:Header></soap:Header><soap:Body><GetLocations3 xmlns="http:/"><tem:pageSize>6</tem:pageSize><tem:maxRows>18</tem:maxRows><tem:latitude>33.4</tem:latitude><tem:longitude>-112.4</tem:longitude><tem:maxDistance>700</tem:maxDistance><tem:availableServices><tem:int>1</tem:int></tem:availableServices></GetLocations3></soap:Body></soap:Envelope>`

Why is there no complete URL after GetLocations3? In all of my other SOAP requests, the entire URL is listed, not just `"http:/"`?

Also, I tried `actionNamespaceSlash` before originally posting and it did not make a difference.

**Comment by priore** [comment]
you can paste the your code of SOAPEngine ?

**Comment by AmeliaBoli** [comment]
Thank you for looking. I redacted our url.

```
let soapEngine = SOAPEngine()
soapEngine.delegate = self
soapEngine.userAgent = "SOAPEngine"
soapEngine.version = SOAPVersion.VERSION_WCF_1_1
soapEngine.licenseKey = SOAP_KEY

soapEngine.envelope = "xmlns:tem=\"http://tempuri.org/\""

soapEngine.clearValues()
soapEngine.defaultTagName = nil
soapEngine.actionNamespaceSlash = true
soapEngine.responseHeader = true

soapEngine.setIntegerValue(6, forKey: "tem:pageSize")
soapEngine.setIntegerValue(18, forKey: "tem:maxRows")
soapEngine.setDoubleValue(33.4, forKey: "tem:latitude")
soapEngine.setDoubleValue(-112.4, forKey: "tem:longitude")
soapEngine.setDoubleValue(700, forKey: "tem:maxDistance")
soapEngine.setValue([1], forKey: "tem:availableServices", subKeyName: "tem:int")

soapEngine.requestURL("http://COMPANY_SITE/service.asmx", soapAction: "http://tempuri.org/GetLocations3", completeWithDictionary: { (statusCode: Int, dict: [AnyHashable: Any]?) -> Void in
}
```

**Comment by priore** [comment]
Hi,
use `soapEngine.version = SOAPVersion.VERSION_1_1`, the `VERSION_WCF_1_1` is for `.svc` services.

**Comment by AmeliaBoli** [comment]
Thank you. That solved the problem.
