### ISSUE TITLE
How do I remove xmlns:xsd and xmlns:xsi tags?

### ISSUE THREAD

**Issue by manjunathgudisi** [priore/SOAPEngine#146]
Hi - 

My service is expecting below XML as input payload ...

```xml
<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:com="com.myproj">
	<soapenv:Header/>
	<soapenv:Body>
		<com:GetCurrentDate/>
	</soapenv:Body>
</soapenv:Envelope>
```

Here is the code I have written...

```swift
        let soap = SOAPEngine()
    
        // authorization
        soap.authorizationMethod = SOAPAuthorization.AUTH_BASIC //basic auth
        soap.username = "####";
        soap.password = "####";
        
        soap.userAgent = "SOAPEngine"
        soap.version = SOAPVersion.VERSION_1_1
        soap.xsdDataTypes = false
        soap.soapNamespace = "soapenv"
        soap.envelope = "xmlns:com=\"com.myproj\""

        soap.requestWSDL(servicewsdl,
                        operation: "com:GetCurrentDate",
                        completeWithDictionary: {
                            (statusCode : Int, dict : [AnyHashable : Any]?) -> Void in
                            success(dict)
                        }) { (error : Error?) -> Void in
                            failure(error!)
                        }
```

When I debug my service, I see that it is receding below XML as input payload...

```xml
<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:com="com.myproj">
	<soapenv:Header/>
	<soapenv:Body>
		<com:GetCurrentDate/>
	</soapenv:Body>
</soapenv:Envelope>
```

Because of this, Im getting "The given SOAPAction com:GetCurrentDate does not match an operation" error.

How do I remove **xmlns:xsi** and **xmlns:xsd** tags from input payload?

Thanks, Manju

**Comment by priore** [comment]
the xsi and xsd attributes is a standard for a soap message, but if you need to remove this you need use the didBeforeSendingURLRequest delegate, in the demo included in the zip, you can see an example for modify the request before sending this request.

**Comment by priore** [comment]
This service is a not standard MS service, the SOAPAction key inside the header of request is a standard for MS services, but you can modify the request usando il delegato didBeforeSendingURLRequest and then modify the value for SOAPAction (setValue:forHTTPHeaderField of the request object).
