### ISSUE TITLE
Can I use SOAPEngine library if my services are with SOAPAction is empty?

### ISSUE THREAD

**Issue by manjunathgudisi** [priore/SOAPEngine#147]
Hi - Please have a look at the attached image. For given service "GetCurrentDate", there is no SOAPAction. it is empty. In this case, shall I use SOAPEngline library or not.

If I can use, how do I use it. Please help me.

<img width="398" alt="screen shot 2017-01-05 at 5 32 44 pm" src="https://cloud.githubusercontent.com/assets/6059076/21680013/095cc812-d36d-11e6-9232-7d0ef77c9196.png">

**Comment by priore** [comment]
This service is a not standard MS service, the SOAPAction key inside the header of request is a standard for MS services, but you can modify the request usando il delegato didBeforeSendingURLRequest and then modify the value for SOAPAction (setValue:forHTTPHeaderField of the request object).
