### ISSUE TITLE
How to pass HTTP header(authentication parameters in header) in SOAPEngine?

### ISSUE THREAD

**Issue by dumpzealousys** [priore/SOAPEngine#148]
How to pass HTTP header(authentication parameters in header) in SOAPEngine?

We have tried with
**soap.header** property

But we don't know in which format we need to pass username and password in header?

Can you share some example request with header so we can understand?

We have tried with NSURLSession like
        request.addValue("xyz", forHTTPHeaderField: "Username")
        request.addValue("abc", forHTTPHeaderField: "Password")

Can you give some alternate way to send parameter in HTTPHeader?

**Comment by priore** [comment]
If you want to set the username and password in the message header of soap, you need to set the property named `autorizationMethod = SOAP_AUTH_BASIC`, and the properties named `username` and `password`.

If you want to set the username and password in the header of request, you need to use the delegate named `didBeforeSendingURLRequest`.

What kind of Authorization uses the your service?

**Comment by dumpzealousys** [comment]
We don't want to send **soap.username** and **soap.password**. 
We want to send like **token** in header part.

**Comment by priore** [comment]
setValue is the correct way, you can verify the xml sent through the delegate said above with reading the httpBody property of the request (NSData) converted it to string.
