### ISSUE TITLE
Raw xml from SOAPEngine

### ISSUE THREAD

**Issue by Sapanesh** [priore/SOAPEngine#150]
Hi,
How we can get Raw xml from SOAPEngine object.

for example : 

 NSMutableDictionary *book = [NSMutableDictionary dictionaryWithObject:@"Genesis" forKey:@"name"];
    // chapter
    NSDictionary *attr = @{@"order": @"asc"};
    NSDictionary *child = [soap dictionaryForKey:@"chapter" value:@"1" attributes:attr];
    [book addEntriesFromDictionary:child]; // add chapter to book
    // book attributes
    [soap setValue:book forKey:@"Book" attributes:@{@"rack": @"2"}];

I need its xml.

Thanks

**Comment by priore** [comment]
Hi
you can use the delegates for get a NSData (raw xml) before posting and after response from the server

**Comment by Sapanesh** [comment]
I need without async ...using async i already achieved it

**Comment by priore** [comment]
for sync methods no way to retrieve the raw data, you can only retrieve a more complete dictionary by setting the property `responseHeader`.

**Comment by Sapanesh** [comment]
I need request xml with sync, not response xml? Is not possible ?

**Comment by priore** [comment]
the sync supports only NSDictionary, already parsed xml, raw data not available, sorry.

**Comment by priore** [comment]
the sync supports only NSDictionary, already parsed xml, raw data not available, sorry, but you can create a custom class for synchronize the delegates.

**Comment by priore** [comment]
This is just an example :

```objc
// SOAPSync.h
@interface SOAPSync : NSObject

@property (nonatomic, strong) NSError *lastError;
@property (nonatomic, strong) NSData *responseData;

- (void)setValue:(id)value forKey:(NSString *)key;
- (void)requestURL:(id)asmxURL soapAction:(NSString*)soapAction;

@end
```


```objc
// SOAPSync.m
#import "SOAPSync.h"
#import <SOAPEngine64/SOAPEngine.h>

@interface SOAPSync() <SOAPEngineDelegate>
{
    SOAPEngine *soap;
    dispatch_semaphore_t sema;
}

@end

@implementation SOAPSync

- (instancetype)init
{
    if (self = [super init]) {
        
        soap = [[SOAPEngine alloc] init];
        soap.delegate = self;
    }
    
    return self;
}

- (void)dealloc
{
    soap = nil;
}

- (void)setValue:(id)value forKey:(NSString *)key
{
    [soap setValue:value forKey:key];
}

- (void)requestURL:(id)asmxURL soapAction:(NSString*)soapAction
{
    sema = dispatch_semaphore_create(0);
    [soap requestURL:asmxURL soapAction:soapAction];
    
    while (dispatch_semaphore_wait(sema, DISPATCH_TIME_NOW))
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode
                                 beforeDate:[NSDate dateWithTimeIntervalSinceNow:0.1]];
}

#pragma mark - SOAPEngine Delegates

- (NSData *)soapEngine:(SOAPEngine *)soapEngine didBeforeParsingResponseData:(NSData *)data
{
    _lastError = nil;
    _responseData = data;
    
    dispatch_semaphore_signal(sema);
    
    return nil; // no continue
}

- (void)soapEngine:(SOAPEngine *)soapEngine didFailWithError:(NSError *)error
{
    _lastError = error;
    _responseData = nil;

    dispatch_semaphore_signal(sema);
}

```

**Comment by Sapanesh** [comment]
Thanks a lot !!
