### ISSUE TITLE
How to send more value in header ?

### ISSUE THREAD

**Issue by Sapanesh** [priore/SOAPEngine#153]
Hi,

I want to send more values in headers...like app_locale etc. You guys given option for  User-Agent ..but what about other values.?

{
    Accept = "text/xml; charset=utf-8";
    "Content-Length" = 2605;
    "Content-Type" = "text/xml; charset=utf-8";
    SOAPAction = "\"LowFareSearchReq\"";
    "User-Agent" = SOAPEngine;
}
Please suggest

Thanks,
Sapnesh Mahajan

**Comment by priore** [comment]
please, read #85
