### ISSUE TITLE
How to send gzip request ?

### ISSUE THREAD

**Issue by Sapanesh** [priore/SOAPEngine#154]
Hi,
We are sending api call using soap request...but we need to send request in gzip format.
How we can achieve ?

Thanks

**Comment by priore** [comment]
please, read this https://github.com/priore/SOAPEngine/issues/125#issuecomment-242913805

**Comment by Sapanesh** [comment]
Ok thanks I will check with
[urlReq setValue:@"gzip" forHTTPHeaderField:@"Accept-Encoding"]

Thanks
