### ISSUE TITLE
SOAPEngine Server response: Unexpected wrapper element 

### ISSUE THREAD

**Issue by gank0326** [priore/SOAPEngine#155]
I use safari can't open http://www.nj12320.org/12320zsk-server/services/commonService?WSDL
Then I use the ios call error SOAPEngine Server response: Unexpected wrapper element getKnowledgeBaseType found. The Expected getKnowledgeBaseType {http://service.cxf.zskserver.just.com/}.

**Comment by priore** [comment]
Hi,
we read the WSDL correctly:

http://www.nj12320.org/12320zsk-server/services/commonService?WSDL for methods of service.
http://www.nj12320.org/12320zsk-server/services/commonService?wsdl=CommonService.wsdl for the params of methods.

getKnowledgeBaseType need a param named arg0, like this:

```objectivec
    [soap setValue:@"0" forKey:@"arg0"];
    [soap requestURL:@"http://www.nj12320.org/12320zsk-server/services/commonService"
          soapAction:@"getKnowledgeBaseType" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        NSLog(@"%@", dict);
    } failWithError:^(NSError *error) {
        NSLog(@"%@", error);
    }];
```

this return a message: "header request", but not clear what need.

**Comment by khaskheli24** [comment]
soap.requestURL("http://124.29.233.4/wspi/wsNxtDeg_PI.asmx",
                        soapAction: "http://124.29.233.4/wspi/post",
                        completeWithDictionary: { (statusCode : Int,
                            dict : [AnyHashable : Any]?) -> Void in
                            
                            var result:Dictionary = dict! as Dictionary
                            print(result)
                            
        }) { (error : Error?) -> Void in
            
            print(error)
        }



this is response i got please help

[AnyHashable("Body"): {
    Fault =     {
        detail = "";
        faultcode = "soap:Client";
        faultstring = "Server did not recognize the value of HTTP Header SOAPAction: http://124.29.233.4/wspi/post.";
    };
}]

**Comment by priore** [comment]
Hi,
reading the WSDL, looking for the soapAction attribute, maybe you need to sets the _soapAction_ parameter at http://tempuri.org/Authentication.

sorry for elapsed time.
