### ISSUE TITLE
Request Keep-Alive Problem.

### ISSUE THREAD

**Issue by Sapanesh** [priore/SOAPEngine#156]
Hi,
we are using one third party gateway..they complain to us..request which you are sending all always Keep Alive.

What they said "Keep Alive - Keep Alive is activated for all the requests. We do not recommend Keep Alive to be activated for any transaction."

What we will do...my all apis goes through SOAPEngine...I already checked there is so such header Keep-Alive.

Thanks,
Sapanesh

**Comment by priore** [comment]
Hello,
you can use the didBeforeSendingURLRequest delegate to add or remove keys on headers of requests.

**Comment by Sapanesh** [comment]
Hi,
Thanks for responding.
But in our header there is no such key called keep-alive

{
    Accept = "text/xml; charset=utf-8";
    Authorization = "Basic VW5pdmVyc2FsIEFQSS91QVBJODEwMDg0MzUyMy0zZmRhMTExNzp3Rys1LWczUEgl";
    "Content-Length" = 2315;
    "Content-Type" = "text/xml; charset=utf-8";
    SOAPAction = "\"LowFareSearchReq\"";
    "User-Agent" = SOAPEngine;
}


Thanks,
Sapanesh

**Comment by priore** [comment]
```objective-c
- (NSMutableURLRequest *)soapEngine:(SOAPEngine *)soapEngine didBeforeSendingURLRequest:(NSMutableURLRequest *)request
{
    [request setValue:@"keep-alive" forHTTPHeaderField:@"Connection"];
    return request;
}

```

**Comment by Sapanesh** [comment]
@priore 
What they said "Keep Alive - Keep Alive is activated for all the requests. We do not recommend Keep Alive to be activated for any transaction."

Issue is that.

**Comment by priore** [comment]
SOAPEngine is limited by HTTP binding (basicHttpBinding) itself can’t provide two-phase commit across distributed transactional resources. Internet apps generally don’t need this level of transactional reliability, enterprise apps sometimes do, but for this using others types of binding  (wssHttpBiding) but that not supported on SOPEngine https://github.com/priore/SOAPEngine#limitations.

**Comment by Sapanesh** [comment]
@priore 

I think you didin't understand my concern.

By SOAPEngine "Connection: 	keep-alive" added automatically.
See request...I checked with "Charles Web Debugging Proxy"
 
Connection: 	keep-alive
Content-Length: 	647
Content-Type: 	text/xml; charset=utf-8
Content-Encoding: 	gzip



Any chance you create one property to disable it. Actually we are stuck ...our 3rd party not accepting request with "Connection: 	keep-alive" 


Please suggest

**Comment by priore** [comment]
Sorry, but I continue not understand.
The SOAPEngine add only following keys on header of request :

```
Content-Type
SOAPAction
Content-Length
User-Agent
```

don't add other on the header.

But if you want to view or edit the SOAPEngine headers, you can use the delegate named `didBeforeSendingURLRequest`.
