### ISSUE TITLE
Set array of strings as value for request

### ISSUE THREAD

**Issue by havocked** [priore/SOAPEngine#157]
Hi ! 

I'm trying to send an array of strings for a soap request with this line in swift 3.0 (Xcode 8.3.1):

```
soap.setValue(["string1", "string2", "string3"], forKey: "Search")
```

I have an error that seems to come from SOAPEngine: 

```
{
  "Body" : {
    "Fault" : {
      "faultcode" : "SOAP-ENV:Client",
      "faultstring" : "Complex types are not parsed in this version."
    }
  }
}
```

Any thoughts on it ?

**Comment by priore** [comment]
Hi,
sorry but this is the service response is not an error generated from the library, you should see what parameters to pass to the service, you need watch the WSDL.

**Comment by havocked** [comment]
Hi, sorry, you are right. But i'm still having trouble to create the value for this :

```<Recherche xsi:type="def:ArrayOfstring" soapenc:arrayType="xsd:string[]"/>```

Any thoughts ? 

Thanks again for your work !

**Comment by priore** [comment]
Hi, try with this (objective-c sample):

```objective-c
    NSArray *array = @[@"value1", @"value2", @"value3"];
    NSDictionary *attr = @{@"xsi:type": @"def:ArrayOfstring", @"soap:arrayType": @"xsd:string[]"};
    [soap setValue:array forKey:@"param-name" subKeyName:@"item" attributes:attr];

```

**Comment by havocked** [comment]
Hello,

It seems to work !

Thanks again !

NB: By the way here is the same example in `Swift 3.0`:

```swift
let array = ["value1", "value2", "value3"]
var attr = [String: String]()
attr["xsi:type"] = "def:ArrayOfstring"
attr["soap:arrayType"] = "xsd:string[]"
soap.setValue(array, forKey: "param-name", subKeyName: "item", attributes: attr)
```
