### ISSUE TITLE
Questions about the library 

### ISSUE THREAD

**Issue by ced236** [priore/SOAPEngine#159]
Hello, 
I am interested by your library but I have a few questions. 
First, is it exist a detailed documentation ? 
Is the library support the xml signature by x509 certificate ?

Regards, 

Cédric

**Comment by priore** [comment]
Hello,
we are completing the detailed documentation on Wiki section of GitHub page, work in progress.

X509 is not currently supported, only DER, CER, and PKCS12 (p12) signatures are supported, we are developing a new version but I do not think the X509 will be supported.

You can implement header SOAP for any type of authentication, and you can alter the soap request, before sending, through delegates.

thanks for your interest
Support team

**Comment by ced236** [comment]
Thank you for your quick reply 

Cédric
