### ISSUE TITLE
BUG - didBeforeParsingResponseData vs requestURL

### ISSUE THREAD

**Issue by Sreekanth001** [priore/SOAPEngine#161]
Hi

Its a bug.

I dont see the repsonse, when I see the dictionary from below service success callback (2.png)

```swift
open func requestURL(_ asmxURL: Any!, soapAction: String!, completeWithDictionary complete: SOAPEngine64.SOAPEngineCompleteBlockWithDictionary!, failWithError fail: SOAPEngine64.SOAPEngineFailBlock!)
```

BUT I see the response in below callback function (1.png)

```swift
func soapEngine(_ soapEngine: SOAPEngine!, didBeforeParsingResponseData data: Data!) -> Data! { }
```

Can you look into this.

<img width="837" alt="1" src="https://cloud.githubusercontent.com/assets/25745802/26314498/c8711e7c-3f2b-11e7-8e6e-4f140681e3c5.png">
<img width="835" alt="2" src="https://cloud.githubusercontent.com/assets/25745802/26314497/c870b9dc-3f2b-11e7-9af4-b0ca3a2ccbf9.png">

**Comment by priore** [comment]
The NSData response is pure data (raw), while NSDictionary is the data parsed started from an specific xml tag, If you want all data become parsed, you neet to set the property named `responseHeader` to true.

**Comment by Sreekanth001** [comment]
Thanks for the immediately response ...Now it's working....
