### ISSUE TITLE
Brought license.. but still shows "This is a trial version .." popup

### ISSUE THREAD

**Issue by manjunathgudisi** [priore/SOAPEngine#162]
Hi

I brought license and used below code to include the license. Need help.

> soap.licenseKey = "eGjzigQ************"

BTW, I used cocoapod like below.

> target ‘MyTraget' do
>   use_frameworks!
>   pod 'SOAPEngine'
> end

![img_4042](https://cloud.githubusercontent.com/assets/6059076/26437899/6945c25e-413d-11e7-8b9b-684e3a4396a6.PNG)

**Comment by priore** [comment]
Hello,
you purchased a enterprise license, an enterprise license is generated through a part of the bundle that identifies the organization (eg com.organization), you can use that type of license for many apps that have the same initial bundle (e.g. com.organization.app1, com.organization.app2 etc.).

In your case, for the bundle you have written you will need to specify a bundle com.simplyfi.gsrtc.app1 or com.simplyfi.gsrtc.app2 (where app1 or app2 is the name of the app that identifies it and that you have chosen).

Usually for an app become used a bundle type com.simplyfi.myapp-name and for enterprise license a partial bundle type eg. com.simplyfi.

**Comment by manjunathgudisi** [comment]
I need to change my bundle from **com.simplyfi.gsrtc** to **com.simplyfi**, any possibility to do this?

**Comment by priore** [comment]
Hello,
we've reset your license code, now you can generate the new license.

Thanks
