### ISSUE TITLE
Use it with ShareExtension

### ISSUE THREAD

**Issue by bhushans** [priore/SOAPEngine#163]
Hi,

I currently use the SOAP Engine inside my App.
However, after create a share extension, we decided to create an embedded framework which we can use for both the App and the extension.
But the request currently only works for the App and not the extension.
Can somebody let me know on how can I make sure the Request go through for extension as well.
Currently, it doesnt throw any error

**Comment by priore** [comment]
Hi,
you can send us a small example of what you want to do ?

nota: you cannot add SOAPEngine to a framework, because this violates the EULA.

**Comment by bhushans** [comment]
So, I was able to resolve this issue correctly. I was trying to run SOAP Engine on a secondary thread and not on the main thread.
As for the EULA, can I just add it to the internal Framework. The framework is not going to be public. I am just creating a framework to share between App and Extension, so I dont have to write the same API calls for both of them
