### ISSUE TITLE
Out of memory (-[NSString(SOAPEngine) stringUnescaping])

### ISSUE THREAD

**Issue by vkostechko-timyo** [priore/SOAPEngine#165]
Hello, 
we're getting "out of memory" crash (Version : 1.31).
Please advice how to avoid it. 
<img width="1360" alt="fabric" src="https://user-images.githubusercontent.com/28860047/28611551-cab8177a-71f4-11e7-8eec-9dbc62ae8927.png">

Thanks in advance

**Comment by priore** [comment]
Hello,
sorry, but we need the specific case, code, parameters and url of the service, or the service response (soap-xml) for test it.

You can send it directly to the support email.
Thanks.

**Comment by priore** [comment]
To retrieve the xml you can use the delegate **didFinishLoadingWithDictionary** and convert the **NSData** parameter to an **NSString**.

**Comment by priore** [comment]
in the meantime, you can replace the internal parser by getting better performance with this trick https://github.com/priore/SOAPEngine/wiki/Improve-the-performance-of-the-XML-parser

**Comment by vkostechko-timyo** [comment]
Thank you for quick and professional help!
