### ISSUE TITLE
SOAP Engine is slow

### ISSUE THREAD

**Issue by esseziway** [priore/SOAPEngine#167]
Hi, 
I have a paid version of soap engine.

Right now my app have around 30 api calls.
But at the time of start it needs around 6-7 api calls.But the time it takes to call those api's and parse the data is too much around 15 seconds.

Do you guys recommend any way to make it work faster.Thanks

**Comment by priore** [comment]
please, read this [wiki](https://github.com/priore/SOAPEngine/wiki/Improve-the-performance-of-the-XML-parser).

thanks
