### ISSUE TITLE
64bit build & XML parser error

### ISSUE THREAD

**Issue by craxoor** [priore/SOAPEngine#17]
Hey (yes, me again) ;)

At first, thanks for your v1.9 update! This version should fix the memory leaks issue (#14). I have also bought a license of your framework! :)

But it seems that the last framework build for the 64 Bit architecture (SOAPEngine64.framework) was not really build for 64 bit. Since version v1.9 i get the following linker error while building my app for `arm64` architecture:

`ld: warning: ignoring file /Users/Me/Documents/Projects/SOAPEngine/SOAPEngine64.framework/SOAPEngine64, missing required architecture x86_64 in file /Users/Me/Documents/Projects/SOAPEngine/SOAPEngine64.framework/SOAPEngine64 (4 slices)`

And there is one more small issue since version 1.9:
I get a XML parser error (in the console window) after each response (but this doesn't affect the further execution of my app). Here is an example XML response:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <SOAP-ENV:Body>
      <ns1:iPadGetNewsResponse xmlns:ns1="urn:TransferCenteriPad">
         <Enc_return xsi:type="xsd:string">PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgcGxpc3QgUFVCTElDICItLy9BcHBsZS8vRFREIFBMSVNUIDEuMC8vRU4iICJodHRwOi8vd3d3LmFwcGxlLmNvbS9EVERzL1Byb3BlcnR5TGlzdC0xLjAuZHRkIj48cGxpc3QgdmVyc2lvbj0iMS4wIj48ZGljdD48a2V5Pkxhc3RVcGRhdGVkPC9rZXk+PHN0cmluZz4yMDE0LTExLTEwIDEzOjI1OjQ3PC9zdHJpbmc+PC9kaWN0PjwvcGxpc3Q+</Enc_return>
      </ns1:iPadGetNewsResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

```
:1: parser error : Start tag expected, '<' not found
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgcGxpc3QgUFVCTElD
^
```

But there seems no error in the responding XML :/

If I reset my local git branch of your framework to the version 1.8 i don't have those issues. Would you please have another look at it? Thanks! :)

Gregor

**Comment by esseziway** [comment]
Hi I am having same issue. 
I have a paid version of soap engine. I am using in ios so SOAPEngine64 is i am using with branch 1.40 from cocoapods

:1: parser error : Start tag expected, '<' not found
[{"id":"0","title":"Shift","start":"0001-01-01 00:00:00","end":"0001-01-01 00:00
^

Thanks

**Comment by priore** [comment]
hello @esseziway 

your service responding JSON format and not SOAP

```json
[{"id":"0","title":"Shift","start":"0001-01-01 00:00:00","end":"0001-01-01 00:00"}]
```

**Comment by esseziway** [comment]
Yes my end point responding with the json. But json is incomplete when i use soapui to test it work fine.

**Comment by priore** [comment]
@esseziway so, we can correctly extract the data of the json inserted in the soap, to test better we need a real test link of your service, however try to set the "responseHeader" property to true.
