### ISSUE TITLE
Concurrent URL requests

### ISSUE THREAD

**Issue by stephenmcbride** [priore/SOAPEngine#170]
Hi, quick question - does SOAP engine support concurrent requests? I'm coming across an issue where if I have two requests that are both fired at the same time, the block for the second request will be executed by the first request if the first request returns first.

**Comment by priore** [comment]
Hello,
you need to use two separately initialized objects, you use swift or objective-c? with delegates or blocks?

**Comment by stephenmcbride** [comment]
Thanks for replying, using two objects did the trick.
