### ISSUE TITLE
XML parse

### ISSUE THREAD

**Issue by elychahine** [priore/SOAPEngine#171]
i'm getting the below each time the xml contains char(11) 
xmlParseCharRef: invalid xmlChar value 11
New call from & # x B;

**Comment by priore** [comment]
The list of valid characters is in the [XML specification](http://www.w3.org/TR/xml/#charsets) and invalid characters listed below:

#x0 - #x8 (ASCII 0 - 8)#xB - #xC (ASCII 11 - 12)
#xE - #x1F (ASCII 14 - 31)
