### ISSUE TITLE
Integrating SOAPEngine into a CocoPod Library

### ISSUE THREAD

**Issue by waelsaad** [priore/SOAPEngine#172]
Hi,

I am trying to include the SOAPEngine64.framework inside MyProject.podspec as below but we keep getting an error :- 'SOAPEngine64/SOAPEngine.h' file not found :-

We kindly request an urgent response in order to make a decision on purchasing a fully Enterprise (multi App).

I tried to add it as a dependency and as a s.vendored_frameworks

Please send us clear instructions as to how we can integrate it.

Thank you.

MyProject.podspec
=================================================================== 

    Pod::Spec.new do |s|
      s.name             = 'MyProject'
      s.version          = '0.1.0'
      s.summary          = 'A short description of MyProject.'

    # This description is used to generate tags and improve search results.
    #   * Think: What does it do? Why did you write it? What is the focus?
    #   * Try to keep it short, snappy and to the point.
    #   * Write the description between the DESC delimiters below.
    #   * Finally, don't worry about the indent, CocoaPods strips it!

      s.description      = <<-DESC
    TODO: Add long description of the pod here.
                           DESC

      # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
      s.license          = { :type => 'MIT', :file => 'LICENSE' }
      s.source           = { :git => 'https://github.com/Wael/MyProject.git', :tag => s.version.to_s }
    #s.vendored_frameworks = 'CashInfinity/SOAPEngine64.framework'

      # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

      s.ios.deployment_target = '9.0'

      s.source_files = 'MyProject/Classes/**/*'
      
      # s.resource_bundles = {
      #   'MyProject' => ['MyProject/Assets/*.png']
      # }

      # s.public_header_files = 'Pod/Classes/**/*.h'
    #s.frameworks = 'SOAPEngine'
      s.dependency 'SOAPEngine'
      s.dependency 'GCDWebServer', '~> 2.3'
      s.dependency 'CocoaAsyncSocket'
      #s.dependency 'FBSnapshotTestCase'
      #s.dependency 'XCTest'

      s.library  = 'xml2.2'
      s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
    end

**Comment by waelsaad** [comment]
Nevermind I just got it working. Thanks anyway...

**Comment by priore** [comment]
We are happy that you have resolved, and we are happy for your trust, you can explain how you solved this? (for other users).

Sorry for elapsed time.

**Comment by waelsaad** [comment]
Sure, This is my updated MyProject.podspec. I also placed SOAPEngine64.framework in the root directly into the Pods folder

        #
        # Be sure to run `pod lib lint MyProject.podspec' to ensure this is a
        # valid spec before submitting.
        #
        # Any lines starting with a # are optional, but their use is encouraged
        # To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
        #

        Pod::Spec.new do |s|
          s.name             = 'MyProject'
          s.version          = '0.1.0'
          s.summary          = 'A short description of MyProject.'

        # This description is used to generate tags and improve search results.
        #   * Think: What does it do? Why did you write it? What is the focus?
        #   * Try to keep it short, snappy and to the point.
        #   * Write the description between the DESC delimiters below.
        #   * Finally, don't worry about the indent, CocoaPods strips it!

          s.description      = <<-DESC
        TODO: Add long description of the pod here.
                               DESC

            s.homepage         = 'https://github.com/Wael/MyProject'
            # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
            s.license          = { :type => 'MIT', :file => 'LICENSE' }
            s.author           = { 'Wael' => 'wael@abacus.co' }
            #s.source           = { :git => 'https://github.com/Wael/MyProject.git', :tag => s.version.to_s }
            s.source           = { :git => 'https://KinnovGitAccount@bitbucket.org/kinnovcode/MyProjectframework.git', :tag => s.version.to_s }

            #s.vendored_frameworks = 'MyProject/SOAPEngine64.framework'

            s.preserve_paths       = 'SOAPEngine64.framework'
            s.public_header_files  = 'SOAPEngine64.framework/Headers/*.h'
            s.source_files          = 'SOAPEngine64.framework/Headers/*.h'
            s.vendored_frameworks  = 'SOAPEngine64.framework'



            # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

            s.ios.deployment_target = '8.0'

            s.source_files = 'MyProject/Classes/**/*'

            # s.resource_bundles = {
            #   'MyProject' => ['MyProject/Assets/*.png']
            # }

            # s.public_header_files = 'Pod/Classes/**/*.h'
            #s.frameworks = 'SOAPEngine'
            #s.dependency 'SOAPEngine'
            s.dependency 'GCDWebServer', '~> 3.3'
            s.dependency 'CocoaAsyncSocket'
            #s.dependency 'FBSnapshotTestCase'
            #s.dependency 'XCTest'

            s.library  = 'xml2.2'
            s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
        end

**Comment by priore** [comment]
thanks for this advice
