### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by cristinaITdeveloper** [priore/SOAPEngine#173]
I would like to buy the license, but I do not have the definitive bundle of the app because it is still under development. How can I do?

Does the license have an expiration date?

**Comment by priore** [comment]
Hello,
after the purchase will receive an automatic email with a link to generate the license.

In the page you will write the expected bundle for your app, the same as used in iTunes Connect and "case sensitive", after confirmation we immediately send you another email with your license key.

Then you need set the property named "licenseKey" of library with its key, just for developing and only in simulator, you don't need a license key.

The license not have expiration.
Thanks for your interest and confidence.

**Comment by cristinaITdeveloper** [comment]
Ok, but I do not have the definitive bundle of the app because it is still under development.  How can I do? Can you change it later?

**Comment by cristinaITdeveloper** [comment]
It's ok, the client now has written me the definitive app bundle identifier!
Now I buy the license, thank you!

**Comment by cristinaITdeveloper** [comment]
Sorry, but after I entered the license key, the alert always appears. What can I do?

**Comment by priore** [comment]
We have tested your bundle and your license code, it's right, perhaps you don't have correctly  copied the license code or the bundle-id, please verify and use the license code that you received on email.

**Comment by cristinaITdeveloper** [comment]
I did a clean of project, now it's okay, I'm not getting the alert anymore!
Thank you!
