### ISSUE TITLE
We just purchased and we are getting a strange error with the commercial version - setSoapActionRequest not found

### ISSUE THREAD

**Issue by waelsaad** [priore/SOAPEngine#174]
Hi,

We just purchased and replaced the GitHub version with the commercial version and we are now getting the following error. We need to go live next week.

[soap setSoapActionRequest:@"OpenOperation"];
Property 'soapActionRequest' not found on object of type 'SOAPEngine *’

Please kindly assist as soon as possible. I have sent an email to support also.

Thank you,

Wael

**Comment by priore** [comment]
the version on GitHub is the same, for trial and for the Apple store, just changes the license code, not have any changes or differences, you can continue to use the GitHub version, always updated, but you need sets the your license code value in the licenseKey property.

Thanks

**Comment by waelsaad** [comment]
Hi, 

Thank you for the prompt response. The header file for the package we received is missing the property it is different to the one from GitHub. I am sure its not correct. We really need to fix the issue.

Thanks,

Wael

**Comment by waelsaad** [comment]
We have already set the licence code it has nothing to do with this problem

**Comment by waelsaad** [comment]
The other issue is when I use the correct working SOAPEngine64.framework from GitHib and insert the licence key and deploy to the iPad it still shows as a trial. !


soap.licenseKey = @"I put my generated licence here"; 

Thats the only line correct?


Thanks,

Wael

**Comment by waelsaad** [comment]
Hi, we really need to work to get this resolved because of a strict timeline. If there is a faster way to communicate please let me know there are currently 2 issues:-

1- With the licence key generated and deploy to the iPad with either the new version we downloaded or with the version from Github we still get the trial error msg

2- With the new version that we downloaded from the email the setSoapActionRequest property is missing from the header file and we need this to seperate the Action from the response we get back, the version from GitHub works perfectly fine except that we still get the trial error msg when we deploy to the iPad.

Thanks

Wael

**Comment by waelsaad** [comment]
Hi, 

Thank you for the prompt response. We have it working now. The bundle id was incorrect my bad. However the header file for the package we received from the email is different to the package from Github.

I am using the Github version and its working fine but the one distributed in the email is not correct.

Thanks,

Wael

**Comment by priore** [comment]
Thanks for the heads up, we will provide as soon possible.
