### ISSUE TITLE
Question about the enterprise licence

### ISSUE THREAD

**Issue by rvi** [priore/SOAPEngine#176]
Hi, I'd like to use SOAPEngine, but I have a few questions about the enterprise licence. 
I'm building a SDK to connect to ONVIF camera (IP with SOAP).

The sdk helps the developers to connect to an ONVIF camera and vizualise the live stream from it.

The goal of the sdk is to be open source and it will mainly use during a hackaton.
If I get the enterprise licence, every developer will be able to use SOAPEngine on their iPhone during the hackaton? Each of them will create their own app, with their own bundle ID.

Thanks for your help!

**Comment by priore** [comment]
The enterprise license is combined with a bundle suffix, e.g. _com.myorganization_, with it you can create many apps e.g. _com.myorganization.app1_, _com.myorganization.app2_ etc., _com.myoriganization_ is **mandatory** and must always be **same for all apps**.

Thanks for your interest.

**Comment by rvi** [comment]
Thanks, it should work then!
