### ISSUE TITLE
SOAPEngine : Cannot call value of non-function type 'URL' IN SWIFT 4.0

### ISSUE THREAD

**Issue by dajdouj10** [priore/SOAPEngine#177]

**Comment by priore** [comment]
you get the latest version from Github?

**Comment by dajdouj10** [comment]
yes 
Version  : 1.40.5 from Pods

**Comment by priore** [comment]
don't use `import SOAPEngine64` in you swift class, use the bridge file, with `#import <SOAPEngine64/SOAPEngine.h>`, [read this](https://github.com/priore/SOAPEngine/wiki/Integrating-SOAPEngine-with-a-Swift-project).

**Comment by dajdouj10** [comment]
yes 
<img width="873" alt="screen shot 2018-01-22 at 1 52 22 pm" src="https://user-images.githubusercontent.com/4354679/35217285-af5e5db2-ff7b-11e7-8fd2-2098e27ad06d.png">

**Comment by priore** [comment]
and you have set in the "Build settings" ?

![schermata 2018-01-22 alle 11 56 40](https://user-images.githubusercontent.com/1537350/35217518-dd803590-ff6b-11e7-9741-376401316ecf.jpg)

**Comment by dajdouj10** [comment]
<img width="920" alt="screen shot 2018-01-22 at 2 12 28 pm" src="https://user-images.githubusercontent.com/4354679/35218230-e617dfce-ff7e-11e7-8931-59a237a49ae3.png">

**Comment by priore** [comment]
we did an empty project with swift 4 and everything works, try also to use the example in github, if you want we can send to you the our example just done.

**Comment by priore** [comment]
hello @dajdouj10 you have resolved ?

if you have solved, please close this issue, thanks.
