### ISSUE TITLE
request NSDictionary with NSArray as sub key results in single xml tag

### ISSUE THREAD

**Issue by TheRealDarklord** [priore/SOAPEngine#179]
Hello everyone,

I've got a SOAP webservice which requires the following request params

param 1: a simple string - no problem, added via SOAPEngine setValue: forKey:
param 2: another simple string - no problem either
param 3: complex data object with the following structure

```objective-c
NSDictionary *data = @{
  @"description": @"i am a description",  
  @"name": @"i am a name"  
  @"subdata": @[
    @{
      @"name": @"i am a name too",
      @"profession": @"worker"
    },
    @{
      @"name": @"just another name",
      @"profession": @"worker"
    }
  ]
};
```

I added the third param in the same way as the others, SOAPEngine setValue:data forKey:@"param3"

this results in the following request XML:
```xml
<param1>a simple string</param1>
<param2>another simple string</param2>
<param3>
  <description>i am a description</description>
  <name>i am a name</name>
  <subdata>
    <name>i am a name too</name>
    <profession>worker</profession>
    <name>just another name</name>
    <profession>worker</profession>
  </subdata>
</param3>
```

but this is just not as intended, I need the request XML in the following way:
```xml
<param1>a simple string</param1>
<param2>another simple string</param2>
<param3>
  <description>i am a description</description>
  <name>i am a name</name>
  <subdata>
    <name>i am a name too</name>
    <profession>worker</profession>
  </subdata>
  <subdata>
    <name>just another name</name>
    <profession>worker</profession>
  </subdata>
</param3>
```

I already tried using SOAPEngine setValue:subData forKey:@"param3" subKeyName:@"subdata". This results in a correct output for the subdata part, but now I am missing the description and name tag of param3. If I add another setValue: forKey: subKey:Name for those missing tags it results in rendering in a complete new param3-Tag. I don't know how to achieve the targeted data structure.

**Comment by priore** [comment]
Hi,
sorry, there's no quick way for this xml format, but you can always use an array of parameters, as you can see below:

```objective-c
NSArray *param3 = @[
                        @{@"description": @"i am a description"},
                        @{@"name": @"i am a name"},
                        @{@"subdata": @{
                                  @"name": @"i am a name too",
                                  @"profession": @"worker"
                                  }
                          },
                        @{@"subdata": @{
                                  @"name": @"just another name",
                                  @"profession": @"worker"
                                  }
                          }
                        ];

[soap setValue:param3 forKey:@"param3"];
```

**Comment by TheRealDarklord** [comment]
Well, although it's not obvious to do it this way it works great. Thank you :)
