### ISSUE TITLE
using requestWSDL failed and got 415 issue

### ISSUE THREAD

**Issue by kylesunjk** [priore/SOAPEngine#18]
Hi 
I have using your soapengine to request a Url from my sever, however i always got the error 415 when parsing the data.

here is the soap object that i have generate.
![image](https://cloud.githubusercontent.com/assets/3692350/5565583/7e4b8d40-8f3e-11e4-9a47-869bbfbbf94c.png)

and the block finish with failwitherror and the error shows that invaild WSDL format.
![image](https://cloud.githubusercontent.com/assets/3692350/5565590/d0492b70-8f3e-11e4-8eed-39827d39e796.png)

can you help me with this error.

Thanks a lot

**Comment by priore** [comment]
you have solved ?

**Comment by kylesunjk** [comment]
Hi
Not yet , but my team decide to recreate the backend sever using other
framework.

but anyway thanks a lot .

I will close the issue in github.

Regards

2015-01-15 5:29 GMT+08:00 Danilo Priore <notifications@github.com>:

**Comment by TamilRaja** [comment]
Hi friends

 I got some error for this SDK used. I have used this URL and Parameters. Can you please how to use this?

 [soap setValue:@"" forKey:@"businessCode"];
    [soap setValue:@"wear" forKey:@"businessName"];
    [soap setIntegerValue:@"" forKey:@"location"];
    [soap setIntegerValue:@"" forKey:@"categoryKeyword"];
    [soap setIntegerValue:@"1" forKey:@"PageNumber"];
    [soap setIntegerValue:@"10" forKey:@"paginationSize"];
    [soap setValue:@"en" forKey:@"languageCode"];
    
    [soap requestURL:@"http://82.178.20.92:8080/CRM/services/SearchBusiness.ws"
          soapAction:@"http://82.178.20.92:8080/CRM/services/SearchBusiness.ws?wsdl"];

**Comment by priore** [comment]
@TamilRaja , please use only one issue for the same case, this is not a forum but a service of support and assistance to the issues ( #55 ), thanks.
