### ISSUE TITLE
SOAPEngine dosent convert base class object to XML after 2 levels of inheritance

### ISSUE THREAD

**Issue by Vivekananda0099** [priore/SOAPEngine#183]
My Class structure is as follows,

```objective-c
@interface ClassA : JSONModel
@property int ProductId;
@end

@interface ClassB : ClassA
@property NSString *ProductName;
@end

@interface ClassC : ClassB
@property NSString *ProductType;
@end
```

When i try to send an object of classC to web service i am noticing that the SOAPEngine is not converting the variable's of base class i.e. ClassA's  to XML.

```objective-c
ClassC *c = [ClassC new];
c.ProductId = 11;
c.ProductName = @"ProductName";
c.ProductType = @"ProductType";
    
[soap setValue:c forKey:@"TrxLine"];
[soap transactionTest:^(NSInteger statusCode, NSDictionary *dict) 
{
    // ...
} failure:^(NSError *error)
{
    // ...
}];
```

In didBeforeSendingURLRequest, when i inspect the [request HTTPBody] the request XML is as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Header />
 <soap:Body>
      <TransactionTest xmlns="http://semnox.com/">
         <TrxLine>
            <ProductType>ProductType</ProductType>
            <ProductName>ProductName</ProductName>
         </TrxLine>
      </TransactionTest>
   </soap:Body>
</soap:Envelope>
```

Since i have set the  c.ProductId = 11; which is actually present in ClassA but SOAPEngine has not converted it to XML.

This works fine if object of ClassA or ClassB is send to web service. 

Can anybody tell me why this is happening? and how i can resolve it?

**Comment by priore** [comment]
we have fixed.

thanks for your patience

**Comment by Vivekananda0099** [comment]
May i know how do i get the updates?

**Comment by priore** [comment]
You can download the last versions from [GitHub](https://github.com/priore/SOAPEngine), or integrate the pod management with [Cocoapods](https://cocoapods.org).

**Comment by Vivekananda0099** [comment]
It working now. Thank you for the quick update.
