### ISSUE TITLE
Fetching time delay in completion block

### ISSUE THREAD

**Issue by Spande90** [priore/SOAPEngine#184]
soapEngine URLRequest  for a dictionary of 19 keys with sub 9 keys with one key containing string of about 300 character is taking time which on the android is much less

in android it takes 0.788 sec
in iOS it takes 11.2 sec  till I get my result from completion blocks of URL Request

**Comment by priore** [comment]
you can send the contents of the dictionary? (even in json format if it's easier for you)

thanks

**Comment by Spande90** [comment]
the response from api is in son but the response from the completion block of soapEngine returning dictionary is taking time.

**Comment by priore** [comment]
the SOAPEngine 1.x parser is slow, we know this, but you can use the SOAPEngine delegates that returns raw data and you parse it with TBXML, or UTXMLDictionary for Swift, that speed up the parsing, like this https://github.com/priore/SOAPEngine/wiki/Improve-the-performance-(Swift).

**Comment by Spande90** [comment]
shouldn't this issue with slow parsing be solved for paid clients? also the library mentioned are depreciated.
