### ISSUE TITLE
Soap Action incomplete in _xmlResponse

### ISSUE THREAD

**Issue by sabado** [priore/SOAPEngine#186]
Hi, I'm trying to send a query whit various values in the follow way using delegates. 
 ```
   SOAPEngine *soap = [[SOAPEngine alloc] init];
    soap.licenseKey = SOAP_LICENSE_KEY	;
    soap.userAgent = @"SOAPIOS";
    soap.delegate = self;
    soap.version = VERSION_WCF_1_1; // WCF service (.svc)
    soap.actionNamespaceSlash = YES;

[soap addValue:@"my val" forKey:@"myKey1"];
[soap addValue:@"my val" forKey:@"myKey2"];
[soap addValue:@"my val" forKey:@"myKey3"];
...
 soap.responseHeader = YES;
   
    [soap requestURL:@"https://my.service.com/something/url.asmx"
        soapAction:@"http://my.service.com/mymethod" ];
```
    

I'm getting error, like nothing sended. I inspect the didBeforeSendingURLRequest and I found that the soapAction domain is bad formed. and the url http://my.service.com/ did not appear, instead only appears http:/ like this part of the xml code.  

`<soap:Body>< mymethod xmlns="http:/"> `

In other request it's works well (just only think is I have to use actionNamespaceSlash to append the slash at end of the domain action)

**Comment by priore** [comment]
👍
