### ISSUE TITLE
LicenseKey doesn't work anymore...

### ISSUE THREAD

**Issue by DanielAbacus** [priore/SOAPEngine#187]
@DaniloPriore Hi, Priore, we have purchased one license from you for SoapEngine in last year. We integrate it with our apps, And it works fine with our several customers. But right now, the new customer who installed our app, are facing this, would you mind help us check what's wrong? We have tried to download the same build from our office, which works fine. But it doesn't work with our Customer's iPad:
![screen shot 2018-12-05 at 10 43 53 am](https://user-images.githubusercontent.com/32082452/49481792-85420980-f880-11e8-90ba-978b21ec71be.png)

And also, do you know how could we check if one license key is for single app or enterprise?

**Comment by DanielAbacus** [comment]
Hi,

Actually, I think we lost the email of the purchase…. If there is any other way to find out the type of the license?

And back to the bug… not sure why it happened… It works after our customer delete the app and re-install it again…. I believe the iOS version is the latest one, not sure about the Models….

Regards
Daniel

**Comment by priore** [comment]
for know if your license and single or enterprise you can temporarily change the bundle-id of your app, if you have eg. com.organziazion.app-name, remove .app-name and try to run the app, if after it you see the license message then you have a single license, if not then you have a enterprise license.

**Comment by DanielAbacus** [comment]
Thx, will have a try.

Regards
Daniel

**Comment by DanielAbacus** [comment]
Hi priore, seems like it happened again....

One of my co-wrokers will try to gather the information you need, p

**Comment by DanielAbacus** [comment]
Hi Priore

Seems like the same issue happened again, as it happened occasionally in one of our client…
One of my co-workers is in charge of this, and he will provide more details to you.

Hi Rameez

Please provide Priore the iPad and the iOS versions of our customer.
And please have a test to check if we are using enterprise license or single license based on this:
“for know if your license and single or enterprise you can temporarily change the bundle-id of your app, if you have eg. com.organziazion.app-name, remove .app-name and try to run the app, if after it you see the license message then you have a single license, if not then you have a enterprise license.”

P.S.
I think we are using enterprise license… as we have re-used this code inside two different pods Library which were re-used in two different apps…
But, Hi Priore, do you think it might be an issue if one of our Application imported two different pods Library using SoupEngine?

Regards
Daniel

**Comment by RameezAbacus** [comment]
Hi Priore! 
I have created three app versions by changing the bundle-id, It works fine on my iPad but one of our customer using our app gets this error message all the time.
We are not using SOAP Engine directly but we have libraries with SOAP Engine. Can We have multiple instances of SOAP Engine in the Same Project
![img_0cb3311c6f88-1](https://user-images.githubusercontent.com/45954974/50132966-bfc69000-02dd-11e9-97a4-c58df50297fe.jpeg)
Regards
Rameez

**Comment by priore** [comment]
Hello,
so, it looks like a thread problems, but our library is thread safe, so try wrapping the call in an NSOperationQueue block.

**Comment by RameezAbacus** [comment]
Hi Priore!
I am facing this issue again ... Last time it started working by itself
![image](https://user-images.githubusercontent.com/45954974/56007733-06bd1300-5d1d-11e9-9afc-abd931231421.png)

**Comment by priore** [comment]
Hello,
some users have written to me that they had the same problem, it turned out that in the xcodeproject file the bundleid was enclosed in quotation marks, this was the problem, could you also verify yourself by opening the xcodeproject file with a text editor?

Thank you

**Comment by priore** [comment]
Please, try the latest version.

**Comment by RameezAbacus** [comment]
@priore 
Which Bundle Id we need to check in our Xcode project?

Will updating the SOAPEngine Will Fix it?

**Comment by priore** [comment]
Hello,
the update expect the possibility the bundle-id is enclosed in quotes, so see if the your problem is solved in this way, for another our customer this problem is solved with this fix.

thanks.

**Comment by RameezAbacus** [comment]
Sorry @priore 
I am not clear which bundle ID, you are referring to when I opened my xcodeproject file 

![Screen Shot 2019-04-16 at 10 42 19 am](https://user-images.githubusercontent.com/45954974/56174276-18602c80-6035-11e9-840c-08481ae2b741.png)
![Screen Shot 2019-04-16 at 10 45 35 am](https://user-images.githubusercontent.com/45954974/56174277-18602c80-6035-11e9-95ab-4fe3b0b1d513.png)

**Comment by priore** [comment]
Hello,
if your bundleid is `com.kinnov.posskient` you don't have any license generated for this bundle, and therefore on the device you will always see the message.

**Comment by RameezAbacus** [comment]
But we are not using single license.... 
Our license is enterprise... This issue occurs occasionally not always ...

**Comment by RameezAbacus** [comment]
Can you suggest any fix for this issue ?

**Comment by priore** [comment]
Same, for `com.kinnov` we don't have any license key in our databases.

**Comment by RameezAbacus** [comment]
We might have used one of the following Bundle Identifiers for ordering license key :
com.kinnov.ent.tableordering
com.kinnov.tableordering

Can you please check in your database?

**Comment by RameezAbacus** [comment]
This is the copy of email :
<img width="1101" alt="Screen Shot 2019-04-17 at 9 52 24 am" src="https://user-images.githubusercontent.com/45954974/56251372-b10ab100-60f6-11e9-831b-b0dfb49b1eb4.png">

**Comment by RameezAbacus** [comment]
Our Organization Identifier in Purchase Email is co.abacus

But In Our Apps identifier starts with 
com.abacus ( for app store release ) 
com.kinnov (for enterprise release)

Is there any way we can fix this ?

**Comment by priore** [comment]
Hello,
if the purchase has been associated with the `co.abacus` bundle-id, it can be used only with this bundle (_co.abacus.app-name1, co.abacus.app-name2 etc._), it cannot be otherwise because the licensekey is bundle-id dependent, if you change your bundle-id you need to buy a different license, as written in the [EULA](https://github.com/priore/SOAPEngine/blob/master/General%20License%20iOS.pdf) the purchase of the license is associated with the bundle-id, in your case the initial part (_co.abacus_), to us there is no license for `com.abacus` and for `com.kinnov`, but there is a license only for **co.abacus**

**Comment by priore** [comment]
we can reset the license code but you need to choose the bundle-id that you want, only one, if you use `com.kinnov` for development and then `com.abacus` for the app store you will need to buy a second license.

**Comment by RameezAbacus** [comment]
Can you please reset co.abacus to com.kinnov? (Do we need to change the license key in our code after this reset ?)
And For com.abacus  we will get the second license.

**Comment by priore** [comment]
Hello,
we have reset your license key, use the link in the confirmation email to generate the new code.

**Comment by RameezAbacus** [comment]
Hello Priore!
What will happen to our those customers that are using the version with existing license key ... Will it affect them?

**Comment by priore** [comment]
The validation of the license does not take place remotely, so as not to overload the devices, whoever has the previous app and works correctly will continue as is.
