### ISSUE TITLE
Connection error within app-tunnel

### ISSUE THREAD

**Issue by schamarc** [priore/SOAPEngine#188]
Hi! This is Marc-Oliver from GFI.

We use your SOAPengine Framework with one of our products. Now we ran into a problem which we cannot explain. The app uses an app-vpn to connect to a web service. If we limit the connection only to this specific host, we will receive a time out/connection error. Do we open the connection, everything works finde. By any chance: Do you link to external libraries or a license sever upon first calling the WSDL service?

Thanks a lot!

**Comment by priore** [comment]
Hello,
we do not make any additional calls, only the URLs of your services are called.

try following solutions:

1) restarting the simulator.
2) resetting content and settings of simulator.
3) increase `requestTimeout` value.

**Comment by schamarc** [comment]
Hi. It is not about the simulator. The problems occur inside app-vpn of Mobile Iron.

What about DNS queries etc? Can you disclose a few lines of code where you make the very first call to the web service?

Thanks.

**Comment by priore** [comment]
Hi,
the library was created in 2012 and therefore still uses `NSURLConnection` (but we are developing the pure swift version) and you can see the request, with the header and the content, using the delegate named `didBeforeSendingURLRequest`, that you can use to modify its before real sending.

We recommend using [Charles Proxy](https://www.charlesproxy.com) to see what really happens during the request.

If you want we can do further tests, but we need all the data necessary to reproduce your situation, in this case by email for security.

thanks

**Comment by priore** [comment]
UPDATE: maybe it could be a problem of validity of SSL certificates, you could try setting `selfSigned = true` to ignore any SSL certificate request and see if with this solve.
