### ISSUE TITLE
SOAPEngine Caching the Authentication Realm

### ISSUE THREAD

**Issue by RiftValleySoftware** [priore/SOAPEngine#189]
This may be a simple question with a simple answer.

I am using SOAPEngine under an ONVIF driver, and doing the standard challenge/response to get an authentication realm.

However, I have noticed that SOAPEngine seems to cache the realm between invocations.

This causes problems for me, because I keep the realm separately, and need to know when the realm is being sent to the device.

So, how can I:

1) Clear SOAPEngine completely to stop the realm from being cached, or
2) Fetch the cached realm from a new SOAPEngine instance before trying to probe the device.

#2 is probably preferable.

**Comment by RiftValleySoftware** [comment]
Actually, this may be an issue with iOS. I am looking into that now...

**Comment by RiftValleySoftware** [comment]
Ah. It looks like it is a shared URLSession that needs to be cleared.

**Comment by RiftValleySoftware** [comment]
That's what comes from starting from someone else's codebase.

To be clear: This is not your problem. It is mine.

**Comment by priore** [comment]
I think you can use the `didBeforeSendingURLRequest` delegare and modify the `URLRequest` that it returns.

**Comment by RiftValleySoftware** [comment]
Thanks! That could be useful for other matters.

I appreciate the fast turnaround. SOAPEngine has been working great for me so far.
