### ISSUE TITLE
Paid version doesn't work

### ISSUE THREAD

**Issue by danisnake** [priore/SOAPEngine#19]
Hello!

I've already payed for the SOAPEngine, put the license code I received on soap.licenseKey with the exact bundle id that I provide you, but it still show the demo popup. Can you help?

Thanks

**Comment by priore** [comment]
Hi danisnake,
you have properly copied the license ?
be sure that during the copy of the license does not contain special characters such as < or >

**Comment by danisnake** [comment]
It's exactly that, the license includes <WBR> in it on the email.
Thanks for the help.
