### ISSUE TITLE
Strange: Empty Directory Returned for Full XML Response

### ISSUE THREAD

**Issue by RiftValleySoftware** [priore/SOAPEngine#190]
I am working on an ONVIF client. So far, everything has been working.

Until today.

When I get the response to the ONVIF "GetServiceCapabilities" call, I see the XML coming in from the camera just fine.

However, in the response Dictionary, the inner members are empty, even though they are full. I will paste in what I am seeing in Charles Proxy, and what the Xcode console is showing me (It will show your traces and mine). You will see that the delivered Dictionary does not have the contents of the Network, Security and System capability records:

Charles Proxy (RAW, Sending). I have redacted the authorization info:

    POST /onvif/device_service HTTP/1.1
    Host: 192.168.3.26:80
    Content-Type: text/xml; charset=utf-8; action="trt:GetServiceCapabilities"
    Accept-Encoding: gzip, deflate
    SOAPAction: "trt:GetServiceCapabilities"
    Accept: text/xml; charset=utf-8
    User-Agent: SOAPEngine
    Content-Length: 380
    Authorization: Digest username="<USER-NAME>", realm="<REALM>", nonce="<NONCE>", uri="/onvif/device_service", response="<RESPONSE>", algorithm="MD5", cnonce="<CNONCE>", nc=00000002, qop="auth"
    Accept-Language: en-us
    Connection: keep-alive

    <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"  xmlns:trt="http://www.onvif.org/ver10/device/wsdl"><soap:Header></soap:Header><soap:Body><trt:GetServiceCapabilities></trt:GetServiceCapabilities></soap:Body></soap:Envelope>

Charles Proxy (RAW, Receiving):

    HTTP/1.1 200 OK
    Date: Thu, 14 Feb 2019 21:59:02 GMT
    Server: Apache/2.4.35 (Unix) OpenSSL/1.0.2p
    Authentication-Info: rspauth="<AUTH>", cnonce="<CNONCE>", nc=00000002, qop=auth
    Content-Type: application/soap+xml; charset=utf-8
    Content-Length: 3539
    Keep-Alive: timeout=5, max=100
    Proxy-Connection: keep-alive

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:acert="http://www.axis.com/vapix/ws/cert" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:aa="http://www.axis.com/vapix/ws/action1" xmlns:acertificates="http://www.axis.com/vapix/ws/certificates" xmlns:aentry="http://www.axis.com/vapix/ws/entry" xmlns:aev="http://www.axis.com/vapix/ws/event1" xmlns:aeva="http://www.axis.com/vapix/ws/embeddedvideoanalytics1" xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding" xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding" xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding" xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding" xmlns:ali="http://www.axis.com/vapix/ws/light" xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1" xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1" xmlns:asd="http://www.axis.com/vapix/ws/shockdetection" xmlns:aweb="http://www.axis.com/vapix/ws/webserver" xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetServiceCapabilitiesResponse><tds:Capabilities><tds:Network DHCPv6="true" NTP="1" DynDNS="true" IPVersion6="true" ZeroConfiguration="true" IPFilter="true"></tds:Network><tds:Security HttpDigest="true" UsernameToken="true" DefaultAccessPolicy="true" AccessPolicyConfig="true" OnboardKeyGeneration="true" TLS1.2="true" TLS1.1="true" TLS1.0="true"></tds:Security><tds:System SystemLogging="true" DiscoveryBye="true" DiscoveryResolve="true"></tds:System></tds:Capabilities></tds:GetServiceCapabilitiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

The Xcode Console:

        2019-02-14 16:59:02.338295-0500 RVS_ONVIF Test Harness[69679:5880940] Initializing SOAPEngine v.1.42
    THIS IS MINE:
        SOAP Request URL: http://192.168.3.26:80/onvif/device_service
        beforeParsingData: Optional(3539 bytes)
    END
        2019-02-14 16:59:02.721807-0500 RVS_ONVIF Test Harness[69679:5880940] origin: , from dict:
        2019-02-14 16:59:02.722026-0500 RVS_ONVIF Test Harness[69679:5880940] origin: , from dict:
        2019-02-14 16:59:02.722192-0500 RVS_ONVIF Test Harness[69679:5880940] origin: , from dict:
        2019-02-14 16:59:02.722329-0500 RVS_ONVIF Test Harness[69679:5880940] origin: , from dict:
    THIS IS MINE:
        SOAP Success. Response Dictionary: ["Header": , "Body": {
            GetServiceCapabilitiesResponse =     {
                Capabilities =         {
                    Network = "";
                    Security = "";
                    System = "";
                };
            };
        }]
        Successful trt:GetServiceCapabilities SOAP Call. Response: ["Header": , "Body": {
            GetServiceCapabilitiesResponse =     {
                Capabilities =         {
                    Network = "";
                    Security = "";
                    System = "";
                };
            };
        }]
    END

**Comment by RiftValleySoftware** [comment]
I think I may have an idea why.

I'd have to look at the WSLD for the call, but it looks like the capabilities are expressed as attributes; not nodes.

    <tds:Security
        HttpDigest="true"
        UsernameToken="true"
        DefaultAccessPolicy="true"
        AccessPolicyConfig="true"
        OnboardKeyGeneration="true"
        TLS1.2="true"
        TLS1.1="true"
        TLS1.0="true"></tds:Security>

Is there an option I can set in SOAPEngine for it to interpret these as values?

**Comment by priore** [comment]
Hi,
you can use the property named `retrievesAttributes`. 

An information for you; the SOAPEngine.h file contains a summary description of all properties and methods, including delegates.

thanks for your trust.

**Comment by RiftValleySoftware** [comment]
Thanks. I have been looking at that file, but I guess I missed that command.

I'll test, and probably close this issue soon.

Again, thanks. SOAPEngine has saved me a great deal of time and effort.

**Comment by RiftValleySoftware** [comment]
There may be a bug. It appears to be ignoring the parameter. I am setting it to true, and I get exactly the same (empty) response:

    SOAP Success. Response Dictionary: ["Header": , "Body": {
        GetServiceCapabilitiesResponse =     {
            Capabilities =         {
                Network = "";
                Security = "";
                System = "";
            };
        };
    }]
    Successful trt:GetServiceCapabilities SOAP Call. Response: ["Header": , "Body": {
        GetServiceCapabilitiesResponse =     {
            Capabilities =         {
                Network = "";
                Security = "";
                System = "";
            };
        };
    }]
    Service Capabilities: ["Header": , "Body": {
        GetServiceCapabilitiesResponse =     {
            Capabilities =         {
                Network = "";
                Security = "";
                System = "";
            };
        };
    }]

Here is the section of code where I set up SOAPEngine:

                let soap = SOAPEngine() // We initialize a new SOAPEngine for each call.
                soap.delegate = self    // We allow interception of delegate calls.
                soap.licenseKey = self._soapEngineLicenseKey    // So we can work on devices.
                soap.version = .VERSION_1_2
                soap.authorizationMethod = .AUTH_DIGEST
                soap.username = self.loginCredentials?.login ?? ""
                soap.password = self.loginCredentials?.password ?? ""
                soap.envelope = inRequest.headerNamespace
                soap.retrievesAttributes = true

**Comment by priore** [comment]
We have tested with your XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:acert="http://www.axis.com/vapix/ws/cert" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:aa="http://www.axis.com/vapix/ws/action1" xmlns:acertificates="http://www.axis.com/vapix/ws/certificates" xmlns:aentry="http://www.axis.com/vapix/ws/entry" xmlns:aev="http://www.axis.com/vapix/ws/event1" xmlns:aeva="http://www.axis.com/vapix/ws/embeddedvideoanalytics1" xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding" xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding" xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding" xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding" xmlns:ali="http://www.axis.com/vapix/ws/light" xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1" xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1" xmlns:asd="http://www.axis.com/vapix/ws/shockdetection" xmlns:aweb="http://www.axis.com/vapix/ws/webserver" xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnsaxis="http://www.axis.com/2009/event/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetServiceCapabilitiesResponse><tds:Capabilities><tds:Network DHCPv6="true" NTP="1" DynDNS="true" IPVersion6="true" ZeroConfiguration="true" IPFilter="true"></tds:Network><tds:Security HttpDigest="true" UsernameToken="true" DefaultAccessPolicy="true" AccessPolicyConfig="true" OnboardKeyGeneration="true" TLS1.2="true" TLS1.1="true" TLS1.0="true"></tds:Security><tds:System SystemLogging="true" DiscoveryBye="true" DiscoveryResolve="true"></tds:System></tds:Capabilities></tds:GetServiceCapabilitiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

with the flag set to YES (or true for Swift):

```objc
soap.retrievesAttributes = YES;
```

and returns the dictionary with attributes values, on `didFinishLoading` delegate, like below:

```
{
    Network =     {
        attributes =         {
            DHCPv6 = true;
            DynDNS = true;
            IPFilter = true;
            IPVersion6 = true;
            NTP = 1;
            ZeroConfiguration = true;
        };
        value = "";
    };
    Security =     {
        attributes =         {
            AccessPolicyConfig = true;
            DefaultAccessPolicy = true;
            HttpDigest = true;
            OnboardKeyGeneration = true;
            "TLS1.0" = true;
            "TLS1.1" = true;
            "TLS1.2" = true;
            UsernameToken = true;
        };
        value = "";
    };
    System =     {
        attributes =         {
            DiscoveryBye = true;
            DiscoveryResolve = true;
            SystemLogging = true;
        };
        value = "";
    };
}
```

**Comment by RiftValleySoftware** [comment]
Huh. Let me look at didFinishLoading. I don't use that. I use the requestURL handler, like so:

                    // This is the actual SOAPEngine request. We ask for a parsed Dictionary in response.
                    soap.requestURL(reqURLString, soapAction: requestAction, completeWithDictionary: { (statusCode: Int, dict: [AnyHashable: Any]?) -> Void in
                        DispatchQueue.main.async {  // Handlers are always in the main thread.
                            // This is the main "success" closure. We have a status code (Int), and a dictionary of parsed SOAP response data.
                            if statusCode != 200,   // Bad status, we query the response data for a reason for failure.
                                let dict = dict as? [String: Any],
                                let body = dict["Body"] as? [String: Any],
                                let fault = body["Fault"] as? [String: Any],
                                let reasonDict = fault["Reason"] as? [String: Any],
                                let reason = reasonDict["Text"] as? String {
                                // We have both a status code (Int), and a reason string
                                self._errorCallback(.droppedTheSoapError_connection_soap_fault(statusCode, reason), soapRequest: requestAction, soapEngine: soap)
                            } else if statusCode != 200 {   // If we couldn't find a reason, then we return only the status code.
                                #if DEBUG
                                    print("SOAP Error. Status Code: \(statusCode), Response Dictionary: " + String(describing: dict))
                                #endif
                                self._errorCallback(.droppedTheSoapError_connection_failure(statusCode), soapRequest: requestAction, soapEngine: soap)
                            } else if let dict = dict as? [String: Any] {   // We are a success if we have a status code of 200, and a response data dictionary.
                                #if DEBUG
                                    print("SOAP Success. Response Dictionary: " + String(describing: dict))
                                #endif
                                self._successCallback(dict, soapRequest: requestAction, soapEngine: soap)
                            } else {    // If we got here, then there's something wrong with the Dictionary.
                                self._errorCallback(.droppedTheSoapError_invalid_content(dict), soapRequest: requestAction, soapEngine: soap)
                            }
                        }
                    }, failWithError: { (error: Error?) -> Void in  // We get here if there was a general calling problem.
                        #if DEBUG
                            print("SOAP Request Error: \(String(describing: error))")
                        #endif
                        DispatchQueue.main.async {
                            self._errorCallback(.droppedTheSoapError_request_fail(error), soapRequest: requestAction, soapEngine: soap)
                        }
                    })
                } else {
                    #if DEBUG
                        print("SOAP Realm Error: nil realm!")
                    #endif
                    DispatchQueue.main.async {
                        self._errorCallback(.droppedTheSoapError_nil_realm, soapRequest: "", soapEngine: soap)
                    }
                }

**Comment by RiftValleySoftware** [comment]
I'm not seeing what you are seeing, even with the delegate handler.

Let me spend some time examining the data. That will take more parsing. I see that the data has a lot of stuff, but the Dictionary does not:

    didFinishLoadingWith Dictionary: Optional([AnyHashable("Body"): {
        GetServiceCapabilitiesResponse =     {
            Capabilities =         {
                Network = "";
                Security = "";
                System = "";
            };
        };
    }, AnyHashable("Header"): ])
    didFinishLoadingWith Data: Optional(3539 bytes)

**Comment by priore** [comment]
we have tested with you same code and in the conditional check: 
```swift
if let dict = dict as? [String: Any]
```
with
```swift
print("SOAP Success. Response Dictionary: " + String(describing: dict))
```
we have same result with all attribute values:
```
SOAP Success. Response Dictionary: ["Security": {
    attributes =     {
        AccessPolicyConfig = true;
        DefaultAccessPolicy = true;
        HttpDigest = true;
        OnboardKeyGeneration = true;
        "TLS1.0" = true;
        "TLS1.1" = true;
        "TLS1.2" = true;
        UsernameToken = true;
    };
    value = "";
}, "Network": {
    attributes =     {
        DHCPv6 = true;
        DynDNS = true;
        IPFilter = true;
        IPVersion6 = true;
        NTP = 1;
        ZeroConfiguration = true;
    };
    value = "";
}, "System": {
    attributes =     {
        DiscoveryBye = true;
        DiscoveryResolve = true;
        SystemLogging = true;
    };
    value = "";
}]
```
but we tested directly with the xml, without making the request.

you try with:

```swift
soap.retrievesAttributes = true
soap.envelope = "xmlns:wsdl=\"http://www.onvif.org/ver10/device/wsdl\"" // not trt
soap.setValue("All", forKey: "wsdl:Cegetory")
```

**Comment by RiftValleySoftware** [comment]
Hmm... that "trt" is necessary for the ONVIF to match the internal calls. But let me try that.

**Comment by RiftValleySoftware** [comment]
Yeah, I'm getting an error from the camera: "Validation constraint violation: tag name or namespace mismatch in element wsdl:Category"

Let me mess around with things, and see if I can shake anything loose.

I am working directly from the ONVIF spec. It's an ugly spec, but I've found the wisdom in following their examples.

**Comment by RiftValleySoftware** [comment]
Unfortunately, the camera is fairly strict on what it will accept from me. For example, it did not accept namespaces directly embedded in element openings. It required me to have them in the envelope, and referenced by namespace indicators ("trt:GetDeviceInformation", instead of "GetDeviceInformation xmlns=...").
If I change the namespace in the envelope, the camera barfs.

**Comment by RiftValleySoftware** [comment]
Fo the record, here's my entire SOAP caller routine:

    /* ################################################################## */
    /**
     This is inspired by the ONVIFCamera library, by Rémy Virin, but I'm a jerk, and couldn't leave well enough alone.

     Perform a SOAP request
     Responses happen through the error and success instance callbacks.
     
     - parameter request: The Device Request instance.
     - parameter asSSL: An optional Bool (default is false), that requires the request to be made as SSL (HTTPS).
     */
    internal func _performSOAPRequest(request inRequest: _DeviceRequest, asSSL inAsSSL: Bool = false) {
        // We use the global queue for this.
        DispatchQueue.global(qos: .default).async { [weak self] in
            if let self = self {    // Make sure that we know who we are.
                let soap = SOAPEngine() // We initialize a new SOAPEngine for each call.
                soap.retrievesAttributes = true
                soap.delegate = self    // We allow interception of delegate calls.
                soap.licenseKey = self._soapEngineLicenseKey    // So we can work on devices.
                soap.version = .VERSION_1_2
                soap.authorizationMethod = .AUTH_DIGEST
                soap.username = self.loginCredentials?.login ?? ""
                soap.password = self.loginCredentials?.password ?? ""
                soap.envelope = inRequest.headerNamespace // Either xmlns:trt="http://www.onvif.org/ver10/device/wsdl" or xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
    //                soap.envelope = "xmlns:wsdl=\"http://www.onvif.org/ver10/device/wsdl\"" // not trt
    //                soap.setValue("All", forKey: "wsdl:Category")
    //                soap.setValue("All", forKey: "trt:Category")
                // See if we need to make this HTTPS.
                let reqURLString = "http" + (inAsSSL ? "s" : "") + "://" + self.ipAddressAndPort + self._pathFor(request: inRequest)
                
                #if DEBUG
                    print("SOAP Request URL: \(reqURLString)")
                #endif

                // The first time through, we fetch any realm required for subsequent authorization.
                if nil == self._realm {
                    #if DEBUG
                        print("Requesting SOAP Authorization Realm")
                    #endif
                    self._realm = _RealmRetriever().realm(for: reqURLString)
                    #if DEBUG
                        print("Received SOAP Authorization Realm: \(String(describing: self._realm))")
                    #endif
                }
                
                soap.responseHeader = true  // If this is not set, you will get an empty dictionary.
                soap.retrievesAttributes = inRequest.retrieveAttributes

                // Realm, we must have.
                if nil != self._realm {
                    soap.realm = self._realm
                    
                    // Set up the parameters for the SOAP call.
                    if let params = inRequest.params {
                        #if DEBUG
                            print("SOAP Request Parameters: \(params)")
                        #endif
                        soap.setValuesForKeys(params)
                    }
                    
                    // Get the action as a String, so we can dispatch properly in our callback.
                    let requestAction = inRequest.soapAction

                    // This is the actual SOAPEngine request. We ask for a parsed Dictionary in response.
                    soap.requestURL(reqURLString, soapAction: requestAction)
                } else {
                    #if DEBUG
                        print("SOAP Realm Error: nil realm!")
                    #endif
                    DispatchQueue.main.async {
                        self._errorCallback(.droppedTheSoapError_nil_realm, soapRequest: "", soapEngine: soap)
                    }
                }
            }
        }
    }

**Comment by RiftValleySoftware** [comment]
Whoops. I think I may see my problem...

**Comment by RiftValleySoftware** [comment]
OK. It was my bad. I used copy-and-paste from another project.

I apologize deeply for wasting your time.

**Comment by RiftValleySoftware** [comment]
For the record, the problem was this line:

            soap.retrievesAttributes = inRequest.retrieveAttributes

It came after my first setting. It was a leftover from the ONVIFCamera example, and I failed to double-check it.

**Comment by priore** [comment]
we are here for support, if you need help again, don't hesitate to contact us.
