### ISSUE TITLE
QUESTION: Best Way to Insert Mock Data

### ISSUE THREAD

**Issue by RiftValleySoftware** [priore/SOAPEngine#191]
Now that I am moved over to using the delegate for everything (which is the proper way, but I copied from a "quick n' dirty" lash-up), I am looking at the best way to do mock data for testing. It's an open standard, and the devices that I am using for testing do not touch all the points.

I am thinking of using a loopback IPv4 address (127.0.0.1:80), and using the `soapEngine(_ soapEngine: SOAPEngine!, didBeforeSending: NSMutableURLRequest!) -> NSMutableURLRequest!` method to analyze outgoing requests, and the `soapEngine(_ inSOAPEngine: SOAPEngine!, didBeforeParsingResponseData: Data!) -> Data!` method to add mock data.

Is this the way that you think I should do it?

Thanks!

**Comment by priore** [comment]
Yes with the delegate `didBeforeParsingResponseData` you can replace or integrate the received data, you can also use a better and faster XML parser, as shown in this [wiki](https://github.com/priore/SOAPEngine/wiki/Improve-the-performance-(Swift)).

**Comment by RiftValleySoftware** [comment]
Thanks!

**Comment by priore** [comment]
there should not are problems with a loopback.
