### ISSUE TITLE
QUESTION: How Do I Get Arrays To Correlate Properly?

### ISSUE THREAD

**Issue by LittleGreenViper** [priore/SOAPEngine#192]
Very Simply, I am sending in this set of parameters (Swift):
```swift
    let params: [String: Any] = ["trt:FromDHCP": "false", "trt:SearchDomain": "", "trt:DNSManual": [["tt:Type": "IPv4", "tt:IPv4Address": "8.8.8.8"], ["tt:Type": "IPv4", "tt:IPv4Address": "1.1.1.1"]]]
    soap.setValuesForKeys(params)
```
I expect them to deliver XML like this (Correct):
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:trt="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema">
        <soap:Header/>
        <soap:Body>
            <trt:SetDNS>
                <trt:SearchDomain/>
                <trt:FromDHCP>false</trt:FromDHCP>
                <trt:DNSManual>
                    <tt:IPv4Address>8.8.8.8</tt:IPv4Address>
                    <tt:Type>IPv4</tt:Type>
                </trt:DNSManual>
                <trt:DNSManual>
                    <tt:IPv4Address>1.1.1.1</tt:IPv4Address>
                    <tt:Type>IPv4</tt:Type>
                </trt:DNSManual>
            </trt:SetDNS>
        </soap:Body>
    </soap:Envelope>
```
However, the XML looks like this:
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:trt="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema">
        <soap:Header/>
        <soap:Body>
            <trt:SetDNS>
                <trt:SearchDomain/>
                <trt:FromDHCP>false</trt:FromDHCP>
                <trt:DNSManual>
                    <input>
                        <tt:IPv4Address>8.8.8.8</tt:IPv4Address>
                        <tt:Type>IPv4</tt:Type>
                    </input>
                    <input>
                        <tt:IPv4Address>1.1.1.1</tt:IPv4Address>
                        <tt:Type>IPv4</tt:Type>
                    </input>
                </trt:DNSManual>
            </trt:SetDNS>
        </soap:Body>
    </soap:Envelope>
```
Note that the array is in "input" elements. I need it to be in "trt:DNSManual" elements.

How do I configure either the input parameters, or SOAPEngine to make sure that I get the proper XML?

Thanks so much!

**Comment by LittleGreenViper** [comment]
I do not thing that this is the answer. I can have multiple arrays, and I need each of them to use the array name as the wrapper (For example, in SetDNS, both "trt:DNSManual" and "trt:SearchDomain" can be arrays).

// sets the default tag name, default is "input", when using setValue without key value or for array items
@property (nonatomic, strong) NSString *defaultTagName;

**Comment by LittleGreenViper** [comment]
I use  soap.setValuesForKeys(params). Maybe I should set each parameter individually, using the setValueForKey? However, I think we will still have the same issue. It should be sent as a Dictionary, but you cannot have multiple values for the same key in a Dictionary.

**Comment by LittleGreenViper** [comment]
OK. I've figured out an obnoxious, error-prone solution that I'll need to see if I can make more reliable tomorrow.

The setValue(_: forKey:) is not a standard Directory setter. It will allow multiple values for the same key, so this will actually give me what I need:

                        for param in params {
                            if let array = param.value as? [[String: String]] {
                                for element in array {
                                    soap.setValue(element, forKey: param.key)
                                }
                            } else {
                                soap.setValue(param.value, forKey: param.key)
                            }
                        }

It's a horrible hack, and is not at all flexible. Like I said, it needs to be done better.

**Comment by priore** [comment]
Hello,
sorry, it's much simpler than when you think, just set `defaultTagName` to nil.

**Comment by LittleGreenViper** [comment]
Cool! That's exactly what I wanted to hear!

Thanks!

**Comment by LittleGreenViper** [comment]
I am sorry. This does not work. It gives me this:

    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:trt="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema">
	<soap:Header/>
	<soap:Body>
		<trt:SetDNS>
			<trt:DNSManual>
				<tt:IPv4Address>8.8.8.8</tt:IPv4Address>
				<tt:Type>IPv4</tt:Type>
				<tt:IPv4Address>1.1.1.1</tt:IPv4Address>
				<tt:Type>IPv4</tt:Type>
				<tt:IPv4Address>8.8.4.4</tt:IPv4Address>
				<tt:Type>IPv4</tt:Type>
			</trt:DNSManual>
			<trt:SearchDomain>
				<string>google.com</string>
				<string>yahoo.com</string>
			</trt:SearchDomain>
			<trt:FromDHCP>false</trt:FromDHCP>
		</trt:SetDNS>
	</soap:Body>
    </soap:Envelope>

I need to have the DNS entries separated by </trt:DNSManual><trt:DNSManual>

**Comment by LittleGreenViper** [comment]
This is the hack that I am using. It works, but only if the parameters are at the top level. It does not recurse:

                        for param in params {
                            if let array = param.value as? [Any] {
                                for element in array {
                                    soap.setValue(element, forKey: param.key)
                                }
                            } else {
                                soap.setValue(param.value, forKey: param.key)
                            }
                        }

**Comment by priore** [comment]
Sorry I reading wrong your necessity.

Is necessary to understand the SOAP XML messages, in the MS standard a repeated key is considered an array by the receiving service, then to repeat the `DNSManual` key it is necessary to create a DNSManual array like below:


```swift
let params: [[String: Any]] = [
         ["trt:FromDHCP": "false"],
         ["trt:SearchDomain": ""],
         ["trt:DNSManual":["trt:Type": "IPv4", "trt:IPv4Address": "8.8.8.8"]],
         ["trt:DNSManual":["trt:Type": "IPv4", "trt:IPv4Address": "1.1.1.1"]]]
soap.setValue(params)
```


I know this is strange, but SOAP is somewhat complicated in its nature :unamused: and also if in the previous way that you used is more intuitive, from SOAP are considered valid also those but used differently.

Not for nothing but JSON services are preferred from all :wink:

**Comment by LittleGreenViper** [comment]
Got it. I will try that out. Thanks!

I agree about JSON. I use that for all my own work.

However, ONVIF is completely SOAP-based.

https://onvif.org
