### ISSUE TITLE
Can I Set The Content-Type and Accept Headers Manually?

### ISSUE THREAD

**Issue by RiftValleySoftware** [priore/SOAPEngine#195]
I am encountering strange SOAP problems with a device (I am writing device interface software).

It seems to be reacting badly to the headers that SOAPEngine is sending.
When I make a digest-authorized call, the Content-Type header is:

text/xml; charset=utf-8; action="trt:GetDeviceInformation"

The device throws a 500 on that.

When I use a manual REST client, the header is:

application/x-www-form-urlencoded

I tried setting the soap.header field, but it still sends the same header.

Additionally, another difference is the accept header for the manual client is \*/\*

Can I set that?

**Comment by RiftValleySoftware** [comment]
\*/\*

**Comment by priore** [comment]
Hello,
if you want to view or edit the request headers, please read https://github.com/priore/SOAPEngine/issues/85

For other digest auth infos, please read https://github.com/priore/SOAPEngine/issues/180

thanks

**Comment by RiftValleySoftware** [comment]
Excellent! Very sensible way of doing it. #180 is directly relevant to my work. Thanks!

**Comment by RiftValleySoftware** [comment]
OK. It's not the headers.

It's the authorization stuff.

Here's what the camera expects:


Digest Authentication |  
-- | --
username | admin
realm | Authentication Login
nonce | aa5f0082366c9cf1
uri | /onvif/device_service
response | 1a392dd4c29ef58200bf9d99595440b4
opaque |  
algorithm | MD5
cnonce | 0a3e46e1f14a8cbb17b0aef5fa058335
nc | 00000002
qop | auth

Here's what the app gives:

Digest Authentication |  
-- | --
username | admin
realm | Authentication Login
nonce | aa5f0082366c9cf1
uri | /onvif/device_service
response | 1a392dd4c29ef58200bf9d99595440b4

Apparently, if the camera doesn't get ALL of that junk after "request" (I have tried removing certain ones), it throws a fit, and 500s.

Yeah, the camera's firmware is obviously...not the best, but it's a major brand, and I need to make it work with that brand.

How do I fill out the rest of the authorization fields?

**Comment by RiftValleySoftware** [comment]
Actually, before you answer, let me spend some time working on the before callback...

**Comment by RiftValleySoftware** [comment]
OK. I am closing this for now. It looks like the error is -sort of- my fault.

I have not been sending correct authentication to any of the cameras, but most have accepted it.

This camera is being stubborn, so I need to send everything.

I see that Apple says not to mess with the authentication stuff in their requests, but I can't believe that I can't put this info there, so I will try that out.

The camera shouldn't throw a 500 for that, but it won't, if I send it the correct data.

I am closing this, for now. Thanks!

**Comment by RiftValleySoftware** [comment]
Just FYI There are still issues with the way that SOAPEngine is responding to thei one manufacturer's camera, but I have not yet established a way to reproduce it.

I wouldn't mind finding out if there is some way for me to replace the authentication challenge in SOAPEngine with my own.

**Comment by RiftValleySoftware** [comment]
OK. I am reopening this issue. It **MAY** be SOAPEngine has a bug, but I am very much open to a workaround or fix that I can do.

I spent most of yesterday analyzing the difference between two cameras: an AXIS unit and a Pelco unit.

They are both high-end *($$$)* cameras, with better-than-average *(which isn't saying much)* firmware.

When SOAPEngine challenges, it uses the same query:

    POST /onvif/device_service HTTP/1.1
    Host: 192.168.4.18:80
    Content-Type: application/x-www-form-urlencoded
    Accept: */*
    User-Agent: RVS_ONVIF%20Test%20Harness/1 CFNetwork/978.0.7 Darwin/18.5.0
    Accept-Language: en-us
    Accept-Encoding: gzip, deflate
    Content-Length: 323
    Connection: keep-alive

    <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"  xmlns:trt="http://www.onvif.org/ver10/device/wsdl"><soap:Body><trt:GetDeviceInformation/></soap:Body></soap:Envelope>

The AXIS responds this way:

    HTTP/1.1 401 Unauthorized
    Date: Thu, 11 Apr 2019 10:38:01 GMT
    Server: Apache/2.4.35 (Unix) OpenSSL/1.0.2p
    WWW-Authenticate: Digest realm="AXIS_WS_ACCC8EBECCEA", nonce="ctbOxz6GBQA=a4acd06191c3e3e24c8829dc6521670e7e12350e", algorithm=MD5, qop="auth"
    Content-Type: text/xml; charset=utf-8
    Content-Length: 0
    Keep-Alive: timeout=5, max=100
    Proxy-Connection: keep-alive

The Pelco responds this way:

    HTTP/1.1 401 Unauthorized
    Cache-Control: private, must-revalidate, proxy-revalidate
    Content-Security-Policy: Frame-src 'self'
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: 1; mode=block
    WWW-Authenticate: Digest realm="Authentication Login", domain="Authentication Login", qop="auth", nonce="6a8c4c2dda4b18ebe3d761fe70ca83b6", opaque="", algorithm="MD5", stale="FALSE"
    Server: gSOAP/2.8
    Content-Type: application/soap+xml; charset=utf-8
    Content-Length: 2301
    Date: Thu, 11 Apr 2019 10:38:44 GMT
    Proxy-Connection: keep-alive

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsrf-bf2="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-1" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-1" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsrf-r2="http://docs.oasis-open.org/wsrf/r-2" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tr2="http://www.onvif.org/ver20/media/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:timg1="http://www.onvif.org/ver10/imaging/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"><SOAP-ENV:Body><SOAP-ENV:Fault SOAP-ENV:encodingStyle="http://www.w3.org/2003/05/soap-encoding"><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value><SOAP-ENV:Subcode><SOAP-ENV:Value>ter:NotAuthorized</SOAP-ENV:Value></SOAP-ENV:Subcode></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">The requested action requires authorization</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Node id="_7">http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver</SOAP-ENV:Node><SOAP-ENV:Role SOAP-ENC:ref="_7"/></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

The next valid request (with digest) that SOAPEngine creates is:

AXIS (valid):

    POST /onvif/device_service HTTP/1.1
    Host: 192.168.4.12:80
    Content-Type: text/xml; charset=utf-8; action="trt:GetDeviceInformation"
    Accept-Encoding: gzip, deflate
    SOAPAction: "trt:GetDeviceInformation"
    Accept: text/xml; charset=utf-8
    User-Agent: SOAPEngine
    Content-Length: 376
    Authorization: Digest username="root", realm="AXIS_WS_ACCC8EBECCEA", nonce="HWMoyD6GBQA=9f10f9231b9f13ede7221d902963c62a2f28194b", uri="/onvif/device_service", response="9233d7ff92e33d62414ace939bded8d5", algorithm="MD5", cnonce="e0e0efac42bf67642b4904c893b46725", nc=00000001, qop="auth"
    Accept-Language: en-us
    Connection: keep-alive

    <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"  xmlns:trt="http://www.onvif.org/ver10/device/wsdl"><soap:Header></soap:Header><soap:Body><trt:GetDeviceInformation></trt:GetDeviceInformation></soap:Body></soap:Envelope>

Pelco (Error):

    POST /onvif/device_service HTTP/1.1
    Host: 192.168.4.18:80
    Content-Type: text/xml; charset=utf-8; action="trt:GetDeviceInformation"
    Accept-Encoding: gzip, deflate
    SOAPAction: "trt:GetDeviceInformation"
    Accept: text/xml; charset=utf-8
    User-Agent: SOAPEngine
    Content-Length: 376
    Authorization: Digest username="admin",realm="Authentication Login",nonce="99b601a4bf11aaef",uri="/onvif/device_service",response="62d7a6a4638d894dd5013fd35b826a2c"
    Accept-Language: en-us
    Connection: keep-alive

    <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope"  xmlns:trt="http://www.onvif.org/ver10/device/wsdl"><soap:Header></soap:Header><soap:Body><trt:GetDeviceInformation></trt:GetDeviceInformation></soap:Body></soap:Envelope>

Notice the difference in the `Authorization:` header. SOAPEngine truncates the header. This causes the camera to *(improperly)* throw a 500.

Is this something that I can fix on my end? I did try to build my own auth header, but it looks like that cannot be done with SOAPEngine.

**Comment by RiftValleySoftware** [comment]
Actually, I should make one correction:

SOAPEngine does not make the challenge; I do.

However, there is only one property of SOAPEngine that I can set from the results: realm (and username/login).

Are there any more properties I can set? I have collected every response in the auth header.

**Comment by RiftValleySoftware** [comment]
Is this how I can build my own auth header?

SOAP_AUTH_CUSTOM

If so, do I just provide that in .header in the "before" callback?

**Comment by RiftValleySoftware** [comment]
OK. Looks like I got it by building my own header, and using .AUTH_CUSTOM.

I need to do a lot more testing to be sure, but looks good so far.

If you want me to post my solution, I can, but it will be in Swift.

**Comment by RiftValleySoftware** [comment]
OK. Looks like I got it by building my own header, and using .AUTH_CUSTOM.

I need to do a lot more testing to be sure, but looks good so far.

If you want me to post my solution, I can, but it will be in Swift.

**Comment by RiftValleySoftware** [comment]
OK. Looks like I got it by building my own header, and using `.AUTH_CUSTOM`.

I need to do a lot more testing to be sure, but looks good so far.

If you want me to post my solution, I can, but it will be in Swift.

**Comment by RiftValleySoftware** [comment]
Looks like I got it going, using `.AUTH_CUSTOM`.

The Pelco is a strange camera, and I'll need to figure out more stuff but I can at least talk to it, now.

I need to test the solution (I built my own Digest header from scratch), to make sure I didn't mess up any other cameras.

If you are interested, I can post my (Swift) solution.

**Comment by RiftValleySoftware** [comment]
...not so fast. I still need to figure out other issues, but I think I have worked through the SOAPEngine issue.

**Comment by priore** [comment]
Hello,
if you post the solution, I think it could help many other programmers with your same problem. From our, we also evolve SOAPEngine for this specific use, since it is our philosophy, to accept advice and implementations on how to improve SOAPEngine and for your commitment we can refund you the money from your license, or give you a new license single or enterprise that you prefer.

**Comment by RiftValleySoftware** [comment]
Oh, I wouldn't dream of a refund. Your library has been great. It saved me months of work.

It would be difficult for you to debug this. The camera is pretty expensive. I can send you Charles Proxy dumps, if you think that will help.

Here is the solution that I found:

I use this String extension. In order to use it, you must add `#import <CommonCrypto/CommonCrypto.h>` to your bridging header:

/* ###################################################################################################################################### */
/**
 From here: https://stackoverflow.com/q/24123518/879365
 I am not making this public, because it requies the common crypto in the bridging header.
 */
fileprivate extension String {
    /* ################################################################## */
    /**
     - returns: the String, as an MD5 hash.
     */
    var md5: String! {
        let str = self.cString(using: String.Encoding.utf8)
        let strLen = CUnsignedInt(self.lengthOfBytes(using: String.Encoding.utf8))
        let digestLen = Int(CC_MD5_DIGEST_LENGTH)
        let result = UnsafeMutablePointer<CUnsignedChar>.allocate(capacity: digestLen)
        CC_MD5(str!, strLen, result)
        
        let hash = NSMutableString()
        
        for i in 0..<digestLen {
            hash.appendFormat("%02x", result[i])
        }
        
        result.deallocate()
        return String(format: hash as String)
    }
}

I declare a couple of internal stored properties:

    /* ################################################################## */
    /**
     This is the authentication realm and other stuff.
     */
    internal var _authData: [String: String]?
    
    /* ################################################################## */
    /**
     This tracks the number of times a nonce has been created.
     */
    internal var _nonceCount: Int = 0

First, I send a basic GetDeviceInfo query, and get a 401 response. I then pull the variables from the www-authenticate header:

    // Upon return, we should have a response that can be parsed. We ignore errors, if the header is there.
    if let httpStatus = inResponse as? HTTPURLResponse, httpStatus.statusCode == 401, let authenticateHeader = httpStatus.allHeaderFields["Www-Authenticate"] as? String {
        // Get the realm and other params from the authentication challenge.
        let params = self._extractAuthenticateParams(authenticateHeader: authenticateHeader)
        self._authCred["realm"] = params["realm"]
        self._authCred["nonce"] = params["nonce"]
        self._authCred["qop"] = params["qop"]
        self._authCred["opaque"] = params["opaque"]
        self._authCred["algorithm"] = params["algorithm"]
        self._authCred["stale"] = params["stale"]
        self._authCred["method"] = "POST"
        self._authCred["uri"] = url.relativePath
    }

I set `.Auth_CUSTOM` as the method:

        soap.authorizationMethod = .AUTH_CUSTOM

I get the authorization stuff from my challenge, and add the username and password:

        // Get the result of a Digest challenge.
        _authData = _AuthorizationSetup().authCreds(for: reqURLString)
        _authData?["username"] = self.loginCredentials?.login ?? ""     // Add the username, so we have it all in one place.
        _authData?["password"] = self.loginCredentials?.password ?? ""  // Add the password, so we have it all in one place.

This is the "before sending" callback:

    /* ################################################################## */
    /**
     This may be called in non-main threads.
     
     This is called before sending out a request. It has the request formed by SOAPEngine.
     
     - parameter inSOAPEngine: The SOAPEngine instance calling this method. It may be nil.
     - parameter didBeforeSending: This is a URL Request that will be sent. You can modify this.
     - returns a Data object. It should be the inData parameter, unchanged.
     */
    public func soapEngine(_ soapEngine: SOAPEngine!, didBeforeSending inRequest: NSMutableURLRequest!) -> NSMutableURLRequest! {
        #if DEBUG
            print("didBeforeSending: \(String(describing: inRequest))")
        #endif
        // Build an RFC2617 authentication header (https://tools.ietf.org/html/rfc2617)
        if .AUTH_CUSTOM == soapEngine.authorizationMethod, let username = _authData?["username"], let realm = _authData?["realm"], let password = _authData?["password"], let uri = _authData?["uri"], let method = _authData?["method"], let nonce = _authData?["nonce"], let qop = _authData?["qop"], let body = String(data: inRequest.httpBody ?? Data(), encoding: .utf8) {
            let cnonce = NSUUID().uuidString.replacingOccurrences(of: "-", with: "")
            guard var ha1: String = "\(username):\(realm):\(password)".md5 else { return nil }
            guard var ha2: String = "\(method):\(uri)".md5 else { return nil }
            var response = ""
            var extra = ""
            
            if let opaque = _authData?["opaque"] {
                extra = ", opaque=\"\(opaque)\""
            }
            
            if "MD5-sess" == method {
                ha1 = (ha1 + ":\(nonce):\(cnonce)").md5
            }
            
            switch qop {
            case "auth-int":
                ha2 = ("\(method):\(uri):" + body.md5).md5
                fallthrough
                
            case "auth":
                response = "\(ha1):\(nonce):\(String(_nonceCount)):\(cnonce):\(qop):\(ha2)".md5
                _nonceCount += 1
                
            default:
                response = "\(ha1):\(nonce):\(ha2)".md5
            }
            
            let authenticationHeader = "Digest response=\"\(response)\", nonce=\"\(nonce)\", method=\"\(method)\", username=\"\(username)\", uri=\"\(uri)\", qop=\"\(qop)\", cnonce=\"\(cnonce)\"" + extra
            
            soapEngine.header = authenticationHeader
        }
        
        return inRequest
    }
