### ISSUE TITLE
QUESTION: Can I Completely Interrupt Network Communication for Testing?

### ISSUE THREAD

**Issue by ChrisMarshallNY** [priore/SOAPEngine#199]
Hi, this is the same person as LittleGreenViper. I have changed my original ID to an organization, and am using a personal GH ID.

I am in the process of implementing a set of unit tests for my SOAPEngine implementation (an ONVIF driver for Cocoa), and need to implement a mock system for testing.

I have created a base class for my testing, which implements SOAPEngineDelegate, and has the following two methods:

    /* ################################################################## */
    /**
     This may be called in non-main threads.
     
     This is called before sending out a request. It has the request formed by SOAPEngine.
     
     - parameter inSOAPEngine: The SOAPEngine instance calling this method. It may be nil.
     - parameter didBeforeSending: This is a URL Request that will be sent. You can modify this.
     - returns the NSURLRequest object.
     */
    /// Override, because we are actually replacing a base class implementation.
    override public func soapEngine(_ soapEngine: SOAPEngine!, didBeforeSending inRequest: NSMutableURLRequest!) -> NSMutableURLRequest! {
        print("didBeforeSending: \(String(describing: inRequest))")
        
        return inRequest
    }
    
    /* ################################################################## */
    /**
     This may be called in non-main threads.
     
     This is called before the data is sent into the parser.
     
     - parameter inSOAPEngine: The SOAPEngine instance calling this method. It may be nil.
     - parameter didBeforeParsingResponseData: The data that will be parsed. You can modify this.
     - returns a Data object. It should be the inData parameter, unchanged.
     */
    public func soapEngine(_ inSOAPEngine: SOAPEngine!, didBeforeParsingResponseData inData: Data!) -> Data! {
        print("didBeforeParsingResponseData: \(String(describing: inData))")
        
        return inData
    }

It is my intention to completely intercept all communications via SOAPEngine this way, extracting sending data from the test subject in didBeforeSending, and returning mock data in didBeforeParsingResponseData.

I already know that I can completely replace data returned to the test subject in didBeforeParsingResponseData, but I want to ask if I return nil in didBeforeSending, if that will stop the communication.

I want to create an invalid IP address and port, and ignore authentication in my tests.

Will this work?

I am doing this, because I want to test as much of the stack as possible; including SOAPEngine. If I cannot do this, then I will have to bypass SOAPEngine in my tests.

**Comment by ChrisMarshallNY** [comment]
Another possibility is to implement `didBeforeParsingResponseString`, and insert pure XML.

That may be better for testing, as I suspect that it exercises a lot more of the stack, and will make it easier for me to sample mock data.

However, the question still stands: I will not have a device, so I will not be able to actually establish an NSURLSession. What is the best way for me to use the delegate function to interrupt a session.

Also, I just noticed. I see that SOAPEngine.h has `didBeforeSendingURLRequest`, not `didBeforeSending`, but the method still works.

**Comment by priore** [comment]
Hello,
I'm not sure what you want to get, but if you return nil from `didBeforeSendingURLRequest`"or from `didBeforeParsingResponseData` the processing stops, in `didBeforeSendingURLRequest` the network request will be interrupted.

Some delegates have been maintained for compatibility with previous versions, but they are deprecated even if they remain functional.

**Comment by ChrisMarshallNY** [comment]
That sounds like what I want.

Thanks!
