### ISSUE TITLE
Under ws-security mode, SOAPEngine treats local datetime as GMT datetime

### ISSUE THREAD

**Issue by coinicon72** [priore/SOAPEngine#20]
Hi, I got a problem and need your help.

I'm using ws-security in my soap request, but server always returns a error: "The message has expired". Turns out that SOAPEngine treats local datetime as GMT datetime.

my code likes:
	SOAPEngine *soap = [[SOAPEngine alloc] init];
	soap.userAgent = @"SOAPEngine";
	soap.version = VERSION_1_1; // WCF service (.svc)
	soap.authorizationMethod = SOAP_AUTH_WSSECURITY;
	soap.username = @"test@test.com";
	soap.password = @"1234";

here is the segment from request payload:

<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>test@test.com</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">ODZiMDE4ZmQ2NDQ5NTRlODYxNmQwMjBmYThjNDMwNzgwMzk4ZGY2NA==</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">RDIyRkRDM0Y2REE0NEEyREFGQkI1REFFRDUwOTMyRTA=</wsse:Nonce><wsu:Created>2015-01-12T18:57:20Z</wsu:Created></wsse:UsernameToken></wsse:Security>

I'm in timezone +8, and the time is 2015-01-12T18:57:20, but you can see the <wsu:Created>2015-01-12T18:57:20Z</wsu:Created> says this is a GMT datetime.

So, could you please tell me what I can do to fix this? thank you so much.

**Comment by priore** [comment]
f0961a79b8d85ba5419ac11d48beb456b2e6204a

**Comment by coinicon72** [comment]
Thanks, @priore .

Nice works, the timestamp issue fixed.

However, I found another issue about password digest which has been logged as issue #22.

Thank you so much.
