### ISSUE TITLE
QUESTION: Calling SOAPEngine With Localhost IP Does Not Work

### ISSUE THREAD

**Issue by ChrisMarshallNY** [priore/SOAPEngine#201]
I am trying to set up a test, where I can call SOAPEngine with a dummy IP (127.0.0.1:80), and have it work, so that I can intercept it and inject my own  XML (test mock).

Here is my main class declaration:

    @objc public class RVS_ONVIF: NSObject, SOAPEngineDelegate {

It works fine when used "live" (connected to a network and cameras).

Here is the code I use to initialize SOAPEngine:

        let soap = SOAPEngine() // We initialize a new SOAPEngine for each call.
        soap.retrievesAttributes = inRequest.isRetrieveAttributes
        soap.delegate = self    // We allow interception of delegate calls.
        soap.licenseKey = self._soapEngineLicenseKey    // So we can work on devices.
        soap.version = .VERSION_1_2
        soap.authorizationMethod = .AUTH_CUSTOM
        soap.envelope = "xmlns:trt=\"http://www.onvif.org/ver10/device/wsdl\""
        soap.username = "test"
        soap.password = "test"
        soap.responseHeader = true  // If this is not set, you will get an empty dictionary.

I have set up a class that conforms to SOAPEngineDelegate, and implements the following methods:

    override internal func _soapEngine(_ soapEngine: SOAPEngine!, didBeforeSendingURLRequest inRequest: NSMutableURLRequest!) -> NSMutableURLRequest! {
        print("didBeforeSendingURLRequest: \(String(describing: inRequest))")
        
        return nil
    }
    
    public func soapEngine(_ inSOAPEngine: SOAPEngine!, didBeforeParsingResponseData inData: Data!) -> Data! {
        print("didBeforeParsingResponseData: \(String(describing: inData))")
        
        return inData
    }
    
    public func soapEngine(_ inSOAPEngine: SOAPEngine!, didReceiveDataSize inCurrent: NSNumber!, total inTotal: NSNumber!) {
        print("didReceiveDataSize: \(String(describing: inCurrent)), total: \(String(describing: inTotal))")
    }
    
    public func soapEngine(_ inSOAPEngine: SOAPEngine!, didSendDataSize inCurrent: NSNumber!, total inTotal: NSNumber!) {
        print("didReceiveDataSize: \(String(describing: inCurrent)), total: \(String(describing: inTotal))")
    }
    
    public func soapEngine(_ inSOAPEngine: SOAPEngine!, didReceiveResponseCode inStatusCode: NSNumber!) -> Bool {
        print("didReceiveResponseCode: \(String(describing: inStatusCode))")
        
        return false
    }

The reason for the underscore (_) in the first one, is because I cannot override `didBeforeSendingURLRequest`. If I try, I get "Overriding non-@objc declarations from extensions is not supported". My test class is a subclass of the main one, which is a SOAPEngineDelegate (and NSObject child).

Here is the declaration of the base class callback:

    public func soapEngine(_ soapEngine: SOAPEngine!, didBeforeSendingURLRequest inRequest: NSMutableURLRequest!) -> NSMutableURLRequest! {
        #if DEBUG
            print("didBeforeSendingURLRequest: \(String(describing: inRequest))")
            if _testingSetup {
                print("Testing Setup -Communication Will be Interrupted.")
            }
        #endif
        // If we are testing,
        if _testingSetup {
            return _soapEngine(soapEngine, didBeforeSendingURLRequest: inRequest)
        } else {
        // Bunch of stuff goes on here if we are running valid.
        }
        return inRequest
    }

In any case, if I call the SOAPEngine instance after init:

    soap.requestURL("http://127.0.0.1:80/onvif/device_service", soapAction: "trt:GetDeviceInformation")

None of the callbacks get called.

Am I doing something wrong?

**Comment by ChrisMarshallNY** [comment]
I would really like to get this working. The ability to directly inject XML would be powerful.

**Comment by ChrisMarshallNY** [comment]
OK. I think I got it. It is my fault.
I was doing this using XCTest, and I forgot to use expectations.
I will close this issue.

**Comment by ChrisMarshallNY** [comment]
However, I need to reopen the issue.

This is because I cannot seem to use a dummy (invalid) IP address.

Is there a way for me to use an invalid IP address, and still have SOAPEngine work?

**Comment by ChrisMarshallNY** [comment]
If I can't use SOAPEngine, then it is not the end of the world, but it does mean that my tests will not run on the lowest-level portion of the stack, and I won't be able to test some exotic error conditions.

**Comment by priore** [comment]
Hello,
SOAPEngine works well with any ip or domain address, even the localhost we use frequently to test the changes we make of framework, maybe you can try without port specification (:80), this is the only difference with us.

**Comment by ChrisMarshallNY** [comment]
It does not work.
If I give it 127.0.0.1 (with or without :80), I get the following error:
`Optional(Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7f9af0553600 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=http://127.0.0.1/onvif/device_service, NSErrorFailingURLKey=http://127.0.0.1/onvif/device_service, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, NSErrorFailingURLStringKey=http://127.0.0.1/onvif/device_service, NSErrorFailingURLKey=http://127.0.0.1/onvif/device_service, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.})`.

I need to get past this error, so that I can get to the place where I can inject or read mock data.

**Comment by ChrisMarshallNY** [comment]
This happens, even if I force the URI to be simple:
`Optional(Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7f9a4092ff60 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=http://127.0.0.1/, NSErrorFailingURLKey=http://127.0.0.1/, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, NSErrorFailingURLStringKey=http://127.0.0.1/, NSErrorFailingURLKey=http://127.0.0.1/, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.})`

**Comment by ChrisMarshallNY** [comment]
I do not see any way to specify a loopback.

**Comment by priore** [comment]
On what device are you running this? Simulator or an real device?

If you use a real device and the computer are on the same wifi, then all you need is to get the computer local ip address and change localhost with that ip address.

**Comment by ChrisMarshallNY** [comment]
Simulator.

**Comment by ChrisMarshallNY** [comment]
I can share the code (it is eventually destined to become open-source), but it is not-so-small a project.

**Comment by priore** [comment]
You have set NSAppTransportSecurity in info.plist of your app ?

**Comment by ChrisMarshallNY** [comment]
Let me check...

**Comment by ChrisMarshallNY** [comment]
No. It is set in the test harness apps, but this is the framework. Let me try that.

**Comment by ChrisMarshallNY** [comment]
No. Same thing happens. I should mention that this is happening in XCTest, not a standard runtime.

**Comment by ChrisMarshallNY** [comment]
There may be one more place I can try...

**Comment by ChrisMarshallNY** [comment]
No. Nothing. I get a socket error. Here is what is reported in the error callback:

`Optional(Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7fad87e3e2a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=http://127.0.0.1/onvif/device_service, NSErrorFailingURLKey=http://127.0.0.1/onvif/device_service, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, NSErrorFailingURLStringKey=http://127.0.0.1/onvif/device_service, NSErrorFailingURLKey=http://127.0.0.1/onvif/device_service, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.})`

However, before that, the console reports:

`<RVS_ONVIF_iOS_Tests.RVS_ONVIF_TestTarget: 0x7fa459e30000>
2019-06-26 07:33:38.334134-0400 xctest[17333:2139561] [] nw_socket_handle_socket_event [C1:2] Socket SO_ERROR [61: Connection refused]
2019-06-26 07:33:38.334503-0400 xctest[17333:2139561] TIC TCP Conn Failed [1:0x7fa45c97f920]: 1:61 Err(61)
2019-06-26 07:33:38.335516-0400 xctest[17333:2139561] Task <8BE1913A-714A-4C0C-99D9-8A3F3EBEF059>.<0> HTTP load failed (error code: -1004 [1:61])
2019-06-26 07:33:38.335684-0400 xctest[17333:2139563] NSURLConnection finished with error - code -1004
2019-06-26 07:33:38.337584-0400 xctest[17333:2139470] SOAPEngine connection fail! - Could not connect to the server. http://127.0.0.1/onvif/device_service`

**Comment by priore** [comment]
SOAPEngine still uses NSURLConnection, which in the latest versions of iOS has been supplanted by NSURLSession, but it is the internal iOS socket that generates the error, not the library, obviously the internal url is not reachable, have you tried anyway to disable the firewall?

**Comment by ChrisMarshallNY** [comment]
The firewall is off (at least at the System Preferences level).

Like I said, I don't want to waste too much of your time on this. I will simply bypass SOAPEngine for the XCTests.

However, I would like to know which XML parser you use, so I can reproduce it with my test harness.

**Comment by ChrisMarshallNY** [comment]
I see that you include libXML2. I assume that you use the C interface to it?

**Comment by ChrisMarshallNY** [comment]
Nevermind. I will use the Foundation parser (even though it is slower), and build my own Dictionary. Since this is a test, I want as little extra code in there as possible.

Thanks so much for everything! I will close the issue.
