### ISSUE TITLE
Cannot call value of non-function type 'URL?' for SOAPEngine.requestURL

### ISSUE THREAD

**Issue by Shuriken97** [priore/SOAPEngine#202]
I followed the implementation method including creating header.h and install obj-c bridging header but I still received "Cannot call value of non-function type 'URL?'" error.

        'let soap = SOAPEngine()
        soap.actionNamespaceSlash = true
        soap.setValue("30", forKey: "Celsius")
        soap.requestURL("http://www.w3schools.com/webservices/tempconvert.asmx",
                        soapAction: "http://www.w3schools.com/webservices/CelsiusToFahrenheit",
                        completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                            
                            //let result:Dictionary = dict as Dictionary
                            NSLog("%f", soap.floatValue());
                            
        }, failWithError: { (error : NSError!) -> Void in
            NSLog("%@", error)
        })'

**Comment by priore** [comment]
please read #126
