### ISSUE TITLE
How to pass authentication header in soap using Swift

### ISSUE THREAD

**Issue by Shuriken97** [priore/SOAPEngine#203]
I want to ask how to supply username and password for asmx soap web service in Swift 4.0

**Comment by priore** [comment]
Hi,
please read this settings for [SOAP Authentication](http://www.whitemesa.com/soapauth.html)


```swift
soap.authorizationMethod = .AUTH_BASIC // depends of your soap service
soap.username = "mysusername"
soap.password = "mypassword"
```
