### ISSUE TITLE
Need help in parsing base64 encoded string in the response

### ISSUE THREAD

**Issue by malleswarikk** [priore/SOAPEngine#205]
Hi,

One of my SOAP web services returns a base64 encoded string in the response as 

```xml
<?xml` version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SOAP-ENV:Body>
        <ProductResponse>
            <searchProductResponse xsi:type="xsd:string">YmFzZTY0IGRlY29kZXI=</searchProductResponse >
        </ns1: ProductResponse >
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

I'm using the below function and it's returning empty dictionary. How should it be handled?

```objective-c
- (void)requestURL:(id)asmxURL
        soapAction:(NSString *)soapAction
completeWithDictionary:(SOAPEngineCompleteBlockWithDictionary)complete
     failWithError:(SOAPEngineFailBlock)fail;
```

Thanks in advance.

**Comment by priore** [comment]
Hello,
please read this [response](https://github.com/priore/SOAPEngine/issues/197#issuecomment-489612887)

Many thanks.

**Comment by malleswarikk** [comment]
Thanks for the response. But the referred issue is different and talks about dictionary returning nil for some other reason. In my case, the response has base64 encoded string which is not getting handled by the requestURL() internally. If SoapEngine has different methods for getting the response and parsing the response then I would be able to decode the response before sending to the parser functions.

**Comment by priore** [comment]
if we understand correctly, you need already decoded base64 data, correct?

The library does not provide this, only in the case where you want to use the aes / 3des encoding, to encode / decode the data and put them in base64 format.

If you want to retrieve the string value, being one value without a specificc key, just use `soap.stringValue` method
