### ISSUE TITLE
commercial license (source code)

### ISSUE THREAD

**Issue by falkorichter** [priore/SOAPEngine#206]
Ciao!

I was wondering if you offer commercial licensing that allows us to use your libraries source code?

**Comment by priore** [comment]
Hello,
currently we don't have a commercial licensing for source code, sorry.

**Comment by falkorichter** [comment]
@priore how can I get in touch with you to discuss commercial licensing for source code?

**Comment by priore** [comment]
you can write on the support email, I will reply from my personal email as soon as they forward me the your email.

**Comment by falkorichter** [comment]
where is this support email? Can't find it :(

**Comment by priore** [comment]
I'm sorry https://github.com/Prioregroup, on top of page.
