### ISSUE TITLE
soapengine64 taken error

### ISSUE THREAD

**Issue by jakkapongz** [priore/SOAPEngine#21]
https://www.facebook.com/prioregroup/posts/10152930639306420

this error still happen, i make new ios8 application(soapengine64.framework) but if run on soapengine.framework (32bit) it work

many thanks

**Comment by jakkapongz** [comment]
error happen when create new class extens nsobject soapengine not response and crash

**Comment by priore** [comment]
from February all the new app, and updates, must be 64-bit (https://developer.apple.com/news/?id=10202014a) then you will need to use the 64 bits framework. Check that you have imported all dependencies into your new project (see here https://github.com/priore/SOAPEngine#install-in-your-apps)

**Comment by jakkapongz** [comment]
thank you very much. :)
