### ISSUE TITLE
Xcode 12 Compile Issue

### ISSUE THREAD

**Issue by mikeilardi** [priore/SOAPEngine#210]
![c2673db3-0ac3-44c6-9a3a-04ae1eb799d9](https://user-images.githubusercontent.com/5014747/93770468-38146080-fbea-11ea-8a6d-fa5aca5b9717.jpg)

After upgrading to Xcode 12 I'm not able to build and we get the error in the attached screenshot.  Is there going to be a fix for this or will support stop at Xcode 11?

**Comment by priore** [comment]
Hello,
we are using the our library with Xcode 12, on two of our projects, and no errors are reported, also trying with the example included, but maybe you may find useful to read this thread on [stackoverflow](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios)

thanks.
