### ISSUE TITLE
Delegate method didFinishLoadingWithDictionary not working

### ISSUE THREAD

**Issue by returnvoid** [priore/SOAPEngine#212]
Hi!

I was trying to implement a method after data was parsed, I tried this and it works

`func soapEngine(_ soapEngine: SOAPEngine!, didBeforeParsingResponseData data: Data!) -> Data!{}
`
But I need one after data is parsed. The one I found is not working

`func soapEngine(_ soapEngine: SOAPEngine!, didFinishLoadingWithDictionary data: Data!) -> Void{}

thnks
`

**Comment by priore** [comment]
Hi,
you have to use the `didFinishLoadingWith` delegate, like below :

```swift
func soapEngine(_ soapEngine: SOAPEngine!, didFinishLoadingWith dict: [AnyHashable : Any]!, data: Data!) {
    print(dict)
}
```

the dictionary contains the data already parsed.

thanks

**Comment by returnvoid** [comment]
Still not working. I think this:

completeWithDictionary: { (statusCode : Int, dict : [AnyHashable: Any]?) -> Void in

should be returning something? or void is ok?

thanks

**Comment by priore** [comment]
Hi,
if you are using delegates this below is an example

```swift
class ViewController: UIViewController  {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let soap = SOAPEngine()
        soap.delegate = self
        
        // try to change this values
        soap.actionNamespaceSlash = true
        soap.responseHeader = true //get full response for non-standard MS services
        
        //
        // your code here
        //
    }
}

extension ViewController: SOAPEngineDelegate {
    func soapEngine(_ soapEngine: SOAPEngine!, didFinishLoadingWith dict: [AnyHashable : Any]!, data: Data!) {
        print(dict)
    }
}

```

try to change the `actionNamespaceSlash` and the `responseHeader` values.

**Comment by returnvoid** [comment]
It did work but only if I used

`envoltorio.requestURL(url, soapAction: soapAction)`

before I was using something like

```
soap.requestURL("http://www.my-web.com/my-service.asmx",
            soapAction: "http://www.my-web.com/My-Method-name",
            completeWithDictionary: { (statusCode : Int, 
            					 dict : [AnyHashable : Any]?) -> Void in
                var result:Dictionary = dict! as Dictionary
                print(result)
            }) { (error : Error?) -> Void in
                print(error)
        }
```

**Comment by priore** [comment]
ok if you have solved it, please close this ticket.

thanks

**Comment by returnvoid** [comment]
Yeah, it works perfectly, thanks for your support ;)
