### ISSUE TITLE
"extra argument "value" in call" Warning in Swift

### ISSUE THREAD

**Issue by ponymuch** [priore/SOAPEngine#24]
Swift:  
soap.requestWSDL("http://59.77.16.52:8080/axis2/services/TestService?wsdl",
            operation: "test",
            value: "much",
            forKey: "name",
            completeWithDictionary: {(statusCode : NSInteger,idc : NSDictionary)in
                println(" ")
            },
            failWithError: {(error: NSError) in
            println(" ")})

extra argument "value" in call????
OC:
OC method : - (void)requestWSDL:(id)wsdlURL
          operation:(NSString *)operation
              value:(id)value
             forKey:(NSString*)key
completeWithDictionary:(SOAPEngineCompleteBlockWithDictionary)complete
      failWithError:(SOAPEngineFailBlock)fail;

**Comment by priore** [comment]
hello, the full correct syntax is

``` objective-c

        soap.requestWSDL("http://59.77.16.52:8080/axis2/services/TestService?wsdl",
            operation: "test",
            value: "much",
            forKey: "name",
            completeWithDictionary: { (statusCode : Int, idc : [NSObject : AnyObject]!) -> Void in
                
                println(" ")
                
            }) { (error: NSError!) -> Void in
                
                println(" ")
        }

```

**Comment by ponymuch** [comment]
that's very helpful! thanks!
