### ISSUE TITLE
MultipleRequest  but return the same value

### ISSUE THREAD

**Issue by ponymuch** [priore/SOAPEngine#25]
![f6eb4069-53d3-4614-bf77-c4fd1fa5833e](https://cloud.githubusercontent.com/assets/10826321/6019696/751f7904-abde-11e4-8ff6-8f1c47c7bd0e.png)

I just want to get the Value of (a+b).
but it appears to get some problem.

**Comment by priore** [comment]
depends greatly on the response of the server, if this responds with a standard microsoft soap or other, I suppose that's not standard, in this case I suggest you use the dictionary returned from the method and get this value through key, first also sets the property named responseHeader to true.

**Comment by ponymuch** [comment]
I need the synchronization request....

**Comment by priore** [comment]
Please, look and apply this common solution, is a very interesting article that allows to change any asynchronous process to a synchronous process using GDC

http://www.g8production.com/post/76942348764/wait-for-blocks-execution-using-a-dispatch
