### ISSUE TITLE
Call WebService on Apache CXF

### ISSUE THREAD

**Issue by Persilos** [priore/SOAPEngine#26]
Hi, i'm trying to call a webservice on Apache CXF in Swift with SOAPEngine. I dont have errors, but my dictionary is empty...
Here's the Swift code for calling my WS

        var soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true

        soap.setValue("Julien", forKey: "pwd")
        soap.setValue("Bonjour", forKey: "login")
        soap.requestWSDL("http://localhost:8080/Xqui/services/WSProject?WSDL",
            operation: "http://interfaces.webservices.project.generycs.be/test1",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                var logInfo:Dictionary = dict as Dictionary
                var nb = logInfo.count
                NSLog("%@", dict)
                
            }) { (error : NSError!) -> Void in
                NSLog("%@", error.description)
        }

Here's the java code of my WS: a simple method for test
(We must specify namespace for webparam, otherwise the call fails)

    @WebMethod
    public String test1(@WebParam(name = "login", targetNamespace =  "http://interfaces.webservices.project.generycs.be/") String login, @WebParam(name = "pwd", targetNamespace = "http://interfaces.webservices.project.generycs.be/") String pwd) throws Exception
    {

        log.debug("<<<< WsProject.test1 - start  - login = " + login);
        return login.toUpperCase() + "-" + pwd;
    }

Thanks in advance,

Julien

**Comment by priore** [comment]
Hi, try setting the property called responseHeader to true, this property is used for a not standard services (non original Microsoft) like your

**Comment by Persilos** [comment]
Thank you for your response, it works perfectly !
