### ISSUE TITLE
Asynchronous / Synchronous call

### ISSUE THREAD

**Issue by Persilos** [priore/SOAPEngine#27]
Hi ! Is there a way to make an Synchronous call with the framework ? 
Otherwise, how can i implement a callback function ?

Regards

**Comment by priore** [comment]
Hi, you can use block programming with dispatch semaphore http://www.g8production.com/post/76942348764/wait-for-blocks-execution-using-a-dispatch

**Comment by Persilos** [comment]
Thank you for this informations. My problem is solved !
