### ISSUE TITLE
Download/Upload progress

### ISSUE THREAD

**Issue by EricoGT** [priore/SOAPEngine#28]
Hello Priore, I'm using SOAPEngine and it's helping me a lot. Congrats, it's a really good job.
I have a question that actually is a request. Does SOAPEngine use NSURLConnection class to do web communication? If Yes, is it possible to get download/upload progress (via float type property)? It would be an alternative way to obtain request progress, as we do with "connection: (NSURLConnection *) connection didReceiveData: (NSData *) data" method implementing "NSURLConnectionDataDelegate"

**Comment by priore** [comment]
we implemented the download 43adf86da7219cc8793c6ba92538312cd26e67ba

**Comment by EricoGT** [comment]
In initial tests, the parameter 'total' always comes with 0 bytes ('current' shows values normally).

**Comment by priore** [comment]
yes, because in the header of response is missing the content length, soapengine needs a content-length.

**Comment by EricoGT** [comment]
In the project "SOAPEngine Sample" You can see 'current' and 'total',
although 'soap.responseHeader' is always false and 'soap.header' empty. Is
there any way to view the header of the response?

2015-02-23 9:46 GMT-03:00 Danilo Priore <notifications@github.com>:

**Comment by priore** [comment]
not in this version, we will put in the next version, while, the property named "responseHeader", allows you to recover, in the SOAP response, the full header of the SOAP message, and the property named "header" allows to customize the header for SOAP message, in a custom request, cannot be used for http response headers because it is other scope.

**Comment by EricoGT** [comment]
OK. Thanks for the support. After upgrading my web service I'll do more
tests with this delegate.

2015-02-23 12:58 GMT-03:00 Danilo Priore <notifications@github.com>:

**Comment by priore** [comment]
soon, in the next update there will also be the delegate for upload progress

**Comment by priore** [comment]
the upload progress now is available 81158b697d849bd6892e4a6b69fc846f9fccb866
