### ISSUE TITLE
request a operation of the wsdl method very slow

### ISSUE THREAD

**Issue by dlpigpen** [priore/SOAPEngine#29]
I am trying to call an action from the wsdl. The different thing between your source code and the soap ui tool (http://www.soapui.org/) that this tool is faster than yours. 

The speed of the soap ui tool: 3s
your source code: 60s

I don't know why, so could you have any suggestions?

**Comment by priore** [comment]
Do not use requestWSDL, the method requestWSDL was added only for beginners developer, please use requestURL instead, you can retrieve the soapAction needed for requestURL method through your favorite browser by calling directly the WSDL and find in it the correct soapAction.
Note: soapUI makes a request and displays its content, does not perform additional processing, instead the SOAPEngine processing the contents to converting into a dictionary and the necessary checks of the response, like errors or conversion of types of chars.

**Comment by dlpigpen** [comment]
Thank for your fast response. I appreciate your suggestion and also your advice. Everything is better now. I've also purchased your engine framework. Wish you always update and finally, if i've found out thing need to be updated, I will submit a new ticket for you.

Plz close the issue. Many thanks!

**Comment by TamilRaja** [comment]
Hi 

 how to use WSDL url in soap method. Can you give an idea.

**Comment by priore** [comment]
Hi TamilRaja, look the example "directly from WSDL" from https://github.com/priore/SOAPEngine#how-to-use (continue through your previous issue #55 ).

**Comment by TamilRaja** [comment]
HI @priore Really thanks for your update. I have check that one..
