### ISSUE TITLE
Need a callBack Function

### ISSUE THREAD

**Issue by ponymuch** [priore/SOAPEngine#30]
![error](https://cloud.githubusercontent.com/assets/10826321/6499315/daedcbb6-c333-11e4-82c8-8474c08b3fcc.png)
I need this callback function,but whenever I call the function ,It return the same value "无值"

I have already use this method：but it didn't work！
http://www.g8production.com/post/76942348764/wait-for-blocks-execution-using-a-dispatch

I am a fresh man，would you please give me a demo or some sample code to solve this problem？

very appreciate！that‘s trouble me for a long time！

**Comment by priore** [comment]
Hello
set the property named responseHeader to YES and download the latest version of the framework, now contains new synchronous methods that you need.

**Comment by ponymuch** [comment]
there is no wsdl 's sync methods.....

**Comment by priore** [comment]
Yes, is true, but I suggest you use requestURL, as described in this side of wiki https://github.com/priore/SOAPEngine#optimizations this greatly improve the speed of response of the service

**Comment by ponymuch** [comment]
could you please give me a demo?
thanks!

**Comment by priore** [comment]
``` objective-c
NSError *error = nil;
    SOAPEngine *soap = [[SOAPEngine alloc] init];
    soap.responseHeader = YES;
    NSDictionary *dict = [soap syncRequestURL:@"http://59.77.16.52:8080/axis2/services/TestService" soapAction:@"http://tempuri.org/test" error:&error];
    NSLog(@"error: %@, result: %@", error, dict)
```

but are not sure of the url of the service, perhaps you need to include .php at the end, and not even the soapAction since I did not grant to see the wsdl.

**Comment by ponymuch** [comment]
fabulous! It works!
Thanks a lot!
I get this:
[Body: {
    testResponse =     {
        return = "hello much3";
    };
}]

I use the dic["Body"] get this:
{
    testResponse =     {
        return = "hello much3";
    };
}
I just need the String "hello much3".
how to get this?
I used to use the soap.StringValue() get the result string directly.

**Comment by priore** [comment]
for a standard SOAP services (MS-SOAP) you can use the stringValue, and responseHeader set to NO, for a not standard SOAP service (like PHP / JAVA) uses the method valueForKeyPath available for the NSDictionary types (in your case set to Body.testResponse.return) and responseHeader set to YES.

**Comment by ponymuch** [comment]
Thank you very very much!!!
