### ISSUE TITLE
Feature request: CocoaPods support

### ISSUE THREAD

**Issue by Apolotary** [priore/SOAPEngine#32]
Could you please add support for CocoaPods? 

Thanks in advance!

**Comment by jaunesarmiento** [comment]
:+1: for CocoaPods support

**Comment by viniciusmo** [comment]
+1 for CocoaPods support

**Comment by Apolotary** [comment]
Actually, I'm not sure if that'd be compatible with project's license: https://github.com/priore/SOAPEngine/blob/master/General%20License%20iOS.pdf

**Comment by priore** [comment]
Now we have included the podspec file 3d13d071d4f02deb828d84bca6e02de1a5157eec
