### ISSUE TITLE
RequestURL Block Deprecated

### ISSUE THREAD

**Issue by naldolopes** [priore/SOAPEngine#33]
I 'm getting the following Warning in IOS 8 :

"requestURL:soapAction:complete:failWithError is deprecated" 

Is it a problem? its compile and run...

**Comment by priore** [comment]
the method is deprecated, but you can still use it. It 'been deprecated because returns the result only as string format, we suggest using the new delegate that returns already parsed data in NSDictionary format.

**Comment by naldolopes** [comment]
But in this case my ruturn data is a string
Em 17/03/2015 10:15, "Danilo Priore" <notifications@github.com> escreveu:

**Comment by priore** [comment]
yes, but the delegate returns a string (parameter named stringXML) which is the complete unparsed SOAP message, while the delegate that returns the dictionary, the SOAP msg is already parsed.
In any case, the previous delegate, the deprecated delegate, can be used but we advise to use the most recent delegate, the deprecated delegate will not be removed for a long time, but only for leave the compatibility with older version of our framework, do not worry.
