### ISSUE TITLE
Setting custom header?

### ISSUE THREAD

**Issue by jaunesarmiento** [priore/SOAPEngine#35]
Hi, I need to be able to do the following request. I also need that header to be added on every succeeding request.

```
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Header>
        <AuthHeader xmlns="https://some.xmlns_url_here.com/webservices/WebService">
            <Token>SOME_AUTH_TOKEN_HERE</Token>
        </AuthHeader>
    </Header>
    <Body>
        ...
    </Body>
</Envelope>
```

How can I do this using SOAPEngine? I'm fairly new to SOAP even though it's been around for ages, so please bear with me. :)

**Comment by priore** [comment]
sets property named `authorizationMethod` to SOAP_AUTH_CUSTOM value and define your custom header in property named "`header`.

**Comment by jaunesarmiento** [comment]
Yeah I tried that. But now I'm encountering another issue I think. The SOAPEngine thinks I'm still using the `Login` operation.

**Comment by priore** [comment]
sorry, I did not understand, I can see the code you're using ?

**Comment by jaunesarmiento** [comment]
Hold on, can I email you instead? It's kind of confidential.

**Comment by priore** [comment]
sure, you can use support@prioregroup.com

**Comment by jaunesarmiento** [comment]
Alright thanks!

**Comment by ashers91** [comment]
Do you know how we can add a custom header that isn't for authentication, such as:
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2" />
  </soap:Header>

**Comment by priore** [comment]
@ashers91 

```objective-c
    soap.actionNamespaceSlash = NO;
    soap.authorizationMethod = SOAP_AUTH_CUSTOM;
    soap.header = @{@"t:RequestServerVersion": @"", @"attributes": @{@"Version": @"Exchange2010_SP2"}};
    soap.envelope = @"xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\"";
    [soap setValue:@{@"t:BaseShape": @"Default"} forKey:@"FolderShape"];
    [soap setValue:@{@"t:DistinguishedFolderId": @"", @"attributes": @{@"Id": @"calendar"}} forKey:@"FolderIds"];
    [soap requestURL:@"your-service-url" soapAction:@"http://schemas.microsoft.com/exchange/services/2006/messages/GetFolder"];
```
