### ISSUE TITLE
Getting attributes from the XML tag?

### ISSUE THREAD

**Issue by jaunesarmiento** [priore/SOAPEngine#36]
Given I have the following response body:

```xml
<GetAllUsersResponse>
  <GetAllUsersResult>
    <User ID="1">
      ..
    </User>
    <User ID="2">
      ..
    </User>
  <GetAllUsersResult>
</GetAllUsersResponse>
```

Is there a way I can get the users' `ID`s from the dictionary that SOAPEngine returns? Or do I have to roll my own parser for this kind of use-case?

**Comment by priore** [comment]
at this last version the attributes are not considered, are considered only the values, but we can see how to do this new features.

**Comment by jaunesarmiento** [comment]
Alright, thanks!

**Comment by priore** [comment]
did you find helpful the changes of our framework that we have sent in your email ?

**Comment by jaunesarmiento** [comment]
I haven't tried it yet. Thanks for the quick implementation of the feature! :) I'll try it out when I get the time.

**Comment by priore** [comment]
Please, download the last version and sets the retrievesAttributes property to YES 6f9d53bba021dfc3ff1a4827ad89a60a21afd1c1

**Comment by jaunesarmiento** [comment]
I'm still not getting the `ID` fields back. It could be because `User` is an array of elements?

**Comment by priore** [comment]
we're working on this

**Comment by jaunesarmiento** [comment]
Cool, thanks!

On Mon, Apr 27, 2015 at 6:03 PM, Danilo Priore <notifications@github.com>
wrote:

> we're working on this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/priore/SOAPEngine/issues/36#issuecomment-96590160>.
>



-- 
*Jaune Sarmiento*
*JavaScript, iOS, Android*

**Comment by priore** [comment]
hello
please, take downloading this last commit 1263a633743b8f0a6c76febe0d8da500da3521d7

**Comment by jaunesarmiento** [comment]
Hi @priore, I can get the attributes now. Thank you very much! Will close this issue now.
