### ISSUE TITLE
How can I submit a two-dimension?

### ISSUE THREAD

**Issue by dlpigpen** [priore/SOAPEngine#37]
I've charged your framework and it's very nice I think. However we are in the trouble in the error that soap engine fire out.

The message "SOAPEngine Cannot use object of type stdClass as array"

Our services is receiving a two-dimension array and the data type in the SOAP is "xsd:string[][]" and this is the struct.
```
<urn:greenapicatalogCategorySubmitReviewByProductID soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <sessionId xsi:type="xsd:string">?</sessionId>
   <customer_id xsi:type="xsd:int">?</customer_id>
   <comment xsi:type="xsd:string">?</comment>
   <questions xsi:type="urn:greenapicatalogCategoryProductReviewArray" soapenc:arrayType="xsd:string[][]"/>
   <photo1 xsi:type="xsd:string">?</photo1>
   <photo2 xsi:type="xsd:string">?</photo2>
   <photo3 xsi:type="xsd:string">?</photo3>
   <customer_ip xsi:type="xsd:string">?</customer_ip>
   <webform_id xsi:type="xsd:int">?</webform_id>
</urn:greenapicatalogCategorySubmitReviewByProductID>

```
Could you help us? This is a urgent question because our project is coming to deadline. Thank for your help?

**Comment by priore** [comment]
sorry, we necessary to examine the complete soap message, please, send us the full xml response, here or if you prefer, to our support email, thanks

**Comment by priore** [comment]
sorry, I had not understood that the server responds with this message.
Objective-C does not have two-dimensional array types, the only way to send a two-dimensional array you need to create a NSMutableArray where each element is another NSMutableArray

**Comment by dlpigpen** [comment]
Thank for your help. The problem has been solved.
