### ISSUE TITLE
Deserializing parameter problem

### ISSUE THREAD

**Issue by KamikX** [priore/SOAPEngine#38]
Hi all, I have a problem with calling webservise  with parameter. The situation is as follows:

When execute  this code :

    soap.userAgent = "SOAPEngine"
    actionNamespaceSlash = true
    soap.version = VERSION_1_1
    soap.setValue(2, forKey: "Lang")
        
    soap.requestURL("http://www.vitajtevtrnave.sk/miscellaneous/webservice.cfc",      
                                soapAction:"GetWholeDatabase", 
                                completeWithDictionary: { (status: Int, dict: [NSObject : AnyObject]!) -> Void in
            
                                 var result:Dictionary = dict as Dictionary
                                        println(result)
 
                                 }) { (error:NSError!) -> Void in
                
                                         println(error)
                                }

I get error message:

<pre>SOAPEngine org.xml.sax.SAXException: Deserializing parameter 'Lang':  could not find deserializer for type {http://www.w3.org/2001/XMLSchema}anyType
Error Domain=NSOSStatusErrorDomain Code=0 "org.xml.sax.SAXException: Deserializing parameter
'Lang':  could not find deserializer for type {http://www.w3.org/2001/XMLSchema}anyType" 
UserInfo=0x7ffac9d441b0 {NSLocalizedDescription=org.xml.sax.SAXException: Deserializing parameter 'Lang':  could not find deserializer for type {http://www.w3.org/2001/XMLSchema}anyType}</pre>

Soap message from SoapUI:

<pre>
  soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"    
  xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mis="http://miscellaneous">
  soapenv:Header
  soapenv:Body
      mis:GetWholeDatabase soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      Lang xsi:type="xsd:int">2</Lang>
      mis:GetWholeDatabase
  soapenv:Body
  soapenv:Envelope
</pre>

When use  action without parameter everything works. Could anyone help me ? where may be a bug ? 

Thanks

**Comment by priore** [comment]
Please, download the last version and use the xsdDataTypes property and setIntegerValue instead of the setValue method 6f9d53bba021dfc3ff1a4827ad89a60a21afd1c1

**Comment by KamikX** [comment]
Thank you for  quick fix :)
