### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1012 after upgrading to SoapEngine64

### ISSUE THREAD

**Issue by D33jay** [priore/SOAPEngine#39]
Hi,
i tried to upgrade my project to use the SoapEngine 64 Framework (I used the 32 bit version in the past). 
Now I get a NSURLErrorDomain -1012 and a weird NSErrorFailingURLKey Error. I did`t changed anything in the code but the deprecated methods :

(void)requestURL:(id)asmxURL
        soapAction:(NSString *)soapAction
          complete:(SOAPEngineCompleteBlock)complete
     failWithError:(SOAPEngineFailBlock)fail

to 

- (void)requestURL:(id)asmxURL
        soapAction:(NSString *)soapAction
completeWithDictionary:(SOAPEngineCompleteBlockWithDictionary)complete
     failWithError:(SOAPEngineFailBlock)fail;

I really can`t get it work, is there any trick or did I miss something?

**Comment by priore** [comment]
NSURLErrorDomain -1012 is NSURLErrorUserCancelledAuthentication. (See the error code list and search for -1012 https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/Reference/reference.html)

Possible causes:

1. The server requesting a authorization.
2. The URL formed with HTTPS or some path is not what expect, or some other server is requesting authorization.
3. Some intermediary (like a proxy server) is requiring a authorization.

Try again, before sets the property named selfSigned to YES.

**Comment by D33jay** [comment]
I tested it with an older version of SoapEngine64.framework and everything works fine. When I added the newest Version I got the Error I previously wrote. When I set the selfSigned property to YES It works, but I get really strange results (Most of the values are missing)

**Comment by priore** [comment]
you can send us the example of your code with the relative service url, if you prefer through email, if contains private data, thanks

**Comment by D33jay** [comment]
I sent you an email.

**Comment by priore** [comment]
we have not received any e-mail, please send it to support@prioregroup.com, please take the last commit that fixes problems with the missing values 1263a633743b8f0a6c76febe0d8da500da3521d7

**Comment by D33jay** [comment]
I sent you the email again. I will test this with the newest commit. Thanks

**Comment by priore** [comment]
Hi,
unfortunately we cannot perform a tests on the service that you have written in the mail, because it is geo-located and does not accept calls from other country, we are in Italy.

in any case, we are trying to do more testing with other https services, although with paypal working properly, we will inform you as soon as possible.

thanks for your patience.

**Comment by priore** [comment]
Please, try with this latest version if resolve your problem https://github.com/priore/SOAPEngine/releases/tag/v1.20.2

thanks
