### ISSUE TITLE
SetValue Problem 

### ISSUE THREAD

**Issue by naldolopes** [priore/SOAPEngine#40]
Hi, i have a strange problem here.  This my code...

Usuarios *usuario = [db getDataFromUserTable];

    for (Pedidos *p in arrayPedidos)
    {
        // INICIALIZA O OBJETO SOAP.
        soap = [[SOAPEngine alloc] init];
        soap.userAgent = @"SOAPEngine";
        soap.licenseKey = kSOAP_ENGINE_KEY;
        soap.version = VERSION_WCF_1_1; // WCF service (.svc)

        [soap setValue:usuario.usuarioUID forKey:@"aparelhoUID"];
        [soap setValue:p.pedidoID forKey:@"NumeroPedido"]; // THIS IS NSNUMBER AND WORKS 
        [soap setValue:p.nomeGerenteLoja forKey:@"NomeGerenteLoja"];
        [soap setValue:p.emailLoja forKey:@"EmailLoja"];
        [soap setValue:p.nomeAprovadorLoja forKey:@"AutorizadoPor"];
        [soap setValue:p.qtdOcorrenciasRegistradas forKey:@"QuantOcorrRegistrada"]; // THIS  IS NSNUMBER AND NOT WORKS.
        [soap setValue:p.statusID forKey:@"StatusPedido"];  // THIS IS NSNUMBER AND NOT WORKS. 
        
        NSError *error = nil;
        [soap syncRequestURL:kBASE_URL_ARTSERVICES
                  soapAction:@"http://smart.artservices.com.br/IPositivacao/UploadDadosPedido" error:&error];
        
        if (error != nil)
        {
            return;
        }
        
        if ([[soap stringValue] isEqualToString:@"true"])
        {
            NSLog(@"STATUS: UPLOAD PEDIDO ID: %@ -- OK --",p.pedidoID);
            p.isSync = [NSNumber numberWithBool:TRUE];
            
            if(!([self.managedObjectContext save:&error]))
            {
                // Handle Error here.
                NSLog(@"LOG: %@", [error localizedDescription]);
            }
        }
        else
        {
            NSLog(@"STATUS: UPLOAD ERROR!");
            NSLog(@"ERRO UPLOAD PEDIDO ID: %@,",p.pedidoID);
        }
    }

The parameters with receive NSNumber values in this code, the last two of them, arrive with value '0' in my server.
But  the first one (p.pedidoID) arrive with correct value in my server.
I Try use setIntergerValue buts it's show the same problem. In my server it waits a int32 for the last 2 parameters.  I`m doing something wrong?

**Comment by priore** [comment]
Hello,
we tried the same sequence of parameters, like yours, there are no problems in the generation of the soap request, all values are filled.

we are using this example :
```
    [soap setValue:@"q12w" forKey:@"Param1"];
    [soap setValue:[NSNumber numberWithInt:1] forKey:@"Param2"];
    [soap setValue:@"qwerty" forKey:@"Param2"];
    [soap setValue:@"asdfgh" forKey:@"Param3"];
    [soap setValue:@"zxcvbn" forKey:@"Param4"];
    [soap setValue:[NSNumber numberWithInt:2] forKey:@"Param6"];
    [soap setValue:[NSNumber numberWithInt:3] forKey:@"Param7"];
```
and the xml generated for the request is:
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Header/>
	<soap:Body>
		<MyRequest xmlns="http://www.prioregroup.com/">
			<Param1>q12w</Param1>
			<Param2>1</Param2>
			<Param2>qwerty</Param2>
			<Param3>asdfgh</Param3>
			<Param4>zxcvbn</Param4>
			<Param6>2</Param6>
			<Param7>3</Param7>
		</MyRequest>
	</soap:Body>
</soap:Envelope>
```
You can check the xml request through the `didBeforeSendingURLRequest` delegate, if you prefer, please send a email to us, with your sensible data of your service, so we can help you better.

**Comment by priore** [comment]
another tip, try to enable the property named `xsdDataTypes`, available in new versions

**Comment by naldolopes** [comment]
Tks... but in the end the problem was the order of parameters i send to
Server...
Em 07/05/2015 06:11, "Danilo Priore" <notifications@github.com> escreveu:
