### ISSUE TITLE
When installing though CocoaPods got build error

### ISSUE THREAD

**Issue by hefgi** [priore/SOAPEngine#41]
The file "MyApp.app" couldn’t be opened because you don’t have permission to view it.

that's the error I got after installing SOAPEngine pods. I tried everything and I cannot make it build. Any ideas ?

I tried this following links : 

http://stackoverflow.com/questions/5478480/xcode-4-0-1-dont-have-permission-to-view-old-project-file-help
http://stackoverflow.com/questions/24924809/the-file-myapp-app-couldnt-be-opened-because-you-dont-have-permission-to-vi

**Comment by priore** [comment]
fixed 885109183b73a2a64d979e44a7924b25701e5355, rerun pod install

thanks for your patience
