### ISSUE TITLE
Dictionary with two equal keys

### ISSUE THREAD

**Issue by albertvc10** [priore/SOAPEngine#42]
Hi, 

We have an issue, we want to make a request with the following xml:

```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://server.ws.winparf.lite.com/">
     <soap:Header></soap:Header>
     <soap:Body>
          <ser:getPagedListByFilter>
               <filter>
                  <prenom>remi</prenom>
                    <prenom>bertrand</prenom>
                    <prenom>clement</prenom>
                     <prenom>joan</prenom>
                </filter>
                <pageSize>50</pageSize>
                <mode>disjunction</mode>
                <page>1</page>
           </ser:getPagedListByFilter>
      </soap:Body>
</soap:Envelope>
```

So, we need to add multiple dictionary with the same key ("prenom"). How do we do that?

Thanks in advance,

**Comment by albertvc10** [comment]
When do you expect to have the issue solved?

**Comment by priore** [comment]
sorry, not before than tomorrow

**Comment by priore** [comment]
please use this last version 37ed9c20b9c833bd07984f94eced20fab604e66f that have a extended setValue method :

```objective-c
NSMutableArray *array = [NSMutableArray arrayWithObjects:@"remi", @"bertrand", @"clement", @"joan", nil];
[soap setValue:array forKey:@"filter" subKeyName:@"prenom"];
```

**Comment by albertvc10** [comment]
Hi, 

we have tried your last release but we aren't able to compile. There's an "mach o-linker" error when import the new version of the framework. Even in your sample folder we have the same error. 

here is what it says:

Ld /Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Products/Debug-iphoneos/WinParfMobile.app/WinParfMobile normal arm64
    cd /Users/winparf/Documents/iosmobileapp
    export IPHONEOS_DEPLOYMENT_TARGET=8.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/winparf/.gem/ruby/2.0.0/bin/pod:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk -L/Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Products/Debug-iphoneos -F/Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Products/Debug-iphoneos -F/Users/winparf/Documents/iosmobileapp/WinParfMobile -F/Users/winparf/Downloads/SOAPEngine-1.20.0 -filelist /Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Intermediates/WinParfMobile.build/Debug-iphoneos/WinParfMobile.build/Objects-normal/arm64/WinParfMobile.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -lxml2 -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=8.2 -framework SOAPEngine64 -framework Accounts -framework Security -Xlinker -dependency_info -Xlinker /Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Intermediates/WinParfMobile.build/Debug-iphoneos/WinParfMobile.build/Objects-normal/arm64/WinParfMobile_dependency_info.dat -o /Users/winparf/Library/Developer/Xcode/DerivedData/WinParfMobile-dknucasgymxpkebffhxlzumrettm/Build/Products/Debug-iphoneos/WinParfMobile.app/WinParfMobile

ld: framework not found SOAPEngine64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by priore** [comment]
sorry, is a wrong push, download again d945ad025954ad6922f7925308ae51092950e0af

**Comment by albertvc10** [comment]
Thanks a lot for your effort! 

But we have another issue, similar to the other.

```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://server.ws.winparf.lite.com/">
     <soap:Header></soap:Header>
     <soap:Body>
          <ser:getPagedListByFilter>
               <filter>
                  <tel>8888888</telf>
                  <city>Madrid</city>
                  <person>
                         <prenom>bertrand</prenom>
                         <nom>bertrand</nom >
                   </person >
                          <prenom>pol</prenom>
                         <nom>pol</nom >
                    < person >
                          <prenom>joan</prenom>
                         <nom>joan</nom >
                   </person >
                          <prenom>oriol</prenom>
                         <nom> oriol </nom >
                    < person >
                          <prenom>daniel</prenom>
                         <nom> daniel </nom >
                   </person >
                     <person>
                          <prenom>albert</prenom>
                         <nom> albert </nom >
                   </person >
                </filter>
                <type>A</type>
                <type>B</type>
                <mode>disjunction</mode>
                <page>1</page>
           </ser:getPagedListByFilter>
      </soap:Body>
</soap:Envelope>

```

So, in each key we need more than one subkey.

We are working in a software company, and this is a professional project. We have no problem if needed to pay extra cost or so...

Kind regards,

**Comment by priore** [comment]
you can use a dictionary for each person, with the "prenom" key and "name" key or others, and pass every dictionary, for each person, to setValue with key "person", but would be most correct to include this list of dictionaries in an array and pass it to setValue with a key "persons" and sub key "person".
