### ISSUE TITLE
SOAPEngine operations in NSOperationQueue?

### ISSUE THREAD

**Issue by jaunesarmiento** [priore/SOAPEngine#43]
Hi again,

I'm trying to make a multiple requests to a single web service endpoint. I'm doing this by queuing up these requests in a `NSOperationQueue`. The problem is that when I get to the `completWithDictionary` handler of `requestWSDL` method,  I get the same result from the last operation in the queue.

To better explain my problem, here's an example.

```swift
// A dummy webservice
let url = "https://some.url.com/webservices/WebService.asmx?WSDL"

let queue = NSOperationQueue()
let restaurantIds = [100, 101]

for id in restaurantIds {

  let operation = NSBlockOperation()

  operation.addExecutionBlock({ () -> Void in
    if !operation.cancelled {
      let soap = SOAPEngine.sharedInstance()
      soap.setValue(id, forKey: "RestaurantID") // The value of `id' here is correct; 100, and then 101
      soap.requestWSDL(url,
        operation: "SomeOperation", // A dummy operation
        completeWithDictionary: { (statusCode: Int, response: [NSObject: AnyObject]!) -> Void in
          // When I try to access `id' here, it's always 101 when it should be 100 
          // then 101 on the second.
        }
      )
    }
  })

  queue.addOperation(operation) // Starts the operation

}
```

I think this has something to do with the way you handle completion blocks inside SOAPEngine, but I could be wrong.

It seems that the completion block for the first operation isn't called; instead, it fires the completion block for the second operation for both.

**Comment by priore** [comment]
if you use the shared Instance requests are processed by a single instance of the process, and this creates the conflict, it is better to use a new instance for each request.

A advice, requestWSDL is very slow, you should use requestURL, reading the wiki SOAPEngine on Github.

**Comment by jaunesarmiento** [comment]
Ahh. That explains it. I think I fixed the issue. It might be helpful to others to make note of the conflicts when using `SOAPEngine.sharedInstance()`.

Thanks for the prompt reply!
