### ISSUE TITLE
SOAPEngine sometimes crash with error [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

### ISSUE THREAD

**Issue by martinprot** [priore/SOAPEngine#44]
Hi.

I've installed this framework with cocoapods (v1.2).

Using this code, SOAPEngine crashes with the error : `[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'`

Here's the code that crashes : 

```objective-c
	NSDictionary *params = @{@"email": user.email,
							 @"token": user.token};
	SOAPEngine *soap = [[SOAPEngine alloc] init];
	soap.userAgent = @"SOAPEngine";
	
	// service url with WSDL, and operation (method name) without tempuri
	[soap requestWSDL:@"http://myserver.com/wsdl"
			operation:@"my_service"
				value:params
	completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
	
	NSLog(@"Result: %@", dict);
	
	} failWithError:^(NSError *error) {
	
	NSLog(@"%@", error);
	}];
```

Maybe the crash comes from a wrong server response (since the server belongs to my client, I do not have access to it), but how could I test this response without crashing?

**Comment by priore** [comment]
hello, you are sure that user.email or user.token is not nil?

if the server address is reserved, you can send all data we need for test it through email, so we can help you better (support@prioregroup.com)

**Comment by martinprot** [comment]
Hello.
Of course, I'm sure that my parameters are not nil.
It crashes in `SOAPEngine::connectionDidFinishLoading`, and **only** when the server return error 500.

**Comment by priore** [comment]
We have fixed a problem of decoding the SOAP response, but I suggest to use the "requestURL", that is faster.

```objective-c
    [soap setValue:@"your-email" forKey:@"email"];
    [soap setValue:@"you-token" forKey:@"token"];
    [soap requestURL:@"your-sevice-page.php"
          soapAction:@"webserv_charge_list_post" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        
              NSLog(@"%@", dict);
              
    } failWithError:^(NSError *error) {
        
        NSLog(@"%@", error);
    }];
```

**Comment by martinprot** [comment]
Thanks. It works now.

**Comment by shabeepk** [comment]
Hi there,

We're seeing a similar crash when the server returns a response like this one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <GetTasksResponse xmlns="http://Example">
            <GetTasksResult>
                <ErrorString>No Error</ErrorString>
                <ErrorNum>1</ErrorNum>
                <Data>
                    <![CDATA[<Tasks xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />]]>
                </Data>
            </GetTasksResult>
        </GetTasksResponse>
    </soap:Body>
</soap:Envelope>
```

Can you see why this may be happening? We suspect this as a bug in SOAPEngine.

Thanks.
