### ISSUE TITLE
Digest AuthType

### ISSUE THREAD

**Issue by Oberreiter** [priore/SOAPEngine#45]
Is it possible to access a SOAP Service behind a digest authenticated Apache Server?

Regard Andreas

**Comment by priore** [comment]
The framework supports the basic authentication, username:password converted to base64 and put in the Authorization key of the header of the request, but you can customize the header of the request as you like using the delegate named didBeforeSendingURLRequest, or you can customize the header of SOAP message.

**Comment by Oberreiter** [comment]
Thank You for your quick response.



Regarding to https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/AuthenticationChallenges.html



Rewriting the URL isn't Quit enough.



Do you see a way for me to get this working with your framework?



Regards

Andreas



-----Ursprüngliche Nachricht-----
Von: Danilo Priore <notifications@github.com>
Gesendet: Mon 18 Mai 2015 16:26
An: priore/SOAPEngine <SOAPEngine@noreply.github.com>
CC: Oberreiter Andreas <a.oberreiter@nadlinger.at>
Betreff: Re: [SOAPEngine] Digest AuthType (#45)

The framework supports the basic authentication, username:password converted to base64 and put in the Authorization key of the header of the request, but you can customize the header of the request as you like using the delegate named didBeforeSendingURLRequest, or you can customize the header of SOAP message.

**Comment by priore** [comment]
The our framework also supports NSURLAuthenticationMethodHTTPDigest, being based on NSURLConnection, just set the username and password properties, we recommend downloading the framework and try it on simulator, or if you have a service, send us the data required to use it, if you prefer through with email, and after we try it, in this way we can update the our framework to make it compatible with your server.

**Comment by Oberreiter** [comment]
I've tried all supportet soap.authorizationMethod Values none of the worked for me!

When I try it in my private Network without authentication it works.



Please send me your Private E-Mail. Then I will send you an example Code with the Login Credentials.



Regards

Andreas



-----Ursprüngliche Nachricht-----
Von: Danilo Priore <notifications@github.com>
Gesendet: Mon 18 Mai 2015 17:23
An: priore/SOAPEngine <SOAPEngine@noreply.github.com>
CC: Oberreiter Andreas <a.oberreiter@nadlinger.at>
Betreff: Re: [SOAPEngine] Digest AuthType (#45)

The our framework also supports NSURLAuthenticationMethodHTTPDigest, being based on NSURLConnection, just set the username and password properties, we recommend downloading the framework and try it on simulator, or if you have a service, send us the data required to use it, if you prefer through with email, and after we try it, in this way we can update the our framework to make it compatible with your server.

**Comment by priore** [comment]
we are trying to configure apache to work with digest authorization, but all attempts until now have failed, you can tell us a valid document about how to configure apache on Yosemite (OSX) ?

email: support@prioregroup.com

**Comment by priore** [comment]
now, your apache server are configured with auth digest, and we are developing the authorization digest, as listed below, it is ok for you ?

hash1=MD5(username:realm:password)
hash2=MD5(soap-method:soap-service-uri)
digest=MD5(hash1:nonce:hash2)

where username, realm (new) and password are properties of framework, nonce are generated every time.

**Comment by Oberreiter** [comment]
As far as I know the realm isn't needed. The Server Tests if the given User is in the right realm.

I have a working example php sample without the realm:

$options = array(
		'login' => login,
		'password' => passwort,
	);

	require ("SoapClientAuth.php");
	$this -> client = new SoapClientAuth($GLOBALS['soap_path'],$options);

I'll send you the SoapClientAuth.php File via Mail.

**Comment by priore** [comment]
Hi Andreas,
Unfortunately the code that you have sent, with username and password, returns always 401, maybe there is a problem on the server or the user is not present ?

We tested it with an online server that requires digest authorization, even if not returns an xml, was used only to confirm that the digest works, and works fine.

Below the sample code that we used us with a online server that requires digest authentication.

```objective-c
    soap.authorizationMethod = SOAP_AUTH_NONE; // tips: sets NONE, but sets username and password
    soap.username = @"guest";
    soap.password = @"guest";
    [soap requestURL:@"http://www.moditekka.com/phpauth.php" soapAction:@“test" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        // not important for this test
    } failWithError:^(NSError *error) {
        NSLog(@"%@", error);
    }];
```

**Comment by Oberreiter** [comment]
I'm sorry I forgot to reload the apache config!
Now the login works at least i one yes it with the browser.

Unfortunately It still don't work with your code?!

If I compare the login windows of your testsite with mine they are different. (The realm looks different) 

If implemented the Digest this way:
apache2.conf
```
<Directory "/path to Website">
 AuthType Digest
 AuthName "ExtraDB"
 AuthUserFile /path to File/digest.users
 Require user prior
</Directory>
```
To create the digest.users
 `htdigest /path to File/digest.users ExtraDB priore`

**Comment by priore** [comment]
Please, try with this latest version https://github.com/priore/SOAPEngine/releases/tag/v1.20.2

**Comment by Oberreiter** [comment]
Thank you works great!!!
