### ISSUE TITLE
Message Composition

### ISSUE THREAD

**Issue by KamikX** [priore/SOAPEngine#46]
Hi all I have example  of soap message: 

<pre>
&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" &lt;xmlns:tem="http://tempuri.org/">
&lt;soapenv:Header/>
   &lt;soapenv:Body>
      &lt;tem:ReceiveMessage>
           &lt;tem:request>
            &lt;tem:MessageContainer>
               &lt;Object Id="" Name="" Description="" Class="" IsSigned="" MimeType="" Encoding="">
               &lt;/Object>
            &lt;/tem:MessageContainer>
         &lt;/tem:request>
      &lt;/tem:ReceiveMessage>
   &lt;/soapenv:Body>
&lt;/soapenv:Envelope> 
</pre>

My question is how to  set  xmlns:tem="http://tempuri.org/" and attribute  for  element  Object like Id, Name,  Description.

This is  structure of Object  from WSDL: 
<pre>
  &lt;xs:complexType mixed="true" name="object">
    &lt;xs:sequence>
      &lt;xs:any maxOccurs="unbounded" minOccurs="0"/>
    &lt;/xs:sequence>
    &lt;xs:attribute name="Id" type="xs:string"/>
    &lt;xs:attribute name="Name" type="xs:string"/>
    &lt;xs:attribute name="Description" type="xs:string"/>
    &lt;xs:attribute name="Class" type="xs:string"/>
    &lt;xs:attribute name="IsSigned" type="xs:boolean"/>
    &lt;xs:attribute name="MimeType" type="xs:string"/>
    &lt;xs:attribute name="Encoding" type="tns:encoding" use="required"/>
</pre>

I trying compose this message, there is my code:

<pre>
        var object:NSDictionary = ["Object":"anyType"]
        var request:NSDictionary = [ "MessageContainer":object]
        
        var soap = SOAPEngine()
        soap.delegate = self
        //soap.envelope = "xmlns:tem=\"http://tempuri.org/"   HTTP operation error statusCode: 400
        soap.userAgent = "SOAPEngine"
        soap.version = VERSION_1_1
       soap.setValue(request, forKey: "request")
        soap.requestWSDL("xxx/receiveMessage?wsdl", operation: "ReceiveMessage")
</pre>

This is my result XML:
<pre>
 &lt;?xml version="1.0" encoding="utf-8"?> &lt;soap:Envelope
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" /> 
&lt;soap:Header> &lt;/soap:Header> 
 &lt;soap:Body> 
     &lt;ReceiveMessage xmlns="http://tempuri.org/IMessage"> 
          &lt;request>
               &lt;MessageContainer>
                    &lt;Object>xs:any and attribute&lt;/Object>
               &lt;/MessageContainer> 
          &lt;/request>
      &lt;/ReceiveMessage>
&lt;/soap:Body>
</soap:Envelope> 
</pre>

**Comment by priore** [comment]
This version does not support sending the attributes, but only receive, but we can implement this feature, we need only few days to organize this work, meanwhile you can implement this through the didBeforeSendingURLRequest delegate :

```objective-c
- (NSMutableURLRequest *)soapEngine:(SOAPEngine *)soapEngine didBeforeSendingURLRequest:(NSMutableURLRequest *)request
{
    NSString *originalXML = [[NSString alloc] initWithData:[request HTTPBody] encoding:NSUTF8StringEncoding];
    NSString *objectTag = [NSString stringWithFormat:@"<Object id=\"%@\" Name=\"%@\">", @"id-value", @"name-value"];
    NSString *alteredXML = [originalXML stringByReplacingOccurrencesOfString:@"<Object>" withString:objectTag];
    [request setHTTPBody:[alteredXML dataUsingEncoding:NSUTF8StringEncoding]];
    
    return request;
}
```

**Comment by KamikX** [comment]
Your temporarily solution works fine  but I had to replace this:   <pre> &lt;ReceiveMessage xmlns="http://tempuri.org/IMessage"> </pre>
to this : 
<pre> &lt;ReceiveMessage xmlns="http://tempuri.org/"> </pre>

First figure is generated automatically from WSDL ? it possible replace  this  at  other point  ??

**Comment by priore** [comment]
If you use the WSDL, is not best solution because is very slow operation, i suggest the use of requestURL for best performance, the namespace is retrieved from wsld, but if you use the requestURL method, is needed only change the soapAction parameter with http://tempuri.org/ReceiveMessage value

**Comment by KamikX** [comment]
If  use requestURL  and set the soapAction parameter with http://tempuri.org/ReceiveMessage 
SOAP Action in header is and  I get error 500
<pre>SOAPAction: "http://tempuri.org/ReceiveMessage"</pre>

If set SOAP Action as    http://tempuri.org/IMessage/ReceiveMessage an replace   ReceiveMessage tag  it is ok
<pre>SOAPAction: "http://tempuri.org/IMessage/ReceiveMessage"</pre>

**Comment by priore** [comment]
or try with this :

```swift
soap.envelope = "xmlns:imsg=\"http://tempuri.org/IMessage/";
soap.requestWSDL("xxx/receiveMessage", operation: "imsg:ReceiveMessage");
```
