### ISSUE TITLE
Does your library support the https request?

### ISSUE THREAD

**Issue by dlpigpen** [priore/SOAPEngine#49]
I am having in the trouble with using the https request.  I'd like to know that does your library supports https request?

This is an error message: Printing description of error:
Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed.

**Comment by priore** [comment]
Yes the our framework supports https, NSURLErrorDomain -1012 is NSURLErrorUserCancelledAuthentication. (See the error code list and search for -1012 https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/Reference/reference.html)

Possible causes:

1. The server requesting a authorization.
2. The URL formed with HTTPS or some path is not what expect, or some other server is requesting authorization.
3. Some intermediary (like a proxy server) is requiring a authorization.

Sets the property named selfSigned to YES or if you can send to us the example of your code with the relative service url, if you prefer through email if contains private data, so we can try for you.

**Comment by dlpigpen** [comment]
Thanks for your fast response. 

Could you provide your email? I really need your help. Thank so much!

**Comment by priore** [comment]
you can find the email in the priore profile of github
