### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by mehmetvefa** [priore/SOAPEngine#50]
Hi, maybe my question will be easy but I need help.

I am trying to add SOAPEngine to my current project with a Podfile like this:

platform:ios, '7.0'
pod ’SOAPEngine’ ‘~> 1.21.0’

but I got error. Could you tell me what is the correct podfile content?

**Comment by priore** [comment]
missing the comma and you must use the simple apex, like in the platform definition :

platform:ios, '7.0'
pod 'SOAPEngine', '~> 1.21.0'
