### ISSUE TITLE
Using with Swift

### ISSUE THREAD

**Issue by mehmetvefa** [priore/SOAPEngine#51]
I am trying to use the pod with my Swift project. I have created my Bridging-Header.h file but I can't include the pod on my SOAPEngine-Bridging-Header.h file.

What should I include here? Could you help me?

![screen shot 2015-06-17 at 11 52 38](https://cloud.githubusercontent.com/assets/3125510/8203004/67c5a266-14e7-11e5-809f-658d149ea1b6.png)

**Comment by priore** [comment]
perhaps you may need read this article [Podfile-AFNetworking](https://medium.com/@stigi/swift-cocoapods-da09d8ba6dd2)
