### ISSUE TITLE
Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.

### ISSUE THREAD

**Issue by abin0992** [priore/SOAPEngine#52]
i use SOAP Engine the request i call is

      soap.authorizationMethod = SOAP_AUTH_CUSTOM;
      soap.header = [NSString stringWithFormat:@"<userCredentials xmlns=\"http://tempuri.org/\"><userName>swm</userName><passWord>swm123</passWord></userCredentials>"];
      [soap setValue:@"6" forKey:@"staffId"];
      [soap requestURL:@"http://swm20.evizontech.com/mobApp_WebServices/ws_getTaskListByAssignee.asmx"
          soapAction:@"http://tempuri.org/GetTaskAssignedToMeList"];

i get this message before
"Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future." My code, its corresponding output and the XML to parse  is shown on screenshot below. The actual problem is i am getting extra double quotes in my output. How can i rectify this?
![screen shot 2015-07-04 at 2 48 53 pm](https://cloud.githubusercontent.com/assets/10430402/8507359/2e64b6f0-225d-11e5-92e7-4e577cd3d0c6.png)

**Comment by priore** [comment]
Yes, is an internal warning message, only internal warning message, during the conversion of the received data in an readable XML format, you can ignore it, it is a not blocking error and not generate others errors on the received data, this message will be removed in the future versions.

thanks for this note and we apologize for your wasted time.
