### ISSUE TITLE
SoapEngine License

### ISSUE THREAD

**Issue by thor486** [priore/SOAPEngine#53]
hello, I bought a single license key following the links here on github but your site isn't working. How can I get the license key? 

Thanks

**Comment by priore** [comment]
the hosting service where there is the procedure for creating the license is offline, we have opened a trouble-ticket, we will notify the resolution as soon as possible.

Sorry for this inconvenience, thanks for patience.

**Comment by priore** [comment]
the site appears restored, thanks for your patience
