### ISSUE TITLE
Not clear on what happens to array of dicts.

### ISSUE THREAD

**Issue by lamenyq** [priore/SOAPEngine#54]
This is likely not the right forum, but I am not sure where to get help.

I am trying to figure out where <item> is coming from.  Any insights would be appreciated.

My dict,

    Coolers =     {
        WICooler =         (
                        {
                Clean = true;
                Cooler = "Cooler # 3";
                CoolerID = 1;
                Damaged = false;
                PalletTagged = true;
                Temperature = "";
            },

becomes,

                <Coolers>
                    <WICooler>
                        <item>
                            <Cooler>Cooler # 3</Cooler>
                            <Temperature></Temperature>
                            <Clean>1</Clean>
                            <Damaged>0</Damaged>
                            <CoolerID>1</CoolerID>
                            <PalletTagged>1</PalletTagged>
                        </item>

**Comment by priore** [comment]
The Item tag is present because WIColer is an array, if you dont want the tag Item,  change WIColer to a dictionary, but if you want leave the array you can change the name of the tag with the properties named "defaultTagName" (accepts nil values).

**Comment by lamenyq** [comment]
Thanks for the response.   I am not really sure why WICoolers is being turned into an array.

```xml
<soap:Body>
    <GetWIReportResponse xmlns="http://somehost.com/">
        <GetWIReportResult>
            <Coolers>
                <WICooler>
                    <CoolerID>1</CoolerID>
                    <Cooler>Cooler # 3</Cooler>
                    <Clean>true</Clean>
                    <Damaged>false</Damaged>
                    <PalletTagged>true</PalletTagged>
                    <Temperature xsi:nil="true" />
                </WICooler>
                <WICooler>
```

Fetching the above xml with

```obj-c
[soap requestURL:host
      soapAction:@"http://somehost.com/GetWIReport"
    completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            dispatch_async(dispatch_get_main_queue(), ^{
```

gives me the following dict

```
(lldb) po dict
{
    Coolers =     {
        WICooler =         (
                        {
                Clean = true;
                Cooler = "Cooler # 3";
                CoolerID = 1;
                Damaged = false;
                PalletTagged = true;
                Temperature = "";
            },
                        {
                Clean = true;
                Cooler = "Cooler # 4";
                CoolerID = 2;
```

Why is the WICooler an array, and not Coolers?

**Comment by priore** [comment]
in the XML, the tag named "Coolers" is an array, or better, is a set of elements named "WTCooler", the transformation in Objective-C, without losing the identifying name of the single elements, this becomes a "Coolers" dictionary that contains an array with key named "WTCooler", this just to not lose the identifier of single elements.
