### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TamilRaja** [priore/SOAPEngine#55]
Hi friends 

I have used this code for WSDL format. But coming error. Can you give idea or fix this one.

2015-07-15 12:27:23.137 SOAPEngine Sample[2528:77854] {
    Accept = "text/xml; charset=utf-8";
    "Content-Length" = 617;
    "Content-Type" = "text/xml; charset=utf-8";
    SOAPAction = "\"http://82.178.20.92:8080/CRM/services/SearchBusiness.ws?wsdl\"";
    "User-Agent" = SOAPEngine;
}
2015-07-15 12:27:23.138 SOAPEngine Sample[2528:77854] <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" ><soap:Header></soap:Header><soap:Body><SearchBusiness.ws?wsdl xmlns="http://82.178.20.92:8080/CRM/services/"><businessCode></businessCode><businessName>wear</businessName><location>4355434576</location><categoryKeyword>4355434576</categoryKeyword><PageNumber>4355434768</PageNumber><paginationSize>4355434832</paginationSize><languageCode>en</languageCode></SearchBusiness.ws?wsdl></soap:Body></soap:Envelope>
2015-07-15 12:27:23.265 SOAPEngine Sample[2528:77854] Sended 617 bytes of 617 bytes
2015-07-15 12:27:23.375 SOAPEngine Sample[2528:77854] SOAPEngine missing Content-Length in the header of the HTTP response or its value is equal zero!
2015-07-15 12:27:23.375 SOAPEngine Sample[2528:77854] Received-------> 669 bytes of 0 bytes
2015-07-15 12:27:23.376 SOAPEngine Sample[2528:77854] Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.
2015-07-15 12:27:23.376 SOAPEngine Sample[2528:77854] SOAPEngine Server response: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 265; Element type "SearchBusiness.ws" must be followed by either attribute specifications, ">" or "/>".

**Comment by priore** [comment]
the WSDL of your service does not contain valid soapAction, search soapAction in your WSDL and you will find it empty, instead should have the getSearchBusiness value, so you can not use this, in addition we not recommend call WSDL directly with requestWSDL, because it is very slow compared to the call directly to method of service service with requestURL.

**Comment by priore** [comment]
try using this

```
    soap.replaceNillable = YES;
    soap.actionNamespaceSlash = NO;
    [soap requestURL:@"http://82.178.20.92:8080/CRM/services/SearchBusiness.ws?wsdl"
          soapAction:@"getSearchBusiness" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
              
              NSLog(@"%@", dict);
              
          } failWithError:^(NSError *error) {
              
              NSLog(@"%@", error);
              
          }];
```

**Comment by TamilRaja** [comment]
Hi friend
       You have used normal (asmx url) method. That framework available in WSDL method. for your reference 
- (void)requestWSDL:(id)wsdlURL
          operation:(NSString *)operation
              value:(id)value
completeWithDictionary:(SOAPEngineCompleteBlockWithDictionary)complete
      failWithError:(SOAPEngineFailBlock)fail;

how to pass this values like that URL. 
WSDL :http://82.178.20.92:8080/CRM/services/GetCategoryList.ws?wsdl
method : getCategoryList
parameter : category=733

**Comment by TamilRaja** [comment]
Hi 
     i have used for this method but application crashed. Can you review my code. 

NSDictionary *dicta = [[NSDictionary alloc]initWithObjectsAndKeys:@"733",@"category", nil];
    NSLog(@"dicta %@",dicta);
    [soap requestWSDL:@"http://82.178.20.92:8080/CRM/services/GetCategoryList.ws?wsdl" operation:@"getCategoryList" value:dicta completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        
        NSLog(@"%@", dict);
        
    } failWithError:^(NSError *error) {
        
        NSLog(@"%@", error);
        
    }];

Crash Message : -[__NSCFConstantString firstObject]: unrecognized selector sent to instance 0x10f588060'

**Comment by priore** [comment]
The WSDL is not a service but is a description of service, the real service url is defined from "wsdlsoap:address" inside WSDL :

<wsdlsoap:address location="http://82.178.20.92:8080/CRM/services/GetCategoryList.ws"/>

but the WSDL not contains a soapAction valid value, that required for requestWSDL method, in this case you need to use requestURL with this location (http://82.178.20.92:8080/CRM/services/GetCategoryList.ws) and with soapAction value "getCategoryList".

```
[soap setIntegerValue:733 forKey:@"category"]; // or setValue:@"733" forKey:@"category"
[soap requestURL:@"http://82.178.20.92:8080/CRM/services/GetCategoryList.ws"
          soapAction:@"getCategoryList" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {

              NSLog(@"%@", dict);

          } failWithError:^(NSError *error) {

              NSLog(@"%@", error);

          }];
```

**Comment by TamilRaja** [comment]
@priore 

     Wow really super. Thanks.........

**Comment by TamilRaja** [comment]
Hi Friends,

      I want one doubt for this framework. This licenses key is valid long time process or short time. 
 Now using in distribution profile it's coming for this message and not working. For your reference here i have attached the screen shot.  How to solve this. Kindly give an alternative solution. If anything problem for app store or future.

![img_5241](https://cloud.githubusercontent.com/assets/3132231/8718111/059763b0-2bbf-11e5-9b87-59750bcbfc89.PNG)

**Comment by priore** [comment]
Hi, the license is valid for long time process, but is associated with the bundle-id of your app, case sensitive, if you changed the bundle with which you have generated the license, this will no longer be valid.

**Comment by TamilRaja** [comment]
Hi @priore 
  
        Now i have used for this  bundle identifier (com.test.app). But same issues coming. how to generated new license.  I have used for previous license Key only, i will give any amount for this framework it seems.

**Comment by priore** [comment]
For give better support for the license, we need the receipt of your purchase of the SOAPEngine, you can sending to our support email.

Note: without license you can run the our framework only on simulator, not on devices. For more informations you can read the General License PDF document, included on GitHub and in zip file.

**Comment by TamilRaja** [comment]
Hi friend

          Thanks for your good co operation....
