### ISSUE TITLE
Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.

### ISSUE THREAD

**Issue by haiboss** [priore/SOAPEngine#56]
How to fix error.
Code 
var soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
         //soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.authorizationMethod=SOAP_AUTH_CUSTOM
       soap.setValue("Demo", forKey: "Username")
        soap.setValue("123", forKey: "Password")
        soap.setValue(1, forKey: "AppID")
        soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://xtestws.vnptphuyen.vn/xtest/GetLevel2UnitList",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
            //var book = dict
                //var verses:NSArray = book["BibleBookChapterVerse"] as! NSArray
            //    println(book)
                //self.verses = verses
                self.table.reloadData()
                
            }) { (error : NSError!) -> Void in
                
               //println("%@", error)
                 NSLog("%@", error)
        }
Error:
2015-07-16 14:21:49.387 SOAPEngine Swift[1026:84888] Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.
2015-07-16 14:21:49.391 SOAPEngine Swift[1026:84888] SOAPEngine Server response: Server did not recognize the value of HTTP Header SOAPAction: http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx/GetLevel2UnitList.
2015-07-16 14:21:49.392 SOAPEngine Swift[1026:84888] Error Domain=NSOSStatusErrorDomain Code=0 "Server did not recognize the value of HTTP Header SOAPAction: http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx/GetLevel2UnitList." UserInfo=0x7fd051e08310 {NSLocalizedDescription=Server did not recognize the value of HTTP Header SOAPAction: http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx/GetLevel2UnitList.}

How to fix it. thx.

**Comment by priore** [comment]
look #52, and we have noted that your soapAction is wrong, for your service must be http://vnpt.vn/GetLevel2UnitList

**Comment by haiboss** [comment]
I've edited under SoapAction is http://vnpt.vn/GetLevel2UnitList but Error ncorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.
2015-07-16 14:21:49.391 SOAPEngine Swift[1026:84888] SOAPEngine Server response: Server did not recognize the value of HTTP Header SOAPAction:"
pls help me test web service. Thx

**Comment by priore** [comment]
This works well for us, even if the server responds with an error message authentication :

```Swift
        soap.actionNamespaceSlash = true
        //soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.authorizationMethod = SOAP_AUTH_CUSTOM
        //soap.header = ?? <-- with SOAP_AUTH_CUTOM this property cannot be nil
        soap.setValue("Demo", forKey: "Username")
        soap.setValue("123", forKey: "Password")
        soap.setValue(1, forKey: "AppID")
        soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://vnpt.vn/GetLevel2UnitList",
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                
                var result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)
        }
```

**Comment by haiboss** [comment]
How to call response header authen before call soap.requestURL. 
soap.header=""<v:Envelope xmlns:i='http://www.w3.org/2001/XMLSchema-instance' xmlns:d='http://www.w3.org/2001/XMLSchema' xmlns:c='http://schemas.xmlsoap.org/soap/encoding/' xmlns:v='http://schemas.xmlsoap.org/soap/envelope/'><v:Header><n0:AuthHeader xmlns:n0='http://vnpt.vn/'><n0:Username>Demo</n0:Username><n0:Password>123</n0:Password></n0:AuthHeader></v:Header> <soap:Body><GetLevel2UnitList xmlns='http://vnpt.vn/'><unitID>int</unitID></GetxDSLDevices></soap:Body></v:Envelope>".

Thx

**Comment by priore** [comment]
we assume that your service requires an authentication as this below :

```
        soap.authorizationMethod = SOAP_AUTH_CUSTOM;
        soap.header = String(format: "<Header><AuthHeader xmlns=\"http://vnpt.vn/\"><Username>%@</Username><Password>%@</Password><AppID>%i</AppID></AuthHeader></Header>", "myusername", "mypassword", 1234);
```

**Comment by haiboss** [comment]
Thx for reply. Full code var soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.authorizationMethod = SOAP_AUTH_CUSTOM
        soap.header = String(format: "<Header><AuthHeader xmlns=\"http://vnpt.vn/\"><Username>%@</Username><Password>%@</Password><AppID>%i</AppID></AuthHeader></Header>", "Demo", "123", 1);
        //soap.setValue("Demo", forKey: "Username")
        //soap.setValue("123", forKey: "Password")
        //soap.setValue(1, forKey: "AppID")
        soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://vnpt.vn/GetLevel2UnitList",
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                
                var result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)
        }
UserName and passwork IS true but post server then error not exists account. pls help me full code.

**Comment by priore** [comment]
sorry, the property "header" value must be without the "header" tag, as below :

```Swift
soap.header = String(format: "<AuthHeader xmlns=\"http://vnpt.vn/\"><Username>%@</Username><Password>%@</Password><AppID>%i</AppID></AuthHeader>", "Demo", "123", 1);
```

**Comment by haiboss** [comment]
thx .
