### ISSUE TITLE
How to call https svc service using SOAPEngine framework

### ISSUE THREAD

**Issue by VS-ARC** [priore/SOAPEngine#57]
Hello,
      I am new to objective-c, i want to call secured(https) svc service in ios. i read article of framework it support only basichttp binding.... & i want to call wshttpsbinding......plz help

**Comment by priore** [comment]
we are already examining the development to support for the services with wsHttpBinding, but is not immediate development, this require more time, sorry.
In any case, the framework provides for the possibility to realize a custom header, and a custom body to be able to make the framework compatible with all the possible requisites, but this implies that you must learn this type of binding, and this it is not simple is complex also for us.

**Comment by VS-ARC** [comment]
ok, thank you
