### ISSUE TITLE
how to call service asynchronously? 

### ISSUE THREAD

**Issue by VS-ARC** [priore/SOAPEngine#58]
in framework example given the way to call service in syncRequestURL....but, i want to call my service method asynchronously(async).

**Comment by priore** [comment]
the framework is completely asynchronous, see requestURL method, and you can decide whether to manage code with delegates or with block programming or with notifications.

**Comment by VS-ARC** [comment]
but if i want to return value, than how can i mange that in block or delegates

**Comment by priore** [comment]
if you want the SVCCall returns a value, this not possible for a async execution, but if you want an async execution is the block that returns the value, this is base of objective-c programming http://rypress.com/tutorials/objective-c/blocks

A advice, use requestURL:soapAction:completeWithDictionary, that return a full dictionary of the SOAP result, and if not return values set the property named "responseHeader" to YES

**Comment by VS-ARC** [comment]
will you please give demo with above example, that block returns value.....

**Comment by priore** [comment]
is simple

```Objective-C
- (void)SVCCallWithCompletionHandler:(void(^)(NSDictionary *dict, NSError *error))block
{
    if (block) {
        SOAPEngine *soap = [[SOAPEngine alloc]init];
        soap.actionNamespaceSlash = YES;
        soap.version= VERSION_WCF_1_1;
        soap.requestTimeout = 10;
        soap.responseHeader = YES;
        soap.licenseKey = @"your-licensekey";
        
        [soap setValue:@"value" forKey:@"value"];
        [soap requestURL:@"http://test.com/basicbinding/service1.svc"
              soapAction:@"http://tempuri.org/IService1/GetValue"
  completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
                  
                  block(dict, nil);
      
              } failWithError:^(NSError *error) {
                  block(nil, error);
              }];
        
    }
}
```

if you need this, or then we did not understand.

**Comment by VS-ARC** [comment]
How can I call that method in extern "C"

```Objective-c

extern "C"
{
char* callService()
{
//how to call SVCCallWithCompletionHandler

}
}


```

**Comment by priore** [comment]
suppose through a callback, but we do not know enough c++ to be able to respond, sorry, we can give support only on Objective-C, Swift and C# for Web services, you need to search support on a forum of experts c++.
In any case you should never have to use extern "C" in an Objective-C project, this is because Objective-C is a strict superset of C.

Sorry.

**Comment by VS-ARC** [comment]
ok, than how can i do that in objective c & swift....

```objective-c

import<Test.h>
@implementation Test

- (void)SVCCallWithCompletionHandler
{
       __block NSString *result;

        SOAPEngine *soap = [[SOAPEngine alloc]init];
        soap.actionNamespaceSlash = YES;
        soap.version= VERSION_WCF_1_1;
        soap.requestTimeout = 10;
        soap.responseHeader = YES;
        soap.licenseKey = @"your-licensekey";

        [soap setValue:@"value" forKey:@"value"];
        [soap requestURL:@"http://test.com/basicbinding/service1.svc"
              soapAction:@"http://tempuri.org/IService1/GetValue"
  completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {

                
    NSLog(dict);
                 result=dict; //wait for response in block........
              } failWithError:^(NSError *error) {
                NSLog(error);
              }];
 NSLog(dict);// than print or return the vaue........
}
@end

```

**Comment by VS-ARC** [comment]
how can i get result of method which return string array........

**Comment by priore** [comment]
please read the our response for the issue #60
