### ISSUE TITLE
Not return response

### ISSUE THREAD

**Issue by TamilRaja** [priore/SOAPEngine#59]
Hello

I have send this url and parameters. How can i send. Already i have sent but some problem is coming.

Sample:
Wsdl : http://82.178.20.92:8080/CRM2/services/SearchBusiness.ws?wsdl
function : getSearchBusiness
Parameters : array( 'businessCode' => '{"businessCode":[ Business Code]}',
'businessName' => 'Business name',
'location' => Location,
'categoryKeyword' => Category Name,
PageNumber' => 1,
'paginationSize' => 10
'languageCode' => ''en
)

I sent this type but issues is came.

[soap setValue:@"businessCode[]" forKey:@"businessCode"];
    [soap setIntegerValue:@"" forKey:@"businessName"];
    [soap setIntegerValue:@"" forKey:@"location"];
    [soap setIntegerValue:@"" forKey:@"categoryKeyword"];
    [soap setIntegerValue:@"1" forKey:@"PageNumber"];
    [soap setIntegerValue:@"10" forKey:@"paginationSize"];
    [soap setValue:@"en" forKey:@"languageCode"]; // or setValue:@"733" forKey:@"category"
    [soap requestURL:@"http://82.178.20.92:8080/CRM2/services/SearchBusiness.ws?wsdl"
          soapAction:@"getSearchBusiness" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
              NSLog(@"Sucess-->%@", dict);
          } failWithError:^(NSError *error) {
              NSLog(@"Erro-->%@", error);
          }];
Please explain me..

**Comment by priore** [comment]
Hi,
you can use setValue method for objects or classes, derived from NSObject, or for empty values (like nil or @""), you can use setIntegerValue for integers, expects an int and not a string. Exist more setValue types for the numeric values (int, float, double, etc), you can use this special methods only for basic numeric values, for other types you can use setValue (like NSNumber, NSString, etc).

note: if you use requestURL not put "?wsdl" at the end of the url

**Comment by TamilRaja** [comment]
I have changed but coming this alert message ERROR : received status code 404.
SOAPEngine Sample[3230:100460] Sended 533 bytes of 533 bytes

**Comment by priore** [comment]
sorry but at address http://82.178.20.92:8080/CRM2/services/SearchBusiness.ws, with or without wsdl, not respond any services, trying with a browser this returns always 404, this is a not error of SOAPEngine but an error of availability of service, the service with this address not be found.

**Comment by TamilRaja** [comment]
Hi
 
   Really sorry.
URL :  http://82.178.20.92:8080/CRM/services/SearchBusiness.ws?wsdl

Method Name : function : getSearchBusiness

[soap setValue:@"businessCode[]" forKey:@"businessCode"];
[soap setIntegerValue:@"" forKey:@"businessName"];
[soap setIntegerValue:@"" forKey:@"location"];
[soap setIntegerValue:@"" forKey:@"categoryKeyword"];
[soap setIntegerValue:@"1" forKey:@"PageNumber"];
[soap setIntegerValue:@"10" forKey:@"paginationSize"];
[soap setValue:@"en" forKey:@"languageCode"];

**Comment by TamilRaja** [comment]
HI i got it soulation but response is coming string method. How to get categoryId and categoryNm.

EX: [{\"categoryId\":734,\"categoryNm\":\"Projector Dealers\",\"categoryNmBl\":\"\U062a\U062c\U0627\U0631 \U0627\U0644\U0639\U0627\U0631\U0636/\U0645\U0633\U0644\U0627\U0637\",\"prntCategoryId\":733},{\"categoryId\":735,\"categoryNm\":\"Computer Dealers\",\"categoryNmBl\":\"\U062a\U062c\U0627\U0631  \U0627\U0644\U062d\U0627\U0633\U0628 \U0627\U0644\U0622\U0644\U064a \",\"prntCategoryId\":733},{\"categoryId\":736,\"categoryNm\":\"Laptop Dealers\",\"categoryNmBl\":\"\U062a\U062c\U0627\U0631 \U0627\U0644\U062d\U0627\U0633\U0628 \U0627\U0644\U0622\U0644\U064a\",\"prntCategoryId\":733},{\"categoryId\":737,\"categoryNm\":\"Printer Dealers\",\"categoryNmBl\":\"\U0627\U0644\U0637\U0628\U0627\U0639\U0629\"}]

**Comment by priore** [comment]
You use the requestURL:soapAction:completeWithDictionary:failWithError: or the deprecated requestURL:soapAction:complete:failWithError ?

If you use the not deprecated method, this returns a dictionary that is easier to use for get of values.
