### ISSUE TITLE
how to read xml

### ISSUE THREAD

**Issue by haiboss** [priore/SOAPEngine#60]
when after call ws return file xlm detail:
  Body =     {
        GetLevel2UnitListResponse =         {
            GetLevel2UnitListResult =             {
                diffgram =                 {
                    NewDataSet =                     {
                        Table =                         (
                                                        {
                                PARENTID = 1;
                                PROVINCECODE = TNH;
                                UNITID = 55;
                                UNITNAME = "Vi\U1ec5n th\U00f4ng T\U00e2y Ninh";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 538;
                                UNITNAME = "TTVT B\U1ebfn C\U1ea7u";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 539;
                                UNITNAME = "TTVT Ch\U00e2u Th\U00e0nh";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 540;
                                UNITNAME = "TTVT D\U01b0\U01a1ng Minh Ch\U00e2u";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 541;
                                UNITNAME = "TTVT G\U00f2 D\U1ea7u";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 542;
                                UNITNAME = "TTVT H\U00f2a Th\U00e0nh";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 543;
                                UNITNAME = "TTVT T\U00e2n Bi\U00ean";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 544;
                                UNITNAME = "TTVT T\U00e2n Ch\U00e2u";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 545;
                                UNITNAME = "TTVT Th\U00e0nh ph\U1ed1 TN";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 546;
                                UNITNAME = "TTVT Tr\U1ea3ng B\U00e0ng";
                            },
                                                        {
                                PARENTID = 55;
                                PROVINCECODE = TNH;
                                UNITID = 590;
                                UNITNAME = "TT \U0110i\U1ec1u h\U00e0nh th\U00f4ng tin";
                            }
                        );
                    };
                };
                schema =                 {
                    element =                     {
                        complexType =                         {
                            choice =                             {
                                element =                                 {
                                    complexType =                                     {
                                        sequence =                                         {
                                            element =                                             (
                                                "",
                                                "",
                                                "",
                                                ""
                                            );
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
How to read data into table cell. Pls help me.

**Comment by haiboss** [comment]
PS : code Swift using SoapEngine. soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://vnpt.vn/GetLevel2UnitList",
            completeWithDictionary: { (statusCode : Int,
                dict : [NSObject : AnyObject]!) -> Void in
                var result:NSDictionary = dict as NSDictionary
                NSLog("%@", result)
                //var book:NSDictionary = dict as NSDictionary
               // var verses:NSArray = book["NewDataSet"] as! NSArray
               // self.verses = verses
               // self.table.reloadData()
            }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)

**Comment by priore** [comment]
Hi

```
        //soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://vnpt.vn/GetLevel2UnitList",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                
                var dataSet:NSDictionary = dict as NSDictionary
                var table:NSArray = dataSet.valueForKeyPath("diffgram.NewDataSet.Table") as! NSArray

            }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)
        }
```

**Comment by haiboss** [comment]
work well for  me. Thanks.

**Comment by haiboss** [comment]
exc-bad-instruction-code-exc-i386-invop-subcode-0x0 in var table:NSArray = dataSet.valueForKeyPath("diffgram.NewDataSet.Table") as! NSArray
Thanks.

**Comment by haiboss** [comment]
i write func:  func Authen(username : NSString ,password : NSString, appID : Int ) -> String{
        var responseFromServer : String = "1"
        var soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.authorizationMethod = SOAP_AUTH_CUSTOM
        soap.licenseKey = "eJJDzkPK9Xx+p5cOH7w0Q+AvPdgK1fzWWuUpMaYCq3r1mwf36Ocw6dn0+CLjRaOiSjfXaFQBWMi+TxCpxVF/FA=="
        soap.header = String(format: "<AuthHeader xmlns=\"http://vnpt.vn/\"><Username>%@</Username><Password>%@</Password><AppID>%i</AppID></AuthHeader>", username, password, appID);
        soap.setValue(username, forKey: "USERNAME")
        soap.setValue(password, forKey: "PASSWORD")
        soap.setIntegerValue(appID, forKey: "AppID")
        soap.requestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
        soapAction: "http://vnpt.vn/CheckAuthen", //GetLevel2UnitList
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                var dataSet:NSDictionary = dict as NSDictionary
                let table:String = dataSet.valueForKeyPath("Body.CheckAuthenResponse.CheckAuthenResult") as! String
                responseFromServer = table
                }) { (error : NSError!) -> Void in
                
                NSLog("%@", error)
        }
        NSLog("%@",responseFromServer)
        return responseFromServer
    }
when call func authen:
....
var str=authen("demo","123",1) 
result retrieve str alway nil
pls help me check and fix  func Authen(). thanks

**Comment by priore** [comment]
you can call the func below : 

```swift
// you can call the func with this code
// var result: String = Authen("Demo", password: "123", appID: 1)
// auth function
func Authen(username : NSString ,password : NSString, appID : Int ) -> String
    {
        var error: NSError?
        var soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.responseHeader = true // use only for non standard MS-SOAP service
        soap.authorizationMethod = SOAP_AUTH_CUSTOM
        soap.licenseKey = "eJJDzkPK9Xx+p5cOH7w0Q+AvPdgK1fzWWuUpMaYCq3r1mwf36Ocw6dn0+CLjRaOiSjfXaFQBWMi+TxCpxVF/FA=="
        soap.header = String(format: "<AuthHeader xmlns=\"http://vnpt.vn/\"><Username>%@</Username><Password>%@</Password><AppID>%i</AppID></AuthHeader>", username, password, appID)
        var result:NSDictionary = soap.syncRequestURL("http://xtestws.vnptphuyen.vn/xtest/LineTestWS.asmx",
            soapAction: "http://vnpt.vn/CheckAuthen", error: &error)
        return result.valueForKeyPath("Body.CheckAuthenResponse.CheckAuthenResult") as! String
    }
```

**Comment by haiboss** [comment]
thanks a lot.
