### ISSUE TITLE
Undeclared general entity "rsquo".

### ISSUE THREAD

**Issue by EricoGT** [priore/SOAPEngine#62]
Hi, I'm using the SOAPEngine in Carrorama application, Going2Mobile company, and through Google Analitycs we found some instances of an exception related to 'rsquo' (right single quotation mark). 
 
 Example: [com.ctc.wstx.exc.WstxParsingException: Undeclared general entity "rsquo" at [row, col {unknown-source}]: [1.1186]].
 
After some testing we came to the conclusion that every parameter text containing the symbol <’> generates this type of exception.
 
It may be a parse problem executed by SOAPEngine or interpretation of web service?
Thank you for your help!

**Comment by priore** [comment]
For to analyze the problem we need data for to call service, in any case, the parsing occurs after the server's response, so it may be a problem derived from the XML that the server returns.

If you can, send us the data to call the service, or the code that you use, even by e-mail.

**Comment by EricoGT** [comment]
Please see this link:
http://www.freeformatter.com/xml-formatter.html

Use this example code (the error is equivalent in the application):
*<?xml version="1.0" encoding="utf-8"?><soap:Envelope
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance
<http://www.w3.org/2001/XMLSchema-instance>"
xmlns:xsd="http://www.w3.org/2001/XMLSchema
<http://www.w3.org/2001/XMLSchema>"
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/
<http://schemas.xmlsoap.org/soap/envelope/>" xmlns:tmp="http://tempuri.org/
<http://tempuri.org/>"><soap:Header></soap:Header><soap:Body><name_user>EricoGT
&rsquo;</name_user></soap:Body></soap:Envelope>*

Error message: Unable to parse any XML input.
org.jdom2.input.JDOMParseException: Error on line 1: The entity "rsquo" was
referenced, but not declared.

The entity 'rsquo' is not recognized by xml. But how can I send it by
SOAPEngine?

There are some other symbols that cause the same problem.



2015-08-06 12:19 GMT-03:00 Prioregroup.com <notifications@github.com>:

**Comment by priore** [comment]
So, you can convert the string to an NSData and send it with SOAPEngine, or you can simply enclose the entire string in a CDATA, eg:

```objective-c
//
// mode 1
//
NSData *d = [@"EricoGT`"  dataUsingEncoding:NSUTF8StringEncoding];
[soap setValue:d forKey:@"name_user"];
//
// mode 2
//
NSString *s = [NSString stringWithFormat:@"<![CDATA[%@]]>", @"EricoGT`"];
[soap setValue:s forKey:@"name_user"];

```

**Comment by EricoGT** [comment]
Hello, 

Turn all the strings in NSData is not a viable option at this time.
CDATA is faster but fragile solution. The user can enter a text containing "]]>" and it would be necessary to protect against this parameter input, generating rework.
I believe that if the xml does not recognize the symbol ’ then the converter should not turn ’ in &rsquo. 
This would be the best solution, keep the symbol as entered. The SOAPEngine could not do that?

**Comment by priore** [comment]
Try with the property named escapingHTML sets to NO.

**Comment by EricoGT** [comment]
Hello!

When you set `soap.escapingHTML = NO` the problem with the &rsquo is solved, but another problem appears. The symbols `<` and `>` are no longer `&lt` and `&gt`, which allows the user to "inject" content in xml package.
See the example:

User input this text in textField:
`My name is ’</name>’.`
(this text fills the 'name' parameter an object).

Using [soap.escapingHTML = YES] xml created is:
`<name>My name is &rsquo;&lt;/name&gt;.&rsquo;</name>`
(here an error occurs in xml because `&rsquo` is not a recognized entity)

Using [soap.escapingHTML = NO] xml created is:
`<name>My name is '</name>'.</name>`
(here an error occurs in xml, as they are interpreted two tags `</name>`)

On Android, our application uses a library called ksoap2, and this type of problem does not occur. Therefore I believe that depends on the library to the treatment of this type of symbol.

Thank you for your cooperation.

**Comment by priore** [comment]
Hi,
was published a new version that fixes the problem of  XML injection

**Comment by EricoGT** [comment]
The last implementation resolved the issue. I appreciate the support. Great library!
