### ISSUE TITLE
How to add the prefix in the attribute variable

### ISSUE THREAD

**Issue by dlpigpen** [priore/SOAPEngine#63]
I'd like to ask the prefix name in the attribute parameter(tem:Name) and name action ("UpdateTeam". Please guide me 

<img width="518" alt="screen shot 2015-08-13 at 5 43 46 pm" src="https://cloud.githubusercontent.com/assets/5404685/9248075/03e0b15e-41e3-11e5-9bd6-92d6cdb2ead4.png">

**Comment by priore** [comment]
Please, read here #61

**Comment by dlpigpen** [comment]
the problem has resolved. Can you close this issue?

**Comment by priore** [comment]
is already closed, thank you ;)
