### ISSUE TITLE
Dsymutil warnings when using Cocoapods

### ISSUE THREAD

**Issue by CoBrA2168** [priore/SOAPEngine#65]
Not sure if this is a Cocoapods specific issue, but it looks like this library is using missing library files.  I'm getting a bunch of dsymutil warnings when using this project on Xcode 6 (iOS SDK 8.4).

See this SO post for more information and a fix:
http://stackoverflow.com/questions/14489692/what-do-these-dsymutil-warnings-mean-in-xcode-4-5

**Comment by priore** [comment]
we created a sample project that uses the podspec, see "Sample SOAPEngine with pods" 33b61e5b48511a685f5e66be9e4cc8d40c212f01, while compiling we do not see warning messages dsymutil, you sure that the problem stems from SOAPEngine ?

**Comment by CoBrA2168** [comment]
I just downloaded the Sample SOAPEngine with Pods file, compiled, and I'm seeing the same 16 warnings on my machine.  I'm using Cocoapods 0.38.2 (the latest as of this writing).

Here are all the warnings I'm seeing:
`warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/NSString+SOAPEngine.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPEngine.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPConnection.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPAES256.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPTFHpple.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPTFHppleElement.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPLicense.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPX509.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPXPathQuery.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPSHA1.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/NSDictionary+SOAPEngine.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPBase64.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPSocial.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/NSData+SOAPEngine.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAPString.o unable to open object file: No such file or directory
warning: (x86_64) /Users/danilo/Library/Developer/Xcode/DerivedData/SOAPEngine-eodoahnfttszzqeljutqohzkwjli/Build/Intermediates/SOAPEngine.build/Release-iphonesimulator/SOAPEngine64.build/Objects-normal/x86_64/SOAP3DES.o unable to open object file: No such file or directory`

**Comment by priore** [comment]
we have Xcode v6.4 (6E35b) and Cocoapods v0.38.2, and this warnings not appear, you have last version of Xcode ?

we note that refers to x86_64  architecture, but this architecture is used when compiling for OSX and not for iOS, please, check the architecture set on the target.

**Comment by CoBrA2168** [comment]
Yes, I'm using the latest version of Xcode with OSX 10.10.5 Yosemite.

This might be a Cocoapods configuration issue then.  Let me see why it's compiling against the wrong architecture.

**Comment by priore** [comment]
Hi,
in our Mac’s, with XCode 6.4, works without showing this warnings, please try to reset XCode settings http://stackoverflow.com/a/21146631

**Comment by priore** [comment]
sorry, we had not seeing the path of the error, it is probably to a wrong compilation of the framework, we provide immediately to update the framework.

**Comment by GispertMG** [comment]
Hi, I know this is a little bit old, but I was having the same issue with Facebook framework. The issue started when I decided to rename and relocate my project folder. When I returned the folder to the original place the issue went off. So I think the problem is that the frameworks keep track of the location of the project and they don't move with the other files.
