### ISSUE TITLE
Autotask API issue

### ISSUE THREAD

**Issue by Alovantous** [priore/SOAPEngine#67]
I am trying to use your software to connect to Autotask's API however the xml being generated does not seem to work.

````xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" ><soap:Header></soap:Header><soap:Body><query xmlns="http://autotask.net/ATWS/v1_5/"><entity>Account</entity><john>firstname</john></query></soap:Body></soap:Envelope>
````

That is the query being generated. Below is some PHP code that is generating a xml snippit to do the same query.

````php
$xml = array('sXML' => "
<queryxml>
        <entity>Account</entity>
        <query>
                    <field>AccountName<expression op='Equals'>IBM</expression></field>
        </query>
</queryxml>");
$result = $client->query($xml);
````

updated to use markdown.

notice how the body of the query is "queryxml" not just query. Any way to do this?

**Comment by priore** [comment]
let's assume that this is the correct code :

```objective-c
    soap.authorizationMethod == SOAP_AUTH_BASICAUTH; // or SOAP_AUTH_BASIC
    soap.username = @"my-username";
    soap.password = @"my-password";
    //soap.responseHeader = YES; // try it only for non standard MS-SOAP services
    [soap requestURL:@"https://webservices.autotask.net/atservices/1.5/atws.asmx"
          soapAction:@"http://autotask.net/ATWS/v1_5/GetWsdlVersion"
completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        
    NSLog(@"Result: %@", dict);

} failWithError:^(NSError *error) {

    NSLog(@"%@", error);

}];
```

note: please, use the markdown when you copy xml or another language code, otherwise without is not readable

**Comment by Alovantous** [comment]
So I tried that code with both `SOAP_AUTH_BASICAUTH` and `SOAP_AUTH_BASIC` and both returned the following:

````xml

{
    br =     {
        b = "Exception Details:";
        br =         {
            br =             {
                b = "Source Error:";
                br =                 {
                    br =                     (
                                                {
                            table = "";
                            tr =                             {
                                td =                                 {
                                    code = "An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.";
                                };
                            };
                        },
                                                {
                            b = "Stack Trace:";
                            br =                             {
                                br =                                 (
                                                                        {
                                        table = "";
                                        tr =                                         {
                                            td =                                             {
                                                code =                                                 {
                                                    pre = "[SoapException]\n   autotask.web.services.Global.Application_AuthenticateRequest(Object sender, EventArgs e) +1095\n   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean completedSynchronously) +69";
                                                };
                                            };
                                        };
                                    },
                                                                        {
                                        b = "Version Information:";
                                        hr = "";
                                    }
                                );
                            };
                        }
                    );
                    comment =                     (
                        " \n[SoapException]\n   at autotask.web.services.Global.Application_AuthenticateRequest(Object sender, EventArgs e)\n   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\n   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)\n",
                        " \nThis error page might contain sensitive information because ASP.NET is configured to show verbose error messages using <customErrors mode=\"Off\"/>. Consider using <customErrors mode=\"On\"/> or <customErrors mode=\"RemoteOnly\"/> in production environments."
                    );
                };
            };
        };
    };
    hr = "";
    i = "Unhandled Execution Error";
}
````

**Comment by Alovantous** [comment]
Any further ideas on this?

**Comment by priore** [comment]
no error detail in response page, because the web services iis have settings "custom errors mode off":

"This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using <customErrors mode=\"Off\"/>."

but if you send a valid username and password, through email, for these services we can perform some tests to better advise you, sorry but without this, we cannot give a best support for you.

**Comment by Alovantous** [comment]
I just sent a email with the username and password the subject line contains this issue number.

**Comment by priore** [comment]
it generates the same error also during call for the declaration of the service (wsdl), even with Safari and after entering the username and password of test. We have the permission, your permission, to contact the Autotask supplier, through email, for to check this ?

**Comment by Alovantous** [comment]
Yes that is fine with me. If they need my approval you can let me know and I will see what I can do.

Jeffrey Bowles
Affordable Computer Techs
705 739 2281

On Sep 16, 2015, at 5:17 AM, Prioregroup.com<http://Prioregroup.com> <notifications@github.com<mailto:notifications@github.com>> wrote:


it generates the same error also during call for the declaration of the service (wsdl), even with Safari and after entering the username and password of test. We have the permission, your permission, to contact the Autotask supplier, through email, for to check this ?

-

**Comment by Alovantous** [comment]
Just wondering if you have had any progress?

**Comment by priore** [comment]
sorry, we sent two emails but still no response from autotask, tomorrow will send another email,

**Comment by Alovantous** [comment]
What email address are you sending the emails too? Maybe I can get some movement from my end for you.


On Sep 20, 2015, at 5:17 PM, Prioregroup.com<http://Prioregroup.com> <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry, we sent two emails but still no response from autotask, tomorrow will send another email,

**Comment by priore** [comment]
we sent to gbriscoe@Autotask.com.

Also trying with SoapUI Mac App, Autotask responds with an Apache error, then we suppose that it is a problem of Autotask server:

**Error loading [https://webservices.autotask.net/atservices/1.5/atws.asmx?wsdl]: org.apache.xmlbeans.XmlException: org.apache.xmlbeans.XmlException: error: Unexpected character encountered: '1'**

we sent another email with reporting this error.
