### ISSUE TITLE
Enterprise license

### ISSUE THREAD

**Issue by Persilos** [priore/SOAPEngine#69]
Hi, i have a question about license.
I know single license is just for one app (using appid of our app), but how the enterprise license work ?
Thanks you

**Comment by priore** [comment]
Hi,
you can read the difference in the "general license ios.pdf" paragraph 4 and paragraph 6.

in short; with a single license you can be use SOAPEngine in only one app, (license associated with one app bundle-id), with a enterprise license you can use SOAPEngine with all apps of your organization (license associated with an one organization bundle-id, in this last case for more apps).
