### ISSUE TITLE
Issue in passing parameters

### ISSUE THREAD

**Issue by yagneshb** [priore/SOAPEngine#70]
Hi,
as we talk on tweet, i m trying to call wcf service in swift using SOAPEngine.I use below code to pass the parameters but their values becomes null at server side 

       for (key , value) in paramsDict {
           soap.setValue(value, forKey:key as! String)
       }

Instead using for loop If i set static values like:

 soap.setValue("value", forKey:"key")

then it works properly. How to solve this problem and also how to pass parameters in one object?

**Comment by priore** [comment]
this works fine for us :

```swift
        let values = ["BookName": "Genesis", "chapter": "1"]
        for (key, value) in values {
            soap.setValue(value, forKey: key);
        }
        soap.requestURL("http://www.prioregroup.com/services/americanbible.asmx",
            soapAction: "http://www.prioregroup.com/GetVerses",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                var book:Dictionary = dict as Dictionary
                var verses:NSArray = book["BibleBookChapterVerse"] as! NSArray
            }) { (error : NSError!) -> Void in
                NSLog("%@", error)
        }
```

the "value" is a object (string or like) or a numeric base type (int, long, float, etc.) ?

**Comment by yagneshb** [comment]
"value" is string or textfield's text

**Comment by priore** [comment]
the setValue method accepts all object types, even user objects, excluding numerical basic types for this case you can use setIntegerValue o setFloatValue etc, it is not necessary to specify "as! String", try removing this cast.

**Comment by yagneshb** [comment]
ok thanks.How to pass object?
 I have user object which contains user details like birthdate,name etc for that i use 

  soap.setValue(value, forKey: "userObj")

here values is dictionary of user details then its not working.

**Comment by priore** [comment]
SOAPEngine, the setValue method, support complex user objects, with standard objects (NSString, NSDictionary, NSArray etc.), numerical type base (int, long, float etc.) and user objects containing others objects user. The SOAP message is composed with TAGs named like property names.
