### ISSUE TITLE
Application crashed when call requestWSDL() method

### ISSUE THREAD

**Issue by Persilos** [priore/SOAPEngine#71]
Hi Priore,
I have a problem when i call the requestWSDL method.
I give you my informations of my webservice:
REQUESTURL: http://vps47767.ovh.net:8080/Wall4u/services/WSProject?WSDL
NAMESPACE: http://interfaces.webservices.project.generycs.be/
SOAPACTION: checkLogin

Here is my configuration of my SOAP object
<img width="730" alt="capture d ecran 2015-09-18 a 16 07 39" src="https://cloud.githubusercontent.com/assets/8830732/9961119/0e94bdf4-5e1f-11e5-93d8-db8878be9e1b.png">

And here the moment when i call my webservice
<img width="790" alt="capture d ecran 2015-09-18 a 16 06 54" src="https://cloud.githubusercontent.com/assets/8830732/9961126/1a4f8dcc-5e1f-11e5-8685-ad139d53dd82.png">

WebService is an Apache CXF WS.

My application crash with the message:
2015-09-18 16:09:24.588 Wall4U[16188:582938] -[__NSCFConstantString firstObject]: unrecognized selector sent to instance 0x102fb6060

2015-09-18 16:09:24.595 Wall4U[16188:582938] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString firstObject]: unrecognized selector sent to instance 0x102fb6060'

I really dont understand, all seems me right...

Regards

**Comment by priore** [comment]
don't use requestWSDL because it's slow, also in the wsdl the soapAction attribute is empty, but is needed for requestWSDL. Try using requestURL, much faster, like below:

```swift
        soap.envelope = "xmlns:svc=\"http://interfaces.webservices.project.generycs.be/\""
        soap.requestURL("http://vps47767.ovh.net:8080/Wall4u/services/WSProject", soapAction: "svc:checkLogin",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                
                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })
```
