### ISSUE TITLE
bitcode Xcode 7

### ISSUE THREAD

**Issue by mrhaxic** [priore/SOAPEngine#72]
Hi

I updated the framework and when I try to run the build still show me this error

ld: '/Users/**/Desktop/Desktop 2/*/*/SOAPEngine64.framework/SOAPEngine64(SOAPEngine64-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

What we must to do my dear ?

Thanks

**Comment by priore** [comment]
Xcode 7.0 is yet unstable for to compiling a version of the framework, you can already find the version 7.1 beta pre-release, we waiting this new release for compiling a new version of our framework. At this time we recommend to set ENABLE_BITCODE to NO for your target, we release soon a new version compiled with Xcode 7.1.

Thanks for your patience.

**Comment by priore** [comment]
Please, verify if this latest version 1.22 fixes the problem of bitcode

thanks

**Comment by mrhaxic** [comment]
Thanks.
