### ISSUE TITLE
data parameter is nil

### ISSUE THREAD

**Issue by PatricioIN** [priore/SOAPEngine#73]
Hi!!

I´m trying use this library but I have a crash in my proyect. I think I'm doing all right but.... Maybe not

  2015-09-23 09:25:54.903 [14887:1851561] Initializing SOAPEngine '1.21.1'
data parameter is nil

 var soap = SOAPEngine()
        soap.actionNamespaceSlash = true
        soap.setFloatValue(42.2222222, forKey: "Latitud")
        soap.setFloatValue(-8.7777777, forKey: "Longitud")
        soap.requestURL("http://sira.intecoingenieria.com/SWEstimacionParada.asmx", soapAction: "http://tempuri.org/BuscarParadas",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                println(dict)
                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })

Any ideas?

Thank you very much

**Comment by priore** [comment]
the xml definition of response does not contain an encoding type, is a unusual, look below:
```
<?xml version="1.0" standalone="no"?>
```
usually a soap message contains the encoding type, to correctly decode the soap message, like below:
```
<?xml version="1.0" encoding="utf-8"?>
```
if this is not present, SOAPEngine decoding the message using a standard ASCII encoding, but in this case the message contains special characters compatible only with a UTF-8 or UTF-16.

If you have access to the server, you must change the service, or its definition, so that it returns the right encoding type.

**Comment by priore** [comment]
sorry, we view that the soap message contains the utf-8 encoding type, but this message contains, inside, another XML message with a wrong encoding type, this generate a loss of the original encoding type.

**Comment by PatricioIN** [comment]
Hi Priore.

Thank you very much for your fast response. I will wait for the fix.

Congratulations for this Library, very useful

Greetings

**Comment by PatricioIN** [comment]
Hi Priore.

Thank you very much for fix it very fast.

I wrote pod 'SOAPEngine' in my Podfile for setup my proyect with your fix but I have the same error. What I´m doing wrong? Thank you very much

Greetings,
Patrick

**Comment by priore** [comment]
sorry, set the property named `retrievesAttributes = true`

**Comment by PatricioIN** [comment]
Sorry Priore but I continue with the crash.

var soap = SOAPEngine()
soap.actionNamespaceSlash = true
soap.retrievesAttributes = true
soap.setFloatValue(42.2222222, forKey: "Latitud")
soap.setFloatValue(-8.7777777, forKey: "Longitud")
soap.requestURL("http://sira.intecoingenieria.com/SWEstimacionParada.asmx", soapAction: "http://tempuri.org/BuscarParadas",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                println(dict)
                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })

Can you see something wrong with my code?

Greetings

**Comment by priore** [comment]
this code, below, work right

```swift
        let soap = SOAPEngine()
        soap.actionNamespaceSlash = true
        soap.retrievesAttributes = true
        soap.setFloatValue(42.2222222, forKey: "Latitud")
        soap.setFloatValue(-8.7777777, forKey: "Longitud")
        soap.requestURL("http://sira.intecoingenieria.com/SWEstimacionParada.asmx", soapAction: "http://tempuri.org/BuscarParadas",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                
                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })
```
which crash or error returns?

**Comment by PatricioIN** [comment]
Same error,

"data parameter is nil"

I have reset my proyect with cocoaPods (pod install, pod setup) 

Greetins

**Comment by priore** [comment]
I apologize, the last podspec had not been pushed to cocoapods, you try again now with pod update

**Comment by PatricioIN** [comment]
I´m sorry Priore but I continue with de same error

"data parameter is nil"

:(

**Comment by priore** [comment]
The last version of our framework is 1.22, you sure to have this last versione ?... please, verify the version number in the SOAPEngine.h, the code we've written above works well, and write again below:

```
        let soap = SOAPEngine() // try to declare soap var outside here, like var soap = [SOAPEngine]()
        soap.actionNamespaceSlash = true
        soap.retrievesAttributes = true
        soap.setFloatValue(42.2222222, forKey: "Latitud")
        soap.setFloatValue(-8.7777777, forKey: "Longitud")
        soap.requestURL("http://sira.intecoingenieria.com/SWEstimacionParada.asmx",
            soapAction: "http://tempuri.org/BuscarParadas",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in

                let result:Dictionary = dict as Dictionary
                NSLog("%@", result)
                
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })
```

**Comment by PatricioIN** [comment]
Thank you very much.

I did pod clean and then pod install and now cocoaPods download the correct version that you said, 1.22

Bug fixed, great library and great job.

Greetings

**Comment by priore** [comment]
because of an wrong compilation the binaries has been updated, please download last binaries or if you use cocoapods run again "pod install", thanks for your patience.

If you are satisfied with the support for this issue, please close the issue, thanks.
