### ISSUE TITLE
data parameter is nil

### ISSUE THREAD

**Issue by PatricioIN** [priore/SOAPEngine#76]
Good afternoon! 

Some days ago I found a issue, fixed at moment. But now I have found the same error in other petition:

        let soap = SOAPEngine()
        soap.actionNamespaceSlash = true
        soap.retrievesAttributes = true
        soap.setValue("20", forKey: "IdParada")
        soap.requestURL("http://sira.intecoingenieria.com/SWEstimacionParada.asmx", soapAction: "http://tempuri.org/EstimacionParadaIdParada",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                let result: NSDictionary = dict as NSDictionary
            }, failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })

I recieve "data parameter is nil"

Thank you very much

**Comment by priore** [comment]
Hi, try setting the property called responseHeader to true.

**Comment by PatricioIN** [comment]
Hi.

I added the property responseHeader but I don´t recieve results. I attach the file.

![header](https://cloud.githubusercontent.com/assets/12427357/10169694/947ab53e-66d2-11e5-821f-70139a4f53a1.png)

Greetings

**Comment by priore** [comment]
ok, we will fix the problem by tomorrow and release a new update, thanks for your patience.
