### ISSUE TITLE
convert StringJSON to NSarray

### ISSUE THREAD

**Issue by haiboss** [priore/SOAPEngine#78]
I have string JSON 
[{"StoreID":3,"StoreName":"Hồng Ngọc","Address":"eqweqweddd","Phone":"eqweq","BeginDate":"\/Date(1441040400000)\/","EndDate":"\/Date(1443546000000)\/"},{"StoreID":2,"StoreName":"Cafe Thái","Address":null,"Phone":null,"BeginDate":"\/Date(1422637200000)\/","EndDate":"\/Date(1440954000000)\/"},{"StoreID":4,"StoreName":"Huy Tùng","Address":"111","Phone":"111","BeginDate":"\/Date(1441040400000)\/","EndDate":"\/Date(1443546000000)\/"},{"StoreID":5,"StoreName":"Cafe Việt","Address":"weq","Phone":"eqweq","BeginDate":"\/Date(1441040400000)\/","EndDate":"\/Date(1443546000000)\/"},{"StoreID":6,"StoreName":"aaaa","Address":"aa","Phone":"aaaa","BeginDate":"\/Date(1441040400000)\/","EndDate":"\/Date(1443546000000)\/"}]

i'm convert to NSArray. pls help me. thx

**Comment by priore** [comment]
```objective-c    
NSData *data = [your-string dataUsingEncoding:NSUTF8StringEncoding];
NSArray *array = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:nil];
```

this is a general question, not related to SOAPEngine, please use http://stackoverflow.com for these generic issues.

thanks.
