### ISSUE TITLE
Stream 0x1565c4130 is sending an event before being opened

### ISSUE THREAD

**Issue by IuliuMoga** [priore/SOAPEngine#79]
When calling  [soap requestURL:self.url
                     soapAction:soapAction
         completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {}
I get Stream 0x1565c4130 is sending an event before being opened but if I'm waiting 1-2 seconds before invoking this function then everything is working.

This always happens but the soap is executed if the soapAuthorization is NONE, but i need BASIC_AUTH wich sometime works and sometimes not.

**Comment by IuliuMoga** [comment]
I think that i've solved it somehow, it was from my data cache it used wrong credentials and leaved the auth to NONE, but the "Stream 0x1565c4130 is sending an event before being opened " still appears but also the SOAP actions are executed with success even with that warning.

**Comment by IuliuMoga** [comment]
Hmmmm not solved yet here is the actual problem of how to reproduce it.
1. Execute a soap from a service A with credentials from service A
2. Execute a soap from a service B with credentials from service A => Authenticate error wich is ok
Now:
3. Execute a soap from a service B with credentials from service B => Authenticate ok and SOAP success
4. Execute a soap from service B with any credentials or dummy credentials => Authenticate OK and SOAP from service B is executed instead of getting Auth error.

**Comment by priore** [comment]
The issue with Stream not Open seems to be directly in CFNetwork implementation from iOS8 and higher. (reproducible when using NSConnection like SOAPEngine). A side-effect of this issue is that windows authentication is not working properly and each request needs to go through complete handshaking process. We investigate more.

**Comment by IuliuMoga** [comment]
@priore Thanks for this again, i knew somehow that are new stupid IOSes problems.

**Comment by priore** [comment]
in any case, try adding the user name in the url of the service, like http://username@url-service, try if it works, we not tried it yet.
