### ISSUE TITLE
add parameters in specific order to soap request

### ISSUE THREAD

**Issue by RexArne** [priore/SOAPEngine#81]
I am exploring the free version of soapEngine to see it is something I can use im my project. So far, it has been very useful. However, I want to a web service with several operations. Some of them need parameters in a specific order. Like the one below. I can't get this to work.

![schermafbeelding 2015-10-11 om 19 41 51](https://cloud.githubusercontent.com/assets/15077711/10418039/4dc0e4d8-7050-11e5-8406-184b19d972e0.png)

![schermafbeelding 2015-10-11 om 21 01 53](https://cloud.githubusercontent.com/assets/15077711/10418435/6fbb43ac-705b-11e5-9a85-bbcd8e858f77.png)

I use requestURL Method where I pass in a dictionary with the required parameters, but it seems the values are not in the correct order. 
Can you give me directions how to handle this. I am fairly new to Swift and Soap web services.

**Comment by priore** [comment]
please, look #77

**Comment by RexArne** [comment]
I must have overlooked issue 77 in my search for an answer. sorry. Anyway, THANKS. It is working!
Another question. In soapEngine.h it says that all the requestURL methods without a dictionary
 are deprecated. why is that? Some of my operations just give a String as response. It works with a dictionary, but only if soap.responseHeader = true

**Comment by priore** [comment]
A standard Microsoft SOAP message contains the response data in predefined tags, some not standard SOAP services return data without these predefined tags.
In this case not can retrieve the data accurately, for this is available the property named responseHeader, for recover complete SOAP message regardless of its structure.
The methods that return the XML in string format has been deprecated in favor of ones that return a dictionary, in this case you do not need use a more XML parser.

**Comment by RexArne** [comment]
Thanks for the explanation!
