### ISSUE TITLE
how to provide username and password for a soap request in Swift?

### ISSUE THREAD

**Issue by aleemilu75** [priore/SOAPEngine#82]
Swift 2.0
soap.requestWSDL

**Comment by priore** [comment]
I did not understand, access to the service definition (WSDL) is protected by a password?
or only the service? (usually)

**Comment by aleemilu75** [comment]
Yes access to the service definition (WSDL) is protected by a password.

 let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = true
        soap.setValue("spdbs_app", forKey: "spdbs_app")
        soap.requestWSDL("http://spdbs-esb-dev.linux.rz.db.de:7302/CallProcessingV2/CallProcessingApp.Proxy?wsdl",
            operation: "createCall",
            value: "spdbs_app",
            forKey: "spdbs_app",
            completeWithDictionary: { (statusCode: Int, dict : [NSObject: AnyObject]!) -> Void in
                
                var result: NSDictionary = dict as NSDictionary
            },
            failWithError: { (error : NSError!) -> Void in
                NSLog("%@", error)
        })

I am Getting this error - 
SOAPEngine Swift[3283:94422] Error Domain=SOAPEngine Code=135 "Could not authenticate you" UserInfo={NSLocalizedDescription=Could not authenticate you, 
NSLocalizedFailureReason=<NSHTTPURLResponse: 0x7f9252fbad30>
 { URL: http://spdbs-esb-dev.linux.rz.db.de:7302/CallProcessingV2/CallProcessingApp.Proxy }

**Comment by priore** [comment]
so, in your browser if you write the url address followed by "?wsdl" appear requesting a username and password ?... in this case, the username and password must be written in the url address, like http://username:password@your-url?wsdl

In any case not advisable to use WSDL request because it is very slow, you look for the soapAction value from WSDL declaration and use it in the requestURL method.

**Comment by aleemilu75** [comment]
yes after writing the url address followed by "?wsdl" i need to provide a username and password.

as i am new to ios n swift in particular , how can i give username n pwd for an individual service?
also how i need to pass parameters to an particular service.?

**Comment by aleemilu75** [comment]
Still its not working .
Error : SOAPEngine connection fail! - The operation couldn’t be completed. (NSURLErrorDomain error -1012.)

**Comment by aleemilu75** [comment]
how can i use wsdl using "requestURL method"? how to get soap action value ?

**Comment by priore** [comment]
How to specify a username/password for the service, please search for "SOAP Authentication" on the main page of SOAPEngine on GitHub, there are many examples.

For soapAction, search the "soapAction" text in the WSDL, every function of the service have its soapAction, if not found, you can use "operation location" or "operation name". If you not are familiar with WSDL, you can send it to us and we examine for you.
