### ISSUE TITLE
Tags <item> <input> and invalid type url.

### ISSUE THREAD

**Issue by EricoGT** [priore/SOAPEngine#84]
Hello guys!

Please, I have two questions:

1) In previous versions, when assigning a list (NSArray) as the value of a parameter, the xml generated created the `<item>` for each element of the list. Now it is being created `<input>` tag. For my job, I need to remove this tag manually. This new tag `<input>` is final or coexists with the previous one?

2) When running for the first time the application on the device (or simulator), the console displays the message `"SOAPEngine invalid type url!"`. In successive it does not appear and the application works normally. This message prevents the delegate is activated and clutters the application flow. Why this message appears exactly? How can I avoid?

Thank you!!

**Comment by priore** [comment]
Hi Erico,

1) the property named `defaultTagName` specifies the name of the items in an array, default value is `input`, you can set this as you prefer (eg `item`) or set it to nil to completely remove the tag.

2) the first parameter of the requestURL expects a url on NSString type or NSURL type, if it is not one of this types you will see this message and the request cannot be processed.

**Comment by EricoGT** [comment]
Good afternoon!

1) Very good! I had not noticed this property, sorry.

2) The address of my server is in the code itself, static (NSString), I do
not understand why this message appears occasionally. I can not simulate
all the time, but I noticed that began to appear in v.1.24 version that I
downloaded recently.


2015-10-20 19:42 GMT-02:00 Prioregroup.com <notifications@github.com>:

> Hi Erico,
>
> 1) the property named defaultTagName specifies the name of the items in
> an array, default value is input, you can set this as you prefer (eg item)
> or set it to nil to completely remove the tag.
>
> 2) the first parameter of the requestURL expects a url on NSString type or
> NSURL type, if it is not one of this types you will see this message and
> the request cannot be processed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/priore/SOAPEngine/issues/84#issuecomment-149711691>.
>



-- 
Érico G. Teixeira
Computational Enginner   |   iOS Developer
 15 98119-5877  |    erico.gimenes@gmail.com
 lord.erico  |    ericogt <https://br.linkedin.com/in/ericogt>

**Comment by priore** [comment]
You can send the code where this problem appears frequently ?
If it contains confidential data you can send it by e-mail, we will use it only for to try and find this problem.

thanks

**Comment by EricoGT** [comment]
The call is very simple. See the example for a user login (IP omitted, methods names changed):

```
NSString *serverAdress =@"http://00.0.00.00:8080/G2M/CarroramaService?wsdl";
 [soap requestURL:serverAdress soapAction:[NSString stringWithFormat:@"%@%@", SYNC_NAMESPACE_COMPLETE, SYNC_LOGIN_METHOD]];
```
SYNC_NAMESPACE_COMPLETE is a #define: @"http://Service.WebService.Carrorama/".
SYNC_LOGIN_METHOD is a #define: @"syncLogin".

The serverAdress variable never changes, but occasionally the message `"SOAPEngine invalid type url!"` appears.

**Comment by priore** [comment]
don't use ?wsdl in requestURL, remove ?wsdl from url and try again

**Comment by EricoGT** [comment]
I will test it as soon as possible, but I think is not the cause of the problem. I use SOAPEngine almost four months and always worked well, even using `?wsdl`.
The message does not appear always, for this reason I can not simulate purposely.

**Comment by priore** [comment]
the our code, where the message is generated, it is very simple, there's nothing before:
```objective-c
    NSURL *_url = nil;
    // asmxURL is name of untyped param
    if ([asmxURL isKindOfClass:[NSString class]]) {
        _url = [NSURL URLWithString:asmxURL];
    } else if ([asmxURL isKindOfClass:[NSURL class]]) {
        _url = (NSURL*)asmxURL;
    } else {
        NSLog(@"SOAPEngine invalid type url!");
        NSCAssert(YES, @"SOAPEngine invalid type url!");
        return;
    }
    //
    // code for to elaborate _url
	//
```

**Comment by EricoGT** [comment]
Your code is accurate, it is not his fault.

I found a point in application that the login method is different:
````
dispatch_async (dispatch_get_main_queue(), ^{
		NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
        NSString *serverAdress = [userDefaults objectForKey:@"syncServerAddress"];
        [soap requestURL:serverAdress soapAction:[NSString stringWithFormat:@"%@%@", SYNC_NAMESPACE_COMPLETE, SYNC_LOGIN_METHOD]];
});
```
Although the key exists in userDefaults, I do not know if the value is valid in all cases. It can also be an error with the asynchronous process.
I appreciate your help. I believe that the problem exists within the application logic.

**Comment by priore** [comment]
and we'll do more tests to examine if all properties are thread-safe, thanks.
