### ISSUE TITLE
How can i add a HEADER value

### ISSUE THREAD

**Issue by jboehler** [priore/SOAPEngine#85]
Hello 

How can i add a header-field to the HTTP request.

examples:

    Cookie: name=value
    Accept-Language: en-US
    Accept-Charset: utf-8

At the moment Cookie is importer for me?

How can i do that?

With Basic Objective-C i do it with:

    NSMutableURLRequest* request = [[NSMutableURLRequest alloc] initWithURL:url];
    [request setValue:VALUE forHTTPHeaderField:@"Field You Want To Set"];

**Comment by priore** [comment]
Hello,
you can use the didBeforeSendingURLRequest delegate.

**Comment by jboehler** [comment]
Thx for the hint will try it out
