### ISSUE TITLE
Problem getting successful response from soap web service

### ISSUE THREAD

**Issue by archerlog** [priore/SOAPEngine#86]
Hi,
I have having troubles trying to get a successful respond from my localhost soap web service.
Below is my code:

    soap = [[SOAPEngine alloc] init];
    soap.userAgent = @"SOAPEngine";
    soap.delegate = self;
    soap.version = VERSION_1_1;
    soap.actionNamespaceSlash = YES;
    
    [soap setValue:@"12345" forKey:@"publicWebKey"];
    [soap setValue:@"56789" forKey:@"publicTokenValue"];
    [soap setLongValue:9999 forKey:@"publicTokenTime"];
    [soap requestURL:@"https://10.10.10.86:8443/ecmPublicService/PublicExampleWebService"
          soapAction:@"http://publicservice.ecm.com/showExample"];

I've already open up the the HTTPS connection and can connect to my web service.

However every time I run the error I got was:

SOAPEngine Server response: Unmarshalling Error: unexpected element (uri:"http://publicservice.ecm.com/", local:"publicWebKey"). Expected elements are <{}publicWebKey>,<{}publicTokenTime>,<{}publicTokenValue>
2015-12-09 16:05:22.009 SoapEngineDemo[2509:96366] Error: Unmarshalling Error: unexpected element (uri:"http://publicservice.ecm.com/", local:"publicWebKey"). Expected elements are <{}publicWebKey>,<{}publicTokenTime>,<{}publicTokenValue>

How can I fix this?

Regards,

**Comment by priore** [comment]
Hi,
this not an error SOAPEngine, suppose is an error of the service, written in Java (java.xml) but we do not know Java to be able to provide a support, in this case you can find the answer on Google or StackOverflow, sorry.
