### ISSUE TITLE
Cannot request WSDL

### ISSUE THREAD

**Issue by gauuni** [priore/SOAPEngine#87]
I used this method:
[soap requestWSDL:@"http://dev.mibet.co/sserver.v2/userwsdl.php?wsdl" operation:@"User.checkUsername" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {  
    } failWithError:^(NSError *error) {
    
}];

And it always return this:
SOAPEngine missing Content-Length in the header of the HTTP response or its value is equal zero!
Please help me out!

**Comment by priore** [comment]
Hello,
below the correct use for your service :

```objective-c
    soap.envelope = @"xmlns:urn=\"urn:memberwsdl\"";
    [soap setValue:@"Nguyen" forKey:@"user"];
    [soap requestURL:@"http://dev.mibet.co/sserver.v2/userwsdl.php" soapAction:@"urn:User.checkUsername" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        
        NSLog(@"StatusCode: %i", (int)statusCode);
        NSLog(@“Response: %@", dict);
        
    } failWithError:^(NSError *error) {
        
        NSLog(@"%@", error);
    }];
```

But your service returns 403 (Forbidden) without content on response (content-lenght = 0).

**Comment by arvind8192** [comment]
// service url with WSDL, and operation (method name) without tempuri
    [soap requestWSDL:@"http://192.168.4.9:82/flexi-wtp-1.0.0/soap.php?wsdl"
            operation:@"Get menu"

i am having problem to call webservice 
please provide me code in iOS

i am trying from 2 days

**Comment by priore** [comment]
for "operation" param, open the wsdl with your browser and identify the value of the soapAction attribute in the wsdl, but do not recommend using requestWSDL, instead use requestURL, read here:

https://github.com/priore/SOAPEngine#optimizations
