### ISSUE TITLE
Reading data returned by the service

### ISSUE THREAD

**Issue by samuelrabini** [priore/SOAPEngine#90]
Hi,

I'm calling my WebService this way:

        soap = [[SOAPEngine alloc] init];
        soap.delegate = self;
        soap.userAgent = @"SOAPEngine";
        soap.licenseKey = @"eJJDzkPK9Xx+p5cOH7w0Q+AvPdgK1fzWWuUpMaYCq3r1mwf36Ocw6dn0+CLjRaOiSjfXaFQBWMi+TxCpxVF/FA==";
        soap.envelope = @"xmlns:tns=\"http://webservices.telematrix.com/\"";
        
        [soap setValue:username forKey:@"username"];
        [soap setValue:password forKey:@"password"];
        
        [soap requestURL:@"http://ws.telematrix.com/LoginService/Login"
              soapAction:@"tns:Login"];

and it works fine. I mean, I receive the correct reponse.
The problem is that I do not know how to read it.
This is the XML answer:

    <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:LoginResponse xmlns:ns2="http://webservices.telematrix.com/"><return>1213921275</return></ns2:LoginResponse></S:Body></S:Envelope>

And this is the didFinishLoading delegate:

    NSLog(@"stringXML: %@", stringXML);
    NSDictionary *result = [soapEngine dictionaryValue];
    NSLog(@"Result: %@", result);

stirngXml is correctly valued, result it's empty.
The web service is returning the LoginResponse object (as from the WSDL).
Can you please help me reading and using the repsponse?

Thanks,
Samuel

**Comment by priore** [comment]
Hi, try setting the property called responseHeader to true, this property is used for a not standard services.

**Comment by samuelrabini** [comment]
It worked!
This is the dictionary:

    {
    Body =     {
        LoginResponse =         {
            return = 1213928063;
        };
    };
    }

Many thanks
