### ISSUE TITLE
Swtich off info messages

### ISSUE THREAD

**Issue by samuelrabini** [priore/SOAPEngine#91]
Hi,
how can I switch off these messages:

    2016-01-20 17:30:41.353 EvoMobile[10653:433618] Initializing SOAPEngine v.1.250000
    2016-01-20 17:30:41.376 EvoMobile[10653:433618] SOAPEngine missing Content-Length in the header of the HTTP response or its value is equal zero!

thanks

**Comment by priore** [comment]
please read last message of issue #88 (https://github.com/priore/SOAPEngine/issues/88#issuecomment-167961530)

**Comment by samuelrabini** [comment]
Thanks,
Samuel

Da:  "Prioregroup.com" <notifications@github.com>
Risposta:  priore/SOAPEngine <reply@reply.github.com>
Data:  mercoledì 20 gennaio 2016 17:43
A:  priore/SOAPEngine <SOAPEngine@noreply.github.com>
Cc:  Samuel Rabini <samuel.rabini@gmail.com>
Oggetto:  Re: [SOAPEngine] Swtich off info messages (#91)


please read last message of issue #88 (#88 (comment))

**Comment by samuelrabini** [comment]
And what bout the message?

Initializing SOAPEngine v.1.250000





Da:  "Prioregroup.com" <notifications@github.com>
Risposta:  priore/SOAPEngine <reply@reply.github.com>
Data:  mercoledì 20 gennaio 2016 17:43
A:  priore/SOAPEngine <SOAPEngine@noreply.github.com>
Cc:  Samuel Rabini <samuel.rabini@gmail.com>
Oggetto:  Re: [SOAPEngine] Swtich off info messages (#91)


please read last message of issue #88 (#88 (comment))

**Comment by priore** [comment]
**Initializing SOAPEngine v.1.250000**
_Informs the version of the framework you're using, it's just a message for debugging during development._

**missing Content-Length**
_This message warns that not have cognition of the real size of the received data but this size is necessary only for the delegate named didReceiveDataSize._

Others messages are displayed on console, only warnings that not affect on your app or for the review by Apple, but inform and help the developer during the development of the app.
