### ISSUE TITLE
Magento SOAP - Procedure 'catalog_category.tree' not present

### ISSUE THREAD

**Issue by 99xs** [priore/SOAPEngine#93]
Hi there,
For some reason I cannot run SOAP v2 on my server (i get strange errors that I haven't been able to sort out). Soap v1 calls work though. One small issue I have. On some of the calls, when I run the following call I get the following error: Procedure 'method.name' not present.

My code looks like this:

        let soap = SOAPEngine()
        soap.userAgent = "SOAPEngine"
        soap.actionNamespaceSlash = false
        soap.selfSigned = true
        soap.version = VERSION_1_1
        soap.envelope = "xmlns:urn=\"urn:Magento\""

        soap.setValue(token, forKey: "sessionId")
        soap.requestURL("http://fakeurl.com/api/soap/?wsdl",
            soapAction: "catalog_category.tree",
            completeWithDictionary: { (statusCode : Int, dict : [NSObject : AnyObject]!) -> Void in
                var result:Dictionary = dict as Dictionary
                NSLog("%@", result)
            }) { (error : NSError!) -> Void in
                NSLog("%@", error)
        }

Could you please give a hand? Thank you in advance.

**Comment by priore** [comment]
try with soap.responseHeader = YES and make sure the soapAction 'catalog_category.tree' is present in the wsdl, if you want we can help more but we need to read the wsdl.

**Comment by 99xs** [comment]
I don't know why, if I call using a normal php file like the one below it will return something, but from xcode it returns not present.

    $client = new SoapClient('http://fakeurl.com/api/soap/');
    $session = $client->login('test', 'test1234');

    //$result = $client->call($session, 'catalog_category.info', '5');
    //$result = $client->call($session, 'catalog_category.tree');
    $result = $client->call($session, 'sales_order.list');

    ?>
    <pre>
	    <?php print_r($result); ?>
    </pre>

**Comment by priore** [comment]
try with soapAction: "urn:Mage_Api_Model_Server_HandlerAction#sales_order.list"

**Comment by 99xs** [comment]
thank you. It works.
