### ISSUE TITLE
trial version Alert

### ISSUE THREAD

**Issue by RexArne** [priore/SOAPEngine#95]
In the past month I have been building my app using SOAPEngine (v1.24). I bought a single license for it. Today with archiving the app a bitcode error appeared. In the Issues I read that this has been solved in 1.25. so I downloaded the latest version of SOAPEngine and added to my project. When running the app on my device a Alert appears that I am using a trial version. I have not changed the bundle Identifier (only the version number).
How do get my app working again on a device?

thx

**Comment by priore** [comment]
Hello, try with sample included, if in this case the message does not appear on your device then you have changed the bundle-id of your app, maybe a single or more characters with different upper or lower case, if the problem persists even with sample app, please contact again.

**Comment by RexArne** [comment]
the sample included in the zip works on my device. I double checked the Bundle Identifier. I is exactly the same. I loaded an old version where everything is working fine. copied the bundle identifier and used that in the new version, but no succes.

Maybe It is the way I updated the framework. What I did is download the zip from GitHub. deleted the old framework from my project and dragged the new one in. On simulator it works fine.

**Comment by priore** [comment]
Perhaps a wrong copy of license code  ?.. try to copy it from old project

**Comment by RexArne** [comment]
No thats not it. I have been able to reproduce the issue.
I took a branch of a commit before I added de new SoapEngine Framework. This one works fine on my device (with soapEngine v1.24). Next, In the projectNavigator I deleted the SoapEngine framework and dragged the new version of de framework from Finder in to the Xcode project. -> Running fine on simulator, But when running on device it shows the trial version alert. 
I did not change anything in the bundleId or the license code.

**Comment by priore** [comment]
We tried with your same steps, but did not give us any trial message :(

You have tried a new empty project but with the same bundle and license ?

You can send a email to us with your project so we can see where the problem is located ?
note: the copy of your code will remain confidential and will not be used in any way for to reproduce your work, it will be used only to check the issue, and after this control we will remove from our computers.

**Comment by RexArne** [comment]
Yes I have tried empty project. Same result.
I cannot send the code without consulting client. 

I have used the included sample project to prepare something for you. I added the 1.24 version of the SOAPEngine framework. Next, I changed the bundle ID to my own bundleID along with the license code.
Works fine on my device.
Next I repeated the steps I wrote before (adding de v1.25 framework). -> running on my device results in Trial version alert again. So I can send you the sample project

**Comment by priore** [comment]
We have taken the code sample you sent us and we executed the following steps :

1. downloaded framework from github.
2. removed framework 1.24 from your sample.
3. drag the new framework on xcode project.
4. run on the device (iphone 6 with ios 9.2).

no trial messages appear on device, can you give me information on your device?
sorry we do not know how else we can help you.

**Comment by RexArne** [comment]
My device is an iPhone 6S, with iOS 9.2.1.

**Comment by RexArne** [comment]
In the meantime I have tried it on  several devices. Same result. I asked a colleague to do the removing and adding on his mac. Same result. 
I installed the new version via Cocoapods. Same result. I'm starting to believe that my license key has a version limit. is that possible? Did you find anything in the sample file I have send?

**Comment by priore** [comment]
your license code on your sample is incorrect, maybe is a wrong copy, we have sent the correct license code in your email.

**Comment by RexArne** [comment]
wow... fixed. I didn't see that one coming. I had my app all up and running with v1.24 and it never complained about an incorrect license code. looking back in my repository I had it wrong from the very first start...... Thx!!
