### ISSUE TITLE
pod install throwing error

### ISSUE THREAD

**Issue by abhi2412shek** [priore/SOAPEngine#98]
when creating a pod file with the statement as

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'SOAPEngine'

is giving error as

[!] /usr/bin/git clone https://github.com/priore/SOAPEngine.git /var/folders/9c/2lnx53vs1xs72gw1snct0jq40000gp/T/d20160217-2019-5l69y --single-branch --depth 1 --branch v1.21.2

Cloning into '/var/folders/9c/2lnx53vs1xs72gw1snct0jq40000gp/T/d20160217-2019-5l69y'...
warning: Could not find remote branch v1.21.2 to clone.
fatal: Remote branch v1.21.2 not found in upstream origin

**Comment by priore** [comment]
Sorry, two old versions have been removed because the binary was badly compiled or the bitcode was erroneously disabled.

Please, try with a pod install command or try with this steps [pod clear cache](https://gist.github.com/mbinna/4202236)

**Comment by abhi2412shek** [comment]
thanks a lot
